### ISSUE TITLE
System.IndexOutOfRangeException found in INTERNAL_parseEffectStruct() (effect.cs) when newing up SpriteBatch

### ISSUE THREAD

**Issue by hotdiggitydoddo** [FNA-XNA/FNA#10]
![image](https://cloud.githubusercontent.com/assets/2938036/13014042/c8e44bec-d166-11e5-91d9-8ff1156ea634.png)

**Comment by flibitijibibo** [comment]
This is with the latest MojoShader binary from fnalibs? It looks like it wants to parse struct members, but I'm guessing you don't have those in your shaders.

**Comment by hotdiggitydoddo** [comment]
It is.  I ran "git submodule update" from the FNA directory this morning.

**Comment by flibitijibibo** [comment]
Not talking about that, talking about this: http://fna.flibitijibibo.com/archive/fnalibs.tar.bz2

**Comment by hotdiggitydoddo** [comment]
That fixed it.  Thanks, and sorry for the confusion!

**Comment by flibitijibibo** [comment]
No problem, will make this more clear when 16.03 comes out!
