### ISSUE TITLE
[XACT] Looping cue will sometimes not stop when Cue..Stop(AudioStopOptions.Immediate);

### ISSUE THREAD

**Issue by CantStraferight** [FNA-XNA/FNA#101]
Edit - sorry hit enter and it posted it immediately.

I just updated to 17.02 and noticed a looping sound would not stop even though Cue.Stop(AudioStopOptions.Immediate) is called.

It seems nearly every time the looping cue is played but not always.  Trying to call Cue.Stop(AudioStopOptions) again does nothing.

It seems this is not present in 16.12 but is in 17.01

**Comment by flibitijibibo** [comment]
This is the function you'll want to look at:

https://github.com/FNA-XNA/FNA/blob/master/src/Audio/Cue.cs#L492

**Comment by CantStraferight** [comment]
Going to close this. 

Looking into this it turns out my code should never have worked but strangely did before 17.01 

Sorry for wasting your time and thank you for all your work.
