### ISSUE TITLE
FNA project creation without XNA

### ISSUE THREAD

**Issue by msmshazan** [FNA-XNA/FNA#105]
Is it possible to create a project in FNA only without xna. And what are the asset types supported in fna.

**Comment by flibitijibibo** [comment]
1. Yes
2. Images, wav files (can be MSADPCM compressed), XACT projects, Direct3D 9 Effect shaders, Ogg Vorbis and Ogg Theora media files, and any content you can shove into a Texture, Vertex/IndexBuffer, or DynamicSoundEffectInstance. You can make your own content pipeline!

**Comment by msmshazan** [comment]
How can create it without xna any example.
