### ISSUE TITLE
Example for creating FNA project without XNA

### ISSUE THREAD

**Issue by msmshazan** [FNA-XNA/FNA#106]
Can you provide an Example for creating FNA project without XNA.

**Comment by flibitijibibo** [comment]
1. Make a new Solution/Project
2. Add existing project
3. Select FNA.csproj
4. Reference FNA in your new project

From there you can use example XNA code and it'll work the same way. Be sure to include the native libraries, as noted in the wiki.

**Comment by msmshazan** [comment]
But when I created new template project fna namespace got altered with project name.

**Comment by flibitijibibo** [comment]
Template...? What template are you using? Visual Studio should have an option to create an empty Windows project, and from there you add FNA.csproj to the solution as the second project.

**Comment by msmshazan** [comment]
No i just used the export project as template option in visual studio but I guess it doesn't work.(namespaces change)
And Since fna is using sdl2 behind the scenes how far can I use SDL2 functions in the project.

**Comment by flibitijibibo** [comment]
The public exposure of SDL/OpenAL/etc. is intentional, as they are often used to replace features found in System.Windows.Forms and other non-portable C# libraries. But, it sounds like you have the project building now?

**Comment by msmshazan** [comment]
Yep.Thanks.
