### ISSUE TITLE
Feature request: Support for System.Windows.Forms.Control.ClientSize set.

### ISSUE THREAD

**Issue by Gert-Jan** [FNA-XNA/FNA#113]
When resizing an XNA window the default behavior is to keep drawing to the same sized backbuffer, which will be drawn to the same area in the window. So when enlarging a window the newly gained space will be blank on the left and bottom of the original backbuffer. When shrinking a window some content on the left and bottom will fall off the window and will not be visible.

In pure XNA the only way to 'fix' that is to subscribe to the GameWindow.ClientSizeChanged event and do something like this: 
```
private void OnWindowSizeChanged(object o, EventArgs e)
{
	graphicsDeviceManager.PreferredBackBufferWidth = game.Window.ClientBounds.Width;
	graphicsDeviceManager.PreferredBackBufferHeight = game.Window.ClientBounds.Height;
	graphicsDeviceManager.ApplyChanges();
}
```

This will change both the backbuffer resolution and implicitly also change the window size (again). Which is cool until you are doing that on modern high-dpi screens where you get super high resolutions which can impact framerate quite a bit.

Preferably you would not want to lock the backbuffer size to the window size, but scale the backbuffer to the window size instead.

On XNA/Windows there is a way (albeit hacky) to do this which goes something like this:
```
private void OnWindowSizeChanged(object o, EventArgs e)
{
	// Remember the new preferred window size
	int newWindowWidth = game.Window.ClientBounds.Width;
	int newWindowHeight = game.Window.ClientBounds.Height;

	// This will implicitly set the window size back to the original backbuffer size
	graphicsDeviceManager.PreferredBackBufferWidth = graphicsDeviceManager.PreferredBackBufferWidth;
	graphicsDeviceManager.PreferredBackBufferHeight = graphicsDeviceManager.PreferredBackBufferHeight;
	graphicsDeviceManager.ApplyChanges();

	// For some reason this does scale the backbuffer to the new window size...
	IntPtr hWnd = game.Window.Handle;
	System.Windows.Forms.Control control = System.Windows.Forms.Control.FromHandle(hWnd);
	control.ClientSize = new System.Drawing.Size(newWindowWidth, newWindowHeight);
}
```

I haven't tested the default XNA behavior mentioned here on FNA on Mac/Linux, so I'm not sure what the exact behavior is there. If it's similar to XNA on Windows, something like game.Window.ClientSizeEXT would be very welcome (or maybe game.Window.PlsScaleBackbufferOnWindowResizeKtnxbyeEXT = true; would also work I guess ;))

**Comment by flibitijibibo** [comment]
We actually can't quite implement this in the same way, as the equivalent is just calling `SDL_SetWindowSize(game.Window.Handle, newWindowWidth, newWindowHeight)`, but I don't think this will actually work as WinForms does (and it's definitely weird).

That said, I do have something that works for FNA, and might work for XNA as well. We actually did something quite like this in FEZ, where we have a supersampled mode that simply resets the GraphicsDevice without modifying the window size. The way it worked was pretty simple:

```
// Blah blah apply usual settings
graphics.ApplyChanges();

// This is the interesting part!
if (supersampled)
{
    int width, height;
    // A bunch of math to determine the correct viewport size
    graphics.GraphicsDevice.PresentationParameters.BackBufferWidth = width;
    graphics.GraphicsDevice.PresentationParameters.BackBufferHeight = height;
    // Note, NOT ApplyChanges!
    graphics.GraphicsDevice.Reset();
}
```

The result is that the GLDevice backbuffer gets changed while the window size remains the same, and FNA's faux-backbuffer scales to the window size accordingly. So a possible equivalent for your function might be this:

```
private void OnWindowSizeChanged(object o, EventArgs e)
{
    PresentationParameters params = graphicsDeviceManager.GraphicsDevice.PresentationParameters.Clone();

    params.BackBufferWidth = graphicsDeviceManager.PreferredBackBufferWidth;
    params.BackBufferHeight = graphicsDeviceManager.PreferredBackBufferHeight;
    graphicsDeviceManager.GraphicsDevice.Reset(params);
}
```

This might have some weird timing issues, however; note that XNA actually calls ApplyChanges implicitly when the window is resized, as GDM wires itself to the very same callback:

https://github.com/FNA-XNA/FNA/blob/master/src/GraphicsDeviceManager.cs#L174
https://github.com/FNA-XNA/FNA/blob/master/src/GraphicsDeviceManager.cs#L379

If I'm correct, what's happening is that GDM's callback is first, then yours is after that. So it _should_ be fine, assuming XNA scales the backbuffer in the same way that FNA does...?

**Comment by Gert-Jan** [comment]
Ah thanks, that OnWindowsSizeChanged method actually works. Needed to sacrifice my new forced window aspect ratio (requires set window size), but wasn't to attached to that anyway.

**Comment by flibitijibibo** [comment]
Neat! Had no idea FNA and XNA behaved in the same way for backbuffer size vs. window size. Saves me quite a bit of fuss trying to reproduce Windows.Forms... :P

**Comment by Gert-Jan** [comment]
Pushed this change in SpeedRunners to Steam an hour-or-so ago. I guess it should work on the FNA/Linux build as well now. Only had to add a bunch of SDL2/Windows specific code for borderless windowed.
