### ISSUE TITLE
Unable To Run Windows 64-bit.

### ISSUE THREAD

**Issue by msmshazan** [FNA-XNA/FNA#114]
Unable To Run Windows 64-bit. How can I get precompiled dependencies for 64-bit.

**Comment by flibitijibibo** [comment]
You'll have to find them yourself. SDL2 and OpenAL Soft are downloadable, the rest you'll want to build on your own. All that said, on Windows 64-bit is largely unsupported.

**Comment by flibitijibibo** [comment]
Closing due to old age. When we bump the glibc version requirement I'll probably look into building Win64 with MinGW.

**Comment by flibitijibibo** [comment]
Here's a test build of the Windows 64-bit libraries, they probably don't work but it's worth trying:

http://www.flibitijibibo.com/fna-mingw.tar.bz2
