### ISSUE TITLE
Possible Bug: RenderTarget2D Dispose doesn't look like it frees glColorBuffer

### ISSUE THREAD

**Issue by TrevorSundberg** [FNA-XNA/FNA#116]
I create and dispose render targets when switching levels. I've been having a bug where after a long time of running and a lot of level switches, the game starts consuming a huge amount of memory. I believe this is due to filling the GPU with textures/render targets, and then having it switch to paging memory with the CPU. The game also intensely lags at this point.

I realized that I completely forgot to call Dispose on the RenderTarget2D, so I made sure to do that. This made a lot of sense since I see this in the GraphicsResource finalizer:
```
	// Pass false so the managed objects are not released
	// FIXME: This can lock up your game from the GC! -flibit
	// Dispose(false);
```

Meaning that Dispose was not being called when they were collected by the GC. However, when looking into Dispose on RenderTarget2D, I noticed it is only doing:

	`GraphicsDevice.GLDevice.AddDisposeRenderbuffer(glDepthStencilBuffer);`

Should glColorBuffer be disposed also or is there some OpenGL magic that automatically takes care of it?

**Comment by flibitijibibo** [comment]
Yes it should, but note that the color buffer is only allocated for multisample renderbuffers. If that's not the case here, then you've got a leak somewhere else... a good way to track graphics resources is to look at those Lists held by the GLDevice; if something is leaking then one of those lists will get really big over time.

Either way, yeah, should probably clean that up:

https://github.com/FNA-XNA/FNA/commit/93e25c728588bb1587868e077f59ba56157afa26

**Comment by flibitijibibo** [comment]
https://github.com/FNA-XNA/FNA/commit/ca889be656b67494e282616379a55c296ef17173

**Comment by TrevorSundberg** [comment]
I was so confused by the multi-sample thing since in my head... "Then where is the color target??"
I realize now that RenderTarget2D inherits from Texture2D... derp!

**Comment by flibitijibibo** [comment]
I believe this particular issue is fixed now, but if you find other leaks feel free to open a new issue or track them in this thread, whatever works best.
