### ISSUE TITLE
Windows 64 Bit Support

### ISSUE THREAD

**Issue by jeffphilp** [FNA-XNA/FNA#12]
In the precompiled libraries that can be downloaded, there is a universal macos, and 32/64 bit support for linux, and 32 bit dlls for windows.  Is there a reason 64bit dlls for Windows cannot be used with FNA?

**Comment by flibitijibibo** [comment]
No reason I'm aware of, I just don't target it since XNA never targeted it either and multiarch Windows is WAY too difficult to be worth my time (Linux/OSX do not care about the C# assembly target arch). You can try, but you get to collect the DLLs yourself.

**Comment by jeffphilp** [comment]
Awesome thanks for your really quick response.

**Comment by RobJellinghaus** [comment]
jeffphilp, did you succeed?  If so, I would be quite interested.  I am about to try this as well and if I make it work I will post a .zip of the working 64-bit DLL collection.

**Comment by jeffphilp** [comment]
@RobJellinghaus Yes I did succeed, though I only make use of the Graphics subsystems.  If you refer to the contribution portion of the Wiki it has the source of the required native libraries.

**Comment by RobJellinghaus** [comment]
Thanks.  Just pulled the FNA-XNA/SDL-Mirror and MojoShader repos.  Any remedial tips on building MojoShader on Windows?  I am not entirely sure how to build a CMake file on Windows...

Thanks very much for the GitHub staging repos, Ethan :-)

**Comment by jeffphilp** [comment]
I just downloaded CMake (https://cmake.org/) windows version and got it to generate Visual Studio 2016 64Bit solutions, and then build from inside Visual Studio.

**Comment by RobJellinghaus** [comment]
Sweet, thanks.  Have to time out tonight but will try that out tomorrow.  

Was able to build x64 version of SDL-Mirror without difficulty, though weirdly the test/sample projects (e.g. testscale, etc.) seem to only want to run in VS2015 under the debugger -- directly double-clicking them in the build directory (VisualC\Win32\Debug\testscale.exe for example) pops open a momentary window which immediately closes.

**Comment by RobJellinghaus** [comment]
OK, I was able to build x64 versions of SDL-Mirror and Mojoshader.  Or, at least, the compilations run and link, and produce what seem to be legitimate x64 versions of SDL2.dll and MojoShader.dll.

However, I have a C# "FNATest" project which I am trying to build as x64, to ensure .NET has access to the full system memory.  I have the x64 version of SDL2.dll in the FNATest\bin\Debug folder.  The FNATest project itself is set to x64.

But when I run FNATest, I get a TypeInitializationException from FNAPlatform.CreateWindow(), with the innermost exception being "An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)"  Which is exactly what you would expect from a platform mismatch... but I have no real idea how to remedy it.

jeffphilp, do you happen to have an example x64 project using FNA's graphics layer (which is also all I want)?  My current broken example is in my main project's git repo https://github.com/RobJellinghaus/Holofunk -- it's the FNATest subdirectory.  Any suggestions would be most welcome.  Thanks very much!
