### ISSUE TITLE
Game exit when I start it

### ISSUE THREAD

**Issue by Zino2201** [FNA-XNA/FNA#120]
Huh I don't know if it's a duplicate issue but whatever... (sorry for my english, it's not my native language) ^^

I have installed the native libs (x64). My game start normally (no exceptions at runtime) but when the program reach my "new Game()" line which call the Game class, it crash... 

I have this problem for hours...

(I readed the docs)

**Comment by flibitijibibo** [comment]
The debugger doesn't mention anything?

**Comment by Zino2201** [comment]
No :| The exit code is 0, no error

**Comment by flibitijibibo** [comment]
Try stepping through to see which line fails in FNA - as long as you can step through FNA a line-by-line check should tell us what's up.

**Comment by Zino2201** [comment]
Okay.

**Comment by Zino2201** [comment]
Huh it's working now... I don't know how but whatever.. (maybe a random vs bug)
