### ISSUE TITLE
[Keyboard - Azerty] Some keys not recognized

### ISSUE THREAD

**Issue by Scellow** [FNA-XNA/FNA#121]
Hello

After having that issue on MonoGame i decided to try it on FNA.. and guess what? same issue :p

Luckily FNA prints what's wrong:

```
EY/SCANCODE MISSING FROM SDL2->XNA DICTIONARY: SDLK_COLON SDL_SCANCODE_PERIOD
KEY/SCANCODE MISSING FROM SDL2->XNA DICTIONARY: SDLK_COLON SDL_SCANCODE_PERIOD
KEY/SCANCODE MISSING FROM SDL2->XNA DICTIONARY: SDLK_EXCLAIM SDL_SCANCODE_SLASH
KEY/SCANCODE MISSING FROM SDL2->XNA DICTIONARY: SDLK_ASTERISK SDL_SCANCODE_BACKSLASH
KEY/SCANCODE MISSING FROM SDL2->XNA DICTIONARY: 249 SDL_SCANCODE_APOSTROPHE
KEY/SCANCODE MISSING FROM SDL2->XNA DICTIONARY: SDLK_DOLLAR SDL_SCANCODE_RIGHTBRACKET
KEY/SCANCODE MISSING FROM SDL2->XNA DICTIONARY: SDLK_CARET SDL_SCANCODE_LEFTBRACKET
KEY/SCANCODE MISSING FROM SDL2->XNA DICTIONARY: SDLK_RIGHTPAREN SDL_SCANCODE_MINUS
```

And Alt+Gr does nothing, so it miss even more characters

I wonder why nobody reported that issue yet, AZERTY keyboard layout is used in France and Belgium, probably Canada too

https://github.com/MonoGame/MonoGame/issues/5715

**Comment by flibitijibibo** [comment]
We have some AZERTY users but only a couple keys have ever been reported. You'll want to add the correct keys here:

https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/SDL2_FNAPlatform.cs#L1848

I'll leave it up to you to figure out what they're actually supposed to map to... does XNA even recognize those keys?

**Comment by flibitijibibo** [comment]
Also note that if you're just trying to do text input, we have [TextInputEXT](https://github.com/FNA-XNA/FNA/wiki/5:-FNA-Extensions#textinputext) for that.

**Comment by Scellow** [comment]
I can't find the equivalent of the SDL keycode to XNA "Keys", my english isn't perfect i used this to get the name of the keys https://www.computerhope.com/keys.htm

It seems to be a pain to get this right for both XNA and MonoGame
This is only for TextInput but still.. i'll checkout TextInputEXT thanks!

**Comment by flibitijibibo** [comment]
Closing due to old age, but it sounds like this was something TextInputEXT was already prepared for... if you ever have time, definitely figure out what those keysyms should line up with in XNA (if it even registers in XNA, if not I'd still like to see where we can fit it in).

**Comment by flibitijibibo** [comment]
A commit from the upcoming SDL 2.0.6 release, may be relevant here:

https://hg.libsdl.org/SDL/rev/fe8057094a5a

**Comment by tuxPM** [comment]
FNA map SDL keycode to XNA by default as opposed to scancode. Adding all possible keycodes will create conflict between layouts. For example, in azerty keyboard "6" match SDLK_MINUS, which is the key after "0" in qwerty. I think the best practice for games is to use scancode by default (button events binding) and TextInput for handling text.
FNA allow you to force scancode usage simply be setting environment variable   
`FNA_KEYBOARD_USE_SCANCODES=1`

If you still want to use SDL keycode for azerty, you could add the non-conflict keycode to INTERNAL_keyMap in SDL2_FNAPlatform.cs. For example to match azerty 0..9 (except 4 and 6) to D0..D9

```
{ (int) 224/*à*/,			Keys.D0 },
{ (int) SDL.SDL_Keycode.SDLK_AMPERSAND,			Keys.D1 },
// remember to disable	{ 'é' /* FIXME: BEPO SDL2? -flibit */,		Keys.None },
{ (int) 233/*é*/,			Keys.D2 },
{ (int) SDL.SDL_Keycode.SDLK_QUOTEDBL,			Keys.D3 },
//{ (int) SDL.SDL_Keycode.SDLK_QUOTE,			Keys.D4 },
{ (int) SDL.SDL_Keycode.SDLK_LEFTPAREN,			Keys.D5 },
//{ (int) SDL.SDL_Keycode.SDLK_MINUS,			Keys.D6 },
{ (int) 232/*è*/,			Keys.D7 },
{ (int) SDL.SDL_Keycode.SDLK_UNDERSCORE,			Keys.D8 },
{ (int) 231/*ç*/,			Keys.D9 },
```

Other unbinded azerty keycodes you may add:

```
SDLK_RIGHTPAREN SDL_SCANCODE_MINUS Keys.OemMinus
SDLK_DOLLAR SDL_SCANCODE_RIGHTBRACKET Keys.OemCloseBrackets
249/*ù*/ SDL_SCANCODE_APOSTROPHE  Keys.OemQuotes
SDLK_ASTERISK SDL_SCANCODE_BACKSLASH Keys.OemBackslash
SDLK_LESS SDL_SCANCODE_NONUSBACKSLASH Unsupported ?
SDLK_COLON SDL_SCANCODE_PERIOD Keys.OemPeriod
SDLK_EXCLAIM SDL_SCANCODE_SLASH Keys.OemQuestion
```
