### ISSUE TITLE
Trying to use GZIP to save compressed files, missing "libMonoPosixHelper.dylib" on MacOSX and corresponding .so file in linux.

### ISSUE THREAD

**Issue by mklingen** [FNA-XNA/FNA#122]
When using GZIPStream, ie

```
using(GZipStream zip = 
 new GZipStream(new FileStream(filePath, FileMode.OpenOrCreate), CompressionMode.Compress)) {
...
}
```

I get a`DLLNotFoundException` on MacOSX, and in Linux. I have tried distributing the appropriate `.so` file in linux, and that seems to fix the problem there, but not so for Mac OS. I noticed MonoKickstart has an entry for the dylib file, but it can't seem to find it at runtime.

**Comment by flibitijibibo** [comment]
Betcha need MonoPosixHelper - here's where I keep my copies, though the versions may not match...

http://www.flibitijibibo.com/mphosx.tar.bz2
http://www.flibitijibibo.com/mph32.tar.bz2
http://www.flibitijibibo.com/mph64.tar.bz2

I haven't found a comfortable place to put these yet... it's seldom required so a part of me wants to keep it out of the precompiled folder, but recently it's become a requirement for versions to match more closely with the runtime version so fnalibs wouldn't work either. I'll open up a MonoKickstart issue for this, for now those archives should take care of things.

**Comment by mklingen** [comment]
Thank you so much.

**Comment by mklingen** [comment]
I'm sorry, but copying this into X.app/Content/MacOS or X.app/Content/MacOS/osx doesn't seem to have any effect. Would I still get a dllNotFound exception even if it was just a problem with versioning?

**Comment by flibitijibibo** [comment]
It would likely crash elsewhere, I bet this is a problem with CPU architecture - make sure that you're using the latest builds for everything; kick.bin.osx should be a 64-bit binary (you can check with `file` in Terminal.app).

**Comment by mklingen** [comment]
Yep, its 64 bit binary. Will update the builds to try. Alternatively I can abandon gzip and use something else.

**Comment by flibitijibibo** [comment]
A build would be cool to have!

LZMA may be worth looking at, if you want to avoid MPH: http://www.7-zip.org/sdk.html

**Comment by mrhelmut** [comment]
FYI, I had the same issue and ended up using the open source version of ```GZipStream``` from Ionic.Zip, which provides the exact same API and is a pure C# library without any external dependencies on Mono platforms.

https://dotnetzip.codeplex.com/
