### ISSUE TITLE
On Linux, `Mouse.SetPosition` doesn't take effect until the user moves the mouse.

### ISSUE THREAD

**Issue by mklingen** [FNA-XNA/FNA#127]
On windows FNA or XNA if I do the following (assuming the original mouse position is `155, 240`):

```
var mouse_before = Mouse.GetState(); 
Mouse.SetPosition(100, 100);
var mouse_after = Mouse.GetState();
Console.Out.WriteLine("{0}, {1} -> {2}, {3}", mouse_before.X, mouse_before.Y, mouse_after.X, mouse_after.Y);
```

I get `155, 240 -> 100, 100` as expected, but on 64 bit linux, I get `155, 240 -> 155, 240` until the user moves the mouse, then the mouse position jumps to `100, 100` plus whatever displacement the mouse had. It seems that `Mouse.SetPosition` isn't actually affecting anything until a mouse event of some kind is received.

**Comment by flibitijibibo** [comment]
This is with the latest fnalibs? Try making a basic SDL2# test and if we can replicate this then you can submit this as an SDL issue.

You can also give Mouse.RelativeMouseModeEXT a try, if you want.

**Comment by flibitijibibo** [comment]
Looks like this was in Unreal 4 as well, Ryan's looking at it:

https://twitter.com/icculus/status/905055573808439297

**Comment by mklingen** [comment]
Oh, so it goes deeper than I thought! Good to see its being looked at.

**Comment by flibitijibibo** [comment]
This will be fixed in the next update, probably the 2.0.6 release (or the next RC):

https://hg.libsdl.org/SDL/rev/9e33d1be5d65

**Comment by flibitijibibo** [comment]
SDL 2.0.6 was released today, I'll try to get builds out by Monday morning. Will close this when it's live!

**Comment by flibitijibibo** [comment]
fnalibs.tar.bz2 has been updated with SDL 2.0.6!
