### ISSUE TITLE
First frame doesn't render properly (very minor)

### ISSUE THREAD

**Issue by Alan-FGR** [FNA-XNA/FNA#128]
Hello there, even on the simplest example, when I render say a sprite, the first frame doesn't render properly. My rig displays a purple color for the alpha, and it's strange because depending on the blend mode I can see a 'hole' with that purple color in the place where the sprite should render, it's not a scissoring problem because the 'hole' isn't axis-aligned. I've double-checked the code, and it's certainly not any of the usual suspects like resources not loaded. I suspect it has something to do with the shaders, but I guess they are compiled upon loading the resource right?
Anyway, everything works fine after that first frame, so it's a very minor issue. I'm interested in knowing if other people reproduce that. At the moment I'm on a Nvidia Kepler, Win7, latest drivers. I'll try on another hardware soon.

**Comment by flibitijibibo** [comment]
What does apitrace show?

http://apitrace.github.io/

**Comment by Alan-FGR** [comment]
Upon further investigation, and especially after reproducing the problem with a different framework, I concluded the problem elsewhere. I'm investigating it it's related to some problems with nvoglv modules I was having when working with OpenGL shaders. In any case, due the fact I couldn't reproduce it in another machine, and the same problem happens with another fw/engine, I'm ruling out the possibility of FNA being the culprit here. Sorry for the false alarm :P.

**Comment by Alan-FGR** [comment]
Update: Was going to investigate this a bit but cannot reproduce anymore.
