### ISSUE TITLE
Incorrect type T on DrawUserIndexedPrimitives

### ISSUE THREAD

**Issue by jeffphilp** [FNA-XNA/FNA#13]
In GraphicsDevice:
```
public void DrawUserIndexedPrimitives<T>(
    PrimitiveType primitiveType,
    T[] vertexData,
    int vertexOffset,
    int numVertices,
    int[] indexData,
    int indexOffset,
    int primitiveCount, 
    VertexDeclaration vertexDeclaration
    ) where T : struct, IVertexType {
```

T is said to extend IVertexType, but the MSDN documentation https://msdn.microsoft.com/en-us/library/ff433983(v=xnagamestudio.40).aspx shows that T does not extent IVertexType.

**Comment by flibitijibibo** [comment]
Looks like this was a bug inherited from MonoGame that I, the XNA4SpecTest, and most games never caught... everybody must really like using IVertexType. Anyway:

https://github.com/FNA-XNA/FNA/commit/6d4c50ce7f6a07d8386c49a9e23a193535896ab3
