### ISSUE TITLE
Exception thrown: 'System.TypeInitializationException' in FNA.dll

### ISSUE THREAD

**Issue by ArcadeZtheWolf** [FNA-XNA/FNA#133]
Windows 10 x64
FNA 17.10

I've been trying to switch from XNA to FNA but whenever I try to run my program it gives me this error:
![image](https://user-images.githubusercontent.com/17486924/31357906-66c82bda-acf8-11e7-8557-574762e651ca.png)

I have all the native libraries from [fnalibs](http://fna.flibitijibibo.com/archive/fnalibs.tar.bz2) and the FNA.dll in the output folder. I don't understand what's going wrong and I need help.

My output folder looks like this:
![image](https://user-images.githubusercontent.com/17486924/31358120-27600f98-acf9-11e7-9354-997c88062821.png)

**Comment by flibitijibibo** [comment]
If your game is built using the x86 configuration be sure that the libs you have are all 32-bit. The x86 folder has the libs you need in that case. I can’t tell from here but it looks like you may have the x64 libs in the output folder. It will only pull libs from the folders if you use the code provided in the Windows API docs regarding 64-bit support.

**Comment by flibitijibibo** [comment]
Just added this, if SDL2.dll is missing or the wrong format you should get something in stdout now (or at the very least, you'll run into the catch block):

https://github.com/FNA-XNA/FNA/commit/68e6f0afd148070c4c921baf7e19ff1c5e87651c

**Comment by ArcadeZtheWolf** [comment]
Thanks! I switched the dlls and it worked.
