### ISSUE TITLE
SDL2 not recognize characters on it-IT keyboard

### ISSUE THREAD

**Issue by Pack4Duck** [FNA-XNA/FNA#134]
this is it layout keboard: https://imgur.com/a/1wQ73
Red square are chars not recognized by SDL2

Message appear is:
KEY/SCANCODE MISSING FROM SDL2->XNA DICTIONARY: SDLK_LESS DL_SCANCODE_NONUSBACKSLASH

SDLK_LESS apear only with < > chars, else appear a code (242,224,232,249)

**Comment by flibitijibibo** [comment]
Any idea what XNA produces for these keys? These definitely don’t map to anything in the Keys enum... here’s the Dictionary if you need it:

https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/SDL2_FNAPlatform.cs#L1835

**Comment by flibitijibibo** [comment]
Closing due to old age - you may want to grab some XNA games with key binding menus and see what those keys map to in XNA. From there we should be able to add support, but without that we'd just be making wild guesses.
