### ISSUE TITLE
FNAPlatform.CreateWindow

### ISSUE THREAD

**Issue by dm67x** [FNA-XNA/FNA#14]
Today, I wanted to use FNA for my game project instead of Monogame and when i run my code with visual studio 2013, i got an exception : 

> An unhandled exception of type 'System.TypeInitializationException' occurred in FNA.dll

It's refered to the line 290 of Game.cs (in FNA).

I'm on Windows 10.

And that's my game code : 

``` C#
class MyGame : Game
    {
        private static MyGame instance = null;
        private GraphicsDeviceManager graphics;
        private SpriteBatch spriteBatch;

        public static MyGame GetInstance()
        {
            if (instance == null)
                instance = new MyGame();
            return instance;
        }

        private MyGame()
        {
            graphics = new GraphicsDeviceManager(this);

            graphics.PreferredBackBufferWidth = 1024;
            graphics.PreferredBackBufferHeight = 600;

            Content.RootDirectory = "Content";
        }

        protected override void Initialize()
        {
            base.Initialize();
        }

        protected override void LoadContent()
        {
            spriteBatch = new SpriteBatch(GraphicsDevice);

            base.LoadContent();
        }

        protected override void Update(GameTime gameTime)
        {
            if (Keyboard.GetState().IsKeyDown(Keys.Escape))
                this.Exit();

            base.Update(gameTime);
        }

        protected override void Draw(GameTime gameTime)
        {
            GraphicsDevice.Clear(Color.Black);
            base.Draw(gameTime);
        }
    }
```

**Comment by flibitijibibo** [comment]
This doesn't tell us a whole lot - I assume you have the native libraries?

Also, get rid of that static Instance variable - initialize your Game with a using statement so that your class gets consistently initialized on startup and is appropriately disposed at program exit.

**Comment by dm67x** [comment]
The singleton pattern or an instance don't change anything. I've downloaded FNA from the website and I add FNA to my project.

**Comment by flibitijibibo** [comment]
Can you send me a binary build of the game?

**Comment by dm67x** [comment]
[debug.zip](https://github.com/FNA-XNA/FNA/files/135538/debug.zip)
[release.zip](https://github.com/FNA-XNA/FNA/files/135539/release.zip)

**Comment by dm67x** [comment]
Sorry it's my fault i forgot the native library.

**Comment by flibitijibibo** [comment]
No problem, this report still ended up being helpful - I'm surprised it didn't throw DllNotFoundException, will have to keep this in mind if it shows up again.

**Comment by darfink** [comment]
Just wanted to chime in and say that I got the same weird exception message, until after I added SDL2 library, then I received a `DllNotFoundException` for OpenAL.

The inner exception of the `TypeInitializationException` is `DllNotFoundException` though. So if possible it should be fixed, I can only assume this has caught many more by surprise.

**Comment by flibitijibibo** [comment]
It's only a surprised if you don't read the docs, but I might be biased as the author of those docs.
