### ISSUE TITLE
GLSL shaders support

### ISSUE THREAD

**Issue by Alan-FGR** [FNA-XNA/FNA#142]
Hello there.
Since FNA uses OpenGL (min 2.1), I wonder if it's possible to use GLSL shaders instead of Mojoed HLSL, I've tried loading compiled GLSL just like the compiled DX effects to no avail.
Thank you.

**Comment by flibitijibibo** [comment]
Nope! You would need to implement an Effect Framework equivalent for GLSL and then match the data structures to work with the C Effect API.

**Comment by Alan-FGR** [comment]
@flibitijibibo Fair enough. I've no intention of implementing that; HLSL is close enough imho (to manually convert snippets) and I guess the Mojo output is pretty close in terms of efficiency to a manual conversion anyway. It's a bit odd though that you gotta write HLSL for an OpenGL (exclusively) game, so I'm trying to use some GLSL snippets and I got to convert them to HLSL and they get Mojoed to run on OpenGL, but I've no problem with that personally. If it was easy to use GLSL they I would, since it apparently isn't, no big deal at all.
