### ISSUE TITLE
Publish FNA at NuGet

### ISSUE THREAD

**Issue by rds1983** [FNA-XNA/FNA#144]
Hi,
Is FNA officialy published at NuGet? Are there plans to do it(if it's not published)?

**Comment by flibitijibibo** [comment]
There are no plans to publish anything on NuGet until the system supports source-only packages. We don’t ship binary blobs on our site and I won’t do it on theirs either.

**Comment by nikarh** [comment]
Hi,
sorry for resurrecting this old issue, but AFAIK it actually is possible to upload source-only packages to NuGet (found [this article](https://medium.com/@attilah/source-code-only-nuget-packages-8f34a8fb4738) describing how to do it)

**Comment by danielcrenna** [comment]
@nikarh @flibitijibibo I have a NuGet in pre-release called `FNA.Package`, it has a custom .targets file to automatically pull in `fnalibs` and set the DLL directory, so it should be one reference. It uses the new `PackageReference` `GeneratePathProperty` feature to soft link the FNA sources directly into your .csproj, so you get the source experience. In my experience the NuGet source-only packages are terrible. The files are embedded/hidden in the obj folder under an obscure GUID, meaning you'd have to know they were there, which only really helps when it crashes, making it no better than a NuGet binary package with source symbols.

**Comment by tomcashman** [comment]
Just curious as to why binary blobs being shipped on nuget is a bad thing? Devs already download the binary files for the native libs. It would make life a lot easier and can be set up using CI/CD to be automatically done when a new tag is made.

**Comment by danielcrenna** [comment]
@tomcashman Have you tried FNA.Package? It has limitations obviously, since it's bringing in source code, so you have to be using csproj's with transitive references support, otherwise you'll have conflicts between libraries, and you have to have a "common" that all other packages reference. Something that I've basically abandoned in favor of just cloning, which is still the most flexible option.

That said it's not that much work to modify the .targets files from FNA.Package and ship a version with blobs.

**Comment by lithiumtoast** [comment]
@tomcashman It's possible to have a NuGet package without source code and just flat files. Care would need be done to ensure the dynamic link library files (`.dll`/`.dylib`/`.so`) would be copied over correctly on build from the NuGet restore directory using a NuGet package `.props`/`.targets` file.

**Comment by ryancheung** [comment]
Try [FNA.NET](https://github.com/FNA-NET/FNA)

**Comment by wattsyart** [comment]
FNA already runs on .NET 6. So I guess the point is the NuGet packages?

**Comment by thatcosmonaut** [comment]
https://github.com/FNA-XNA/FNA/wiki/0:-FAQ#where-is-the-nuget-package
