### ISSUE TITLE
How to even load textures/models/etc?

### ISSUE THREAD

**Issue by TheAwesomeGem** [FNA-XNA/FNA#146]
Coming from LibGDX background, it's a bit confusing trying to load a textures from a .png file and such. I am reading the wiki and apparently I need a content builder/processor that process and compile all of my resources before I can even use it on my game? Is that true?

**Comment by flibitijibibo** [comment]
For Models, yes, a pipeline is required.

For textures and raw vertex/index data, you can do pretty much whatever you want. Textures can be loaded with Content.Load<Texture2D> or Texture2D.FromStream(), or you can load the texture data yourself and call Texture.SetData(yourData). If you have your own model/animation system and you just need buffer objects, you can create those directly and call, for example, VertexBuffer.SetData(yourData).

Shaders are one case where you do need a compiler, but it's not terribly complicated: Grab the DirectX SDK and inside that should be 'fxc.exe', and you can use that to compile Effects. We support the fx_2_0 profile.

**Comment by flibitijibibo** [comment]
Closing due to old age, but I think I answered the question...
