### ISSUE TITLE
Windows the only development platform?

### ISSUE THREAD

**Issue by ShalokShalom** [FNA-XNA/FNA#152]
>> The game is developed using XNA/FNA, which only supports a windows development environment.

https://github.com/CompletelyFairGames/dwarfcorp#cross-platform-development

**Comment by flibitijibibo** [comment]
I think that's just their setup. FNA always has and always will be primarily developed on Linux, which is what my work environment is using.

**Comment by ShalokShalom** [comment]
Can look into it once again?

**Comment by flibitijibibo** [comment]
Sounds like you’re pretty into it, so I’ll leave that up to you! I’m currently working on other things and won’t have time for a few months.

**Comment by ShalokShalom** [comment]
Ah, I see. Seems like this specific component is Windows specific, while you avoid that one att all, as I can read in another issue.

Much fun and happy hacking ^-^

**Comment by ShalokShalom** [comment]
Ah, I see. Seems like this specific component is Windows specific, while you avoid that one att all, as I can read in another issue.

Much fun and happy hacking ^-^

**Comment by FabioMen10** [comment]
I have that doubt too. But I did not have the courage to ask why it goes against everything that he has shown on his Patreon page. [https://www.patreon.com/posts/xblig-fna-and-13853646](url)
When downloading I was able to see that it was a visual studio project solution.

**Comment by ShalokShalom** [comment]
This gives us 404.

**Comment by flibitijibibo** [comment]
Hope this answers any questions you had left:

http://flibitijibibo.com/xnacontent.html
