### ISSUE TITLE
[Suggestion] Merge XNAExtras into FNA

### ISSUE THREAD

**Issue by CNAmira** [FNA-XNA/FNA#156]
[XNAExtras](https://blogs.msdn.microsoft.com/garykac/2006/12/01/xnaextras-update/) provides some extra functions to XNA and it should work with FNA.
NO incompatible changes needed.

**Comment by flibitijibibo** [comment]
Looking at it briefly it seems to just be a series of libraries that use XNA. Provided there aren't any Win32 dependencies they should work fine as-is with FNA and we don't need to integrate them into our project. Games can still use it though!
