### ISSUE TITLE
Can't load ogg files through Content.Load

### ISSUE THREAD

**Issue by DrGurka** [FNA-XNA/FNA#157]
I'm getting an unhandled exception each time i'm trying to load ogg files.

Here's the code
`Song song = Content.Load<Song>(@"Music\Lines of Code")`

And here's the error
`An unhandled exception of type 'System.BadImageFormatException' occurred in FNA.dll
Additional information: An attempt to load an invalid format program was made. (Exception from HRESULT: 0x8007000B)`

The files i'm trying to load does have the .ogg extension and is accompanied with an xnb as you can see in this file [Music.zip](https://github.com/FNA-XNA/FNA/files/1800896/Music.zip)

I'm using the latest version of FNA and i can get the game running if i just remove the above code, but without music ofc

**Comment by flibitijibibo** [comment]
`BadImageFormatException` almost always means your architectures don't match - be sure you have all 32-bit or all 64-bit exe/dll files.

**Comment by DrGurka** [comment]
Yeah, i managed to fix it now by building everything in 64-bit, it was in Any CPU mode also. Thanks for the help!
