### ISSUE TITLE
Can not load a shader compiled with fxc

### ISSUE THREAD

**Issue by BurgerBob** [FNA-XNA/FNA#158]
I'm trying to load an effect in FNA that I built with fxc.exe, and I have an out of memory exception.
Here is a repro :

[shader test.zip](https://github.com/FNA-XNA/FNA/files/1808267/shader.test.zip)

It is a shader that compiles with MonoGame, both in directx and openGL mode.

**Comment by flibitijibibo** [comment]
Compile with `fx_2_0` instead of `fx_4_0` and it should work after that; your .bat file is attempting to build a SM4 effect which is not supported. Also, you'll want to set `/DOPEN_GL` as a parameter in your .bat command.

**Comment by BurgerBob** [comment]
Ok, it works perfectly, thank you for the quick answer !
Maybe you want to add these details in https://github.com/FNA-XNA/FNA/wiki/2:-Building-with-FNA

**Comment by flibitijibibo** [comment]
I'll file this as something to document under #154, as that define is specific to MG and is not something found in XNA games. (I do have to wonder why it's "OPEN_GL" and not "OPENGL" though...)

For now I've added `fx_2_0` as a qualifier in the docs for those using FXC:

https://github.com/FNA-XNA/FNA/wiki/2:-Building-with-FNA#2a-about-effect-support
