### ISSUE TITLE
SetDllDirectory is not foolproof for 64-bit support

### ISSUE THREAD

**Issue by LennardF1989** [FNA-XNA/FNA#162]
I want to respond to the note mentioned here: https://github.com/FNA-XNA/FNA/wiki/4:-FNA-and-Windows-API#64-bit-support

After recent bug reports I started investigating an issue where some people get a `DllNotFoundException` on Windows, while all the files were in the proper location. Out of sheer desperation, I asked them to move either the contents of the x86 or the x64 folder to the game-root and was surprised to learn this actually worked!

A bit of googling later, I found the issue comes from the usage of `SetDllDirectory`. It appears that it can happen that some programs that hook other programs, call this method themselves, in the context of the process they are hooking. This effectively means that hooks overwrite whatever path my game sets!

There are two workarounds for this:
- Use `AddDllDirectory` instead. This is more graceful as the path it adds is not replaced by the use of `SetDllDirectory`, it actually gives a path higher priority during the search! The downside is that hooks can also break this one way or another, but I would assume none would actually do that.
- Use the `PATH` environment variable to add the extra path. This can be tricky, as the `PATH` environment variable can only be a certain size on Windows, and also has the lowest priority in search behavior.

I chose the first work-around and would like to share it with you, maybe it's food for thought to add to the Wiki:
```cs
[DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
[return: MarshalAs(UnmanagedType.Bool)]
private static extern bool SetDefaultDllDirectories(int directoryFlags);

[DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
private static extern void AddDllDirectory(string lpPathName);

private const int LOAD_LIBRARY_SEARCH_DEFAULT_DIRS = 0x00001000;

//...

SetDefaultDllDirectories(LOAD_LIBRARY_SEARCH_DEFAULT_DIRS);

AddDllDirectory(Path.Combine(
    AppDomain.CurrentDomain.BaseDirectory,
    Environment.Is64BitProcess ? "x64" : "x86"
));
```

**Comment by LennardF1989** [comment]
From my search, I found the Intel GPA seems to do this. Besides that, given even Intel made this mistake, other (badly written) hooks might do the same thing. And since hooking things is kind of a big thing in games (overlays and what not), `AddDllDirectory` is the safest choice in any case.

**Comment by LennardF1989** [comment]
I had a few users struck by this issue test the `AddDllDirectory`-method, and they all reported it resolved their issue.

**Comment by flibitijibibo** [comment]
Do you know if the SetDefault call is necessary for this to work? I dunno if the CLR does the right `LoadLibraryEx` but it'd be nice to rip that out if we can.

**Comment by LennardF1989** [comment]
Just a quick update on this. I've since learned that most games running on FNA still work fine for Windows XP and Vista, even though I don't support this platform. Regardless, my proposed fix here breaks that compatibility. 

Windows 7 needs a particular update for it to work, by the way. KB2533623 to be specific.

This is easily resolved by combining both techniques, which hardens you against poorly written software hooks, but still supports as much systems as possible! Put a Try-catch around `AddDllDirectory`, and if it fails with a `EntryNotFoundException`, fallback to the `SetDllDirectory` method.

You might want to add this bit to the wiki as well.

**Comment by flibitijibibo** [comment]
Is there a way to do this without the try/catch? My concern is that the entry point should be checked and verified explicitly, so maybe we should be checking against the NT version or something along those lines before attempting to go into any of these functions.

**Comment by LennardF1989** [comment]
Technically, you could do the LoadLibrary + GetProcAddress way. Then you know for sure an entrypoint exists or not. But it becomes rather nasty if you ask me. Another way would be to check the OSVersion, but that means you would have to dump Windows 7 and lower into the SetDllDirectory spectrum, since you can't tell without further Windows-specific digging if one has the KB-update installed.

The most clean way is probably the Try-Catch method. I'd say given current demographics that play computer games, machines that don't support the AddDllDirectory call are outnumbered, so in most cases, it succeeds without any further problems.

Are there any particular reasons why you would like a no-try-catch approach? Aside from preventing a trial-and-error solution.

**Comment by flibitijibibo** [comment]
My main concern is that the whole root of the problem comes from malicious programs inserting themselves into our processes, so I can't be 100% sure that this isn't inviting them to do something bad behind our backs in a way that we can't detect. It would not surprise me at all if we came back to this issue some months later with some other weird Exception (or worse, a silently caught exception) resulting from some crappy program that isn't acting responsibly. If we do it _exactly_ correct in a way that is as precise as humanly possible it gives us significantly more leverage to pin those programs as malicious in a way that customers understand, and hopefully it will get customers to stop using those programs and force bad actors to start doing the right thing and stop breaking other people's stuff.

**Comment by LennardF1989** [comment]
Makes sense, didn't think of it that way. In that case, I'd say a Windows version check would do just that, as SetDllDirectory is pretty much always available. In case of modern systems, we can switch to the proper AddDllDirectory. 

This would mean that if people crash on startup because DLL's could not be found they most likely have a program doing weird stuff to our process. They can then either fix it by disabling that program, or by moving DLL's around themselves. On top of that: the issue would be limited to Windows 7 and lower only.

**Comment by flibitijibibo** [comment]
For now I have both paths listed on the wiki, but once you have a safer version written up I can update it one more time, and document the reason for all the busy work at the same time.
