### ISSUE TITLE
[Inquiry] Strange NullPointerExceptions

### ISSUE THREAD

**Issue by LennardF1989** [FNA-XNA/FNA#163]
I'm investigating a bunch of NullPointerExceptions from my crashlog server. Most of them are my fault, but some happen deep inside FNA, most notable the `OnApply` of `BasicEffect`.

From what I gather, it happens on two particular lines:
```
dirtyFlags = EffectHelpers.SetWorldViewProjAndFog(dirtyFlags, ref world, ref view, ref projection, ref worldView, fogEnabled, fogStart, fogEnd, worldViewProjParam, fogVectorParam);

...

bool newOneLight = !light1.Enabled && !light2.Enabled;
```

Out of nowhere, `worldViewProjParam` becomes null for some people (crashing `EffectHelpers`). On the other line, `light1` and `light2` might be null.

All of them triggered at random while doing the following higher-up:
```
foreach (EffectPass pass in effect.CurrentTechnique.Passes) {
    pass.Apply();
}
```

Would you know of any reason why and how this can happen? I for the world cannot replicate it. Maybe a device-reset which invalidates the effect? I would however expect things to crash way before it even reaches `OnApply` if the effect gets invalidated (like, when actually enumerating over `effect.CurrentTechnique.Passes` itself).

EDIT: I also have multiple cases where disposing the game (because `Run` ends in a using-block) during a close-down, causes a `Spritebatch` to fail disposing because its effect is null (`spriteEffect.Dispose();` to be specific). Maybe it's a similar issue... Something is going on with effects.

**Comment by flibitijibibo** [comment]
As long as we're using the latest version everything should be okay. We don't lose GL data on device resets so when the effect is valid on start, nothing should modify the parameters in any way (in fact, all of that data is entirely decoupled from the graphics subsystem, it's really just C memory that eventually gets memcpy'd to a constant buffer within MojoShader).

Do you have any information about their system? Graphics information should be coming out of FNALoggerEXT, if you want to hook that to your engine's logging system. It could be that their system doesn't actually support the data and it's never gathering the parameters in the first place.

**Comment by LennardF1989** [comment]
Just an update, I rolled out a new update with the latest and greatest FNA. Eagerly keeping an eye on my crashlog server to see what happens. Will report back.

**Comment by LennardF1989** [comment]
Not really related, but doesn't warrant a new issue IMO, but upon investigating I noticed a pattern on Macs: In some cases (but still pretty frequently actually), it can happen `Draw` is called before `Update` on startup. 

This causes a NullPointerException, because the `Draw` is dependent on the fact `Update` has run at least once.

This is kind of weird, because the logic of `Tick` is setup in such a way, it can never get to `Draw`, before `Update` has run at least once, or I'm missing something...

**Comment by flibitijibibo** [comment]
If what you say is true, then stepCount will be 0 on that first Tick after the loop below this line:

https://github.com/FNA-XNA/FNA/blob/master/src/Game.cs#L475

Additionally, calling SuppressDraw() on startup would fix this, if it really does happen.

**Comment by LennardF1989** [comment]
But its feasibly impossible to be, because it can never get to that point, if an earlier condition hasn't been satisfied. I also looked into a few FIXME's and noticed one mentioning `LoadContent` might never be called, but if I make that happen, I do not get the same exception, except when again `Draw` runs before `Update`. I did exactly what you said, and make sure SuppressDraw is called on startup, curious what happens once I deploy this.

On a side note related to this topic. After updating to the latest FNA, the only thing I'm still getting crashes on, is when it tries to `Dispose` a Spritebatch when the game is being killed.

**Comment by flibitijibibo** [comment]
It may also be an expose event - is it RedrawWindow doing this? The stack will tell you if that’s the case.

**Comment by LennardF1989** [comment]
I jumped back to stacktraces of a previous version, since I wiped out all the current ones as I went to fix them, and indeed, it comes from `RedrawWindow` when `SDL_WINDOWEVENT_EXPOSED` occurs!

Could it be related that during Initialize/LoadContent, I set my screen to fullscreen, and that in some cases, this cases `SDL_WINDOWEVENT_EXPOSED` to be fired before the actual first frame officially happened?

**Comment by flibitijibibo** [comment]
That sounds pretty reasonable, yeah. Note that this is possible in XNA as well if you're really good at timing things, so your best fix would be this:

- Initialize all your Draw-dependent resources at LoadContent
- Try to set window size/state before Game.Initialize(), to prevent weird resizing and 1-frame display flickering

Get those two and this shouldn't happen anymore, and it'll look nicer too!

**Comment by flibitijibibo** [comment]
Sounds like we at least diagnosed this as a client thing, so will close this... you can keep using the thread if you want.

**Comment by LennardF1989** [comment]
No problem :) I digged up another user who had the disposing thing. I have been staring at the FNA code, trying to reproduce it, but I'm completely baffled.

```
System.NullReferenceException: Object reference not set to an instance of an object.
    at Microsoft.Xna.Framework.Graphics.SpriteBatch.Dispose(Boolean disposing) in E:\Projecten\MyGame\Lib\FNA\src\Graphics\SpriteBatch.cs:line 180
    at Microsoft.Xna.Framework.Graphics.GraphicsResource.Dispose() in E:\Projecten\MyGame\Lib\FNA\src\Graphics\GraphicsResource.cs:line 106
    at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Dispose(Boolean disposing) in E:\Projecten\MyGame\Lib\FNA\src\Graphics\GraphicsDevice.cs:line 496
    at Microsoft.Xna.Framework.GraphicsDeviceManager.Dispose(Boolean disposing) in E:\Projecten\MyGame\Lib\FNA\src\GraphicsDeviceManager.cs:line 198
    at Microsoft.Xna.Framework.GraphicsDeviceManager.System.IDisposable.Dispose() in E:\Projecten\MyGame\Lib\FNA\src\GraphicsDeviceManager.cs:line 212
    at Microsoft.Xna.Framework.Game.Dispose(Boolean disposing) in E:\Projecten\MyGame\Lib\FNA\src\Game.cs:line 334
    at Microsoft.Xna.Framework.Game.Dispose() in E:\Projecten\MyGame\Lib\FNA\src\Game.cs:line 302
    at Amorous.Game.Windows.Program.Main(String[] ) in E:\Projecten\MyGame\Src\MyGame.Windows\Program.cs:line 82
```

The effect at that line is supposedly null, but it could technically never be, because the effect is made as part of the constructor. So if the constructor fails prematurely, there would at least be an exception, but nothing... This process is triggered due to the using-block in `Program.cs`. Already tried throwing some random exceptions, to see if Dispose is called, even when things go awry, but it doesn't. It jumps right into my catch-all exception block and handles it gracefully.

**Comment by flibitijibibo** [comment]
May just have to printf spam - line after effect is assigned, one before effect is disposed. Disposing is always clunky on crashes so it’s hard to say.
