### ISSUE TITLE
community platform?

### ISSUE THREAD

**Issue by frostworx** [FNA-XNA/FNA#17]
hi, sorry if this is the wrong place to ask, but I have no clue whereelse I should ask.
I wonder if there's some active FNA community (f.e. irc or some forum) where
people could help each other with their porting problems.
f.e some weeks ago I tried to make a 4.0->FNA port of the older xna3.0 aba game "Mazer Mayhem".
the binary starts, but I must have messed up the shader conversion :)
if that worked it would rock as well to also port his "GearToyGear".
I also gave the xna4.0 port ( https://github.com/Pepsi1x1/XNA-4-Racing-Game-Kit ) of the MS XnaRacingGame a try this weekend. only some minor changes in the code. no idea if it is even possible to build the whole content stuff under linux, so I setup a win7vm to build it there. the FNA linux binary complained about some incompatible xact compression so I rebuilt it without compression. tried with prebuilt mojoshader and mojoshader from git, but the binary segfaults before opening a screen. Am I right that gdb doesn't see xna code?

some community efford to get XNALara working would be nice as well.
Gave it an ugly try and gave the resulting binary the System.Windows.Forms.dll and Accessibility.dll
of my mono install. for whatever reason ;) it didn't work.
I'm sorry if this totally misplaced here and understand if you close the issue.
thank you for your great work!

**Comment by flibitijibibo** [comment]
There is no forum for FNA development at this time, since the discussions would mostly amount to issues that should be reported here anyway.

My recommendation is to get it working on Windows with XNA4, then build that against FNA. At the same time, you can get rid of System.Windows.Forms with friends as is recommended by the FNA documentation:

https://github.com/FNA-XNA/FNA/wiki/4:-FNA-and-Windows-API

Hope this helps get some of those projects booting.

**Comment by frostworx** [comment]
thank you for the quick reply!
I've seem your wiki, but XNALara is full of Windows.Forms and I doubt I can replace all the code myself. I do not even know the windows program, it just looked like nicetohave :}
I'll give the two aba games another try when I find the time, and play a bit longer with this racing code, but not on windows :}
