### ISSUE TITLE
failure in the running

### ISSUE THREAD

**Issue by EdwinGtz** [FNA-XNA/FNA#175]
hi im new using FNA i include FNA in my new project when i compile i have an error
"ARB_debug_output found an error". 
this is the log from console
```
IGLDevice: OpenGLDevice
OpenGL Device: Intel(R) HD Graphics 530
OpenGL Driver: 4.5.0 - Build 24.20.100.6025
OpenGL Vendor: Intel
GREMEDY_string_marker not supported!
MojoShader Profile: glsl120
EXT_swap_control_tear unsupported. Fall back to standard VSync.
API_ID_REDUNDANT_FBO performance warning has been generated. Redundant state change in glBindFramebuffer API call, FBO 0, "", already bound.
        Source: GL_DEBUG_SOURCE_API_ARB
        Type: GL_DEBUG_TYPE_PERFORMANCE_ARB
        Severity: GL_DEBUG_SEVERITY_LOW_ARB
API_ID_REDUNDANT_FBO performance warning has been generated. Redundant state change in glBindFramebuffer API call, FBO 0, "", already bound.
        Source: GL_DEBUG_SOURCE_API_ARB
        Type: GL_DEBUG_TYPE_PERFORMANCE_ARB
        Severity: GL_DEBUG_SEVERITY_LOW_ARB
Error has been generated. GL error GL_INVALID_ENUM in MatrixMode: (ID: 2659017226) Generic error
        Source: GL_DEBUG_SOURCE_API_ARB
        Type: GL_DEBUG_TYPE_ERROR_ARB
        Severity: GL_DEBUG_SEVERITY_HIGH_ARB

```
**this error stop my running**
Error has been generated. GL error GL_INVALID_ENUM in MatrixMode: (ID: 2659017226) Generic error
        Source: GL_DEBUG_SOURCE_API_ARB
        Type: GL_DEBUG_TYPE_ERROR_ARB
        Severity: GL_DEBUG_SEVERITY_HIGH_ARB
Version FNA 18.05

#23 
i seen in the 2016 a post with one solution i tried that solution but without success the error persisting

**Comment by michaelarts** [comment]
Hey @flibitijibibo, Edwin was trying to use my FNA tutorial series and ran into this issue when building a blank FNA project. I don't know enough about FNA to understand what the issue is... but my suspicion is that there's some type of incompatibility with his hardware.

This person had a similar issue error message: https://forums.amorousgame.com/threads/error-wont-let-me-open-the-game-after-downloading.1923/

@EdwinGtz, similar to the person in that thread, could you please go to Run -> dxdiag and then post the specs of your graphics card? That may shed some light on the situation if I'm correct.

**Comment by EdwinGtz** [comment]
ok @michaelarts i see in the code FNA after add the project and when im debuging i see this in the class OpenGLDevice_GL.cs, in the function LoadGLEntryPoints, var baseErrorString: "OpenGL 2.1 support is required!", maybe that is the problem
Display Devices
---------------
        Card name: Intel(R) HD Graphics 530
        Manufacturer: Intel Corporation
        Chip type: Intel(R) HD Graphics Family
        DAC type: Internal
        Device Type: Full Device
      Display Memory: 4165 MB
      Dedicated Memory: 128 MB
      Shared Memory: 4037 MB
      Current Mode: 1280 x 720 (32 bit) (60Hz)
      HDR Support: Not Supported
      D3D9 Overlay: Supported
      DXVA-HD: Supported
      DDraw Status: Enabled
      D3D Status: Enabled
      AGP Status: Enabled

**Comment by michaelarts** [comment]
Yeah, unfortunately I think that's the issue. Maybe try updating your drivers? I'm not sure that's going to fix the issue though.

**Comment by flibitijibibo** [comment]
We don’t call MatrixMode at all, which means you have some kind of streaming-related overlay breaking your code (XSplit or some other malware), be sure to uninstall that before working with FNA. OBS and Steam are known to be compatible, all other overlays should be considered malware unless specificied otherwise.

**Comment by EdwinGtz** [comment]
Thank you @michaelarts,@flibitijibibo, @michaelart i updated the drivers from intel, persisting the error @flibitijibibo how i can see that because i have OBS and Steam but i dont know what is incompatible my pc is new i have 1 month with the pc

**Comment by flibitijibibo** [comment]
Without having the PC in my hands I can’t say what’s installed, but something is definitely interfering with your game windows. Look for anything that might try to render anything inside a game window and uninstall it. OBS and Steam won’t interfere without your permission and both should emit proper GL calls, whatever is installed on that PC is doing the opposite of both those things.

I can say definitively that this isn’t an FNA bug but feel free to keep using this thread.

**Comment by EdwinGtz** [comment]
the people who question how i can fix this error,process with interference with FNA,  uninstall all programs for don't do coding like  Overwolf,tools for  gaming, if this dont work and the error persist do a backup and restore the sistem on the first use, thank you for the support
