### ISSUE TITLE
Compatibility with Facepunch.Steamworks

### ISSUE THREAD

**Issue by BurgerBob** [FNA-XNA/FNA#180]
I'm not sure if the problem is related to FNA or Facepunch.Steamworks, so I am going to post this issue on both forums.

When I create a simple project with both FNA and Facepunch.Steamworks, I get 2 bugs:

Managed Debugging Assistant 'PInvokeStackImbalance' : 'A call to PInvoke function 'Facepunch.Steamworks!SteamNative.Platform+Win32+Native::SteamInternal_CreateInterface' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.'

And if I ignore these exceptions, I got another bug :

System.InvalidOperationException: 'Error has been generated. GL error GL_INVALID_ENUM in MatrixMode: (ID: 2659017226) Generic error
	Source: GL_DEBUG_SOURCE_API_ARB
	Type: GL_DEBUG_TYPE_ERROR_ARB
	Severity: GL_DEBUG_SEVERITY_HIGH_ARB'

It does not occur instantaneously, so my guess is it occurs when Steam tries to draw its overlay.

I attached a project with the bug.
Just copy all the files at the root to the output directory for it to work.
Also, you must have Steam running to have the bug.
[FNA Steamworks Test.zip](https://github.com/FNA-XNA/FNA/files/2091057/FNA.Steamworks.Test.zip)

**Comment by flibitijibibo** [comment]
The first bug is a Facepunch issue, it means their CallingConvention is wrong. My guess is they export it as a C function and they don't have `CallingConvention = CallingConvention.Cdecl` in their DllImport attribute.

The second bug is somebody (not us) trying to call glMatrixMode, which is an overlay bug and not an FNA issue. File that report with Valve if you think it's them, but I think their GL call stream is clean. Have some other capture software running? You can disable the ARB_debug_output stuff if you want, but if someone's throwing bad GL functions against our will then you're probably going to get a black screen...

**Comment by BurgerBob** [comment]
Thanks a lot.
I commented the line that threw the exception and it now works.

I'll tell the Facepunch guys the Managed Debugging Assistant bug, but the game runs anyway if you disable the exception breakpoint.

Thanks again.
