### ISSUE TITLE
FNA doesn't detect Nintendo Switch Joycons

### ISSUE THREAD

**Issue by sherjilozair** [FNA-XNA/FNA#188]
Hello again,

Seems like FNA doesn't detect Switch Joycons on Desktop (Not Switch). SDL2 does detect the joycons as joysticks. Any idea how to do the same for FNA?

**Comment by sherjilozair** [comment]
I've managed to access the joystick using SDL2 within the FNA project, so I guess that works for now. Is there something special about the joycons which make them only accessible as a joystick and not a gamepad? How do games for the Switch handle the joycons? As SDL joysticks?

**Comment by flibitijibibo** [comment]
https://github.com/gabomdq/SDL_GameControllerDB/blob/master/README.md#create-new-mappings

**Comment by flibitijibibo** [comment]
Technically a GameControllerDB issue, so closing this...
