### ISSUE TITLE
Black texture after 1 tick

### ISSUE THREAD

**Issue by Pack4Duck** [FNA-XNA/FNA#189]
I can se for a moment the yellow rectangle, next frame become black. 
This is the code: https://pastebin.com/CkK13RcD
FNA compiled netstandard 2.0 x64.

**Comment by Pack4Duck** [comment]
When i can sit on my pc i'll trt.
I tried also to get pixels[] from an assets file with a fixed width and height.

_texture = new Texture(device, width, height);
_texture.SetData(data);

Spritebatch.Draw(_texture, new Vector2(50,40), Color.Red);

Same results: game starts, shows for a tick texture red, then it become black.

I tried also a monogame fresh proj x64 and it works with same code of my first post.

Im running fna game class with a netcore 2.1 project x64.

**Comment by flibitijibibo** [comment]
Can't reproduce locally, run on Windows, macOS, Linux with .NET 4.0 and Mono 5.x, NVIDIA/Intel graphics both tested:

```
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

class Program : Game
{
	static void Main(string[] args)
	{
		using (Program p = new Program())
		{
			p.Run();
		}
	}

	Program() : base()
	{
		new GraphicsDeviceManager(this);
	}

	Texture2D tex;
	SpriteBatch batch;

	protected override void LoadContent()
	{
		batch = new SpriteBatch(GraphicsDevice);
		tex = new Texture2D(GraphicsDevice, 1, 1);
		tex.SetData(new Color[] { Color.Red });
	}

	protected override void UnloadContent()
	{
		batch.Dispose();
		tex.Dispose();
	}

	protected override void Draw(GameTime gameTime)
	{
		GraphicsDevice.Clear(Color.Black);
		batch.Begin();
		batch.Draw(tex, new Rectangle(50, 50, 150, 150), Color.Yellow);
		batch.End();
	}
}
```

**Comment by Pack4Duck** [comment]
Same things with texture 4x4 and same things with your example in a fresh project.
Tried with .net framework 4.5 and 4.7.1 for ex project and 4.0 for FNA. Both with Any/64/86 arch.
I've also installed mono x86/x64 as last stand.

Im on Windows 10, gtx 1080.

Nothing change.

**Comment by flibitijibibo** [comment]
Thanks RivaTuner...
