### ISSUE TITLE
Fullscreen not resizing display properly

### ISSUE THREAD

**Issue by Myuujinn** [FNA-XNA/FNA#192]
Hey there!

So I'm developing my game and made the switch from MonoGame to FNA (yay) and everything is working perfectly (super yay). Only problem is my fullscreen setting.

So my GameWindow is 1600x900 and my desktop is 1920x1080, FNA will not change my desktop resolution and stay on 1920x1080 and my game will display on the top left of the display with the "Cornflower Blue" color from my graphics clear routine filling the rest of the window.
This behaviour does not happen with MonoGame with the same code.

I don't think I'm setting the fullscreen badly but take a look :
`
public void SetFullScreen(bool isFullScreen)
        {
            graphicsDeviceManager.IsFullScreen = isFullScreen;
            graphicsDeviceManager.ApplyChanges();
        }
`

The GameWindow resolution is set previously using graphicsDeviceManager.PreferredBackBufferWidth and graphicsDeviceManager.PreferredBackBufferHeight.

However, if I set it in fullscreen the first time that the window is created, the behaviour will be normal and my screen resolution will be adjusted as required.
Pretty weird I know.

Thanks for your time ! :)

**Comment by flibitijibibo** [comment]
Can I see the whole Draw routine? It sounds like your program is depending on GameWindow.ClientBounds, which is going to be different from your backbuffer size (GraphicsDevice.PresentationParameters).

**Comment by Myuujinn** [comment]
In order to have cheap resolution independance, I use a RenderTarget2D which is 1920x1080 which I downscale to the desired resolution. Which we will ignore because it doesn't really matter.
My drawing routine for displaying that RenderTarget2D to the window though is as follows :
```c#
public void DrawScreen()
        {
            GraphicsDevice.Clear(Color.CornflowerBlue);
            SpriteBatch.Begin(SpriteSortMode.BackToFront, BlendState.AlphaBlend, null, DepthStencilState.Default, null, null);
            SpriteBatch.Draw(renderTarget, new Rectangle(0, 0, graphicsDeviceManager.PreferredBackBufferWidth, graphicsDeviceManager.PreferredBackBufferHeight),
                null, Color.White, 0f, Vector2.Zero, SpriteEffects.None, 1f);
            cursor.Draw(SpriteBatch);
            fpsCounter.Draw(this);
            SpriteBatch.End();
        }
```

I definitely draw it and resize it according to the backbuffer size but maybe FNA is different from MonoGame on that regard?

**Comment by flibitijibibo** [comment]
What happens when you replace the destination rectangle with `GraphicsDevice.PresentationParameters.Bounds`?

**Comment by Myuujinn** [comment]
The window is now perfectly fullscreen only it's 1080p and not the desired resolution.

**Comment by flibitijibibo** [comment]
It sounds like you have a really hard dependency on the window resolution while at the same time have a hardcoded resolution size. The latter isn't that bad if you're scaling, but note that the GraphicsDevice resolution is independent from the window size, and depending on your platform the window size may vary from the backbuffer size. In the case of desktop targets, we set fullscreen windows to the size of the desktop for safety; the list of reasons is REALLY long but just know that's how it works. As an example of different behavior, on Xbox the resolution is always the console's active resolution, which we don't have any control of. This is essentially the equivalent of how XNA/XBLIG worked; the GameWindow behavior is pretty much undefined while the backbuffer is something you should have total control of.

So let's try this:

```
/* Setting the backbuffer size */
DisplayMode desktop = GraphicsAdapter.DefaultAdapter.CurrentDisplayMode;
graphicsDeviceManager.PreferredBackBufferWidth = desktop.Width;
graphicsDeviceManager.PreferredBackBufferHeight = desktop.Height;
graphicsDeviceManager.IsFullScreen = true;
graphicsDeviceManager.ApplyChanges();

/* Get these after ApplyChanges. Maybe OnDeviceReset? */
Vector2 displayMiddle = new Vector2(
    GraphicsDevice.PresentationParameters.BackBufferWidth / 2,
    GraphicsDevice.PresentationParameters.BackBufferHeight / 2
);
float displayAspect = (
    (float) GraphicsDevice.PresentationParameters.BackBufferWidth /
    (float) GraphicsDevice.PresentationParameters.BackBufferHeight
);
Vector2 gameMiddle = new Vector2(1920 / 2, 1080 / 2);
float gameAspect = 1920.0f / 1080.0f;
float targetScale;
if (displayAspect > gameAspect) /* Screen is wider */
{
    targetScale = (float) GraphicsDevice.PresentationParameters.BackBufferHeight / (float) 1080.0f;
}
else /* Screen either matches aspect or is taller */
{
    targetScale = (float) GraphicsDevice.PresentationParameters.BackBufferWidth / 1920.0f;
}
```

```
/* Draw the target (maybe clear to Black instead of Blue) */
spriteBatch.Draw(
    renderTarget,
    displayMiddle,
    null,
    Color.White,
    0.0f,
    gameMiddle,
    targetScale,
    SpriteEffects.None,
    0.0f
);
```

With all this you'll keep your 1080p target while also being aware of your screen size, allowing you to do aspect ratio preservation if needed (not every player is going to have a the native display res you want).

**Comment by Myuujinn** [comment]
First of all, thank you so much for the help and reactivity.

If I understand that correctly, fullscreen resolution on FNA is always going to be the GraphicsAdapter's resolution on desktop or console. And if that so, isn't it weird that the display resolution is changed if I set it to fullscreen before I create the window and not after? If FNA should/is always be using fullscreen resolution from the adapter, then it shouldn't be intended behaviour.

The code snippet you provided works well on fullscreen resolutions, thanks again !

**Comment by flibitijibibo** [comment]
I would need an isolated test case to verify that. I don't know how inaccurate MG is here, but it sounds like a variable that shouldn't be set by their framework is getting set, while FNA doesn't touch it, and when a toggle occurs it leaves those parts alone and the game ends up, in reality, setting a 1080p res while the _preferred_ variables are the viewport size. The nasty thing about the preferred options in GraphicsDeviceManager is that they can get out of sync if you're not careful (definite emphasis on _preferred_).

**Comment by Myuujinn** [comment]
I have created a test case in which it appears : (https://github.com/Myuujinn/TestCaseGame).

The window will be fullscreen at the start and will change the resolution of the desktop (on Windows 10 at least).
Just press F to change between fullscreen and windowed. When you go back to fullscreen after being windowed, FNA will force 1080p as you said. But not when the window is created.

**Comment by flibitijibibo** [comment]
Tried this out and it seems Windows 10 is not terribly bright about window events! The best way to explain is via SDL's resize events:

https://wiki.libsdl.org/SDL_WindowEventID

The two we care about are `SDL_WINDOWEVENT_SIZE_CHANGED` and `SDL_WINDOWEVENT_RESIZED`. How it's _supposed_ to work is we set the window size ourselves, we get a `SIZE_CHANGED` event, and that's it. _User_ resizes, on the other hand, will send a `RESIZED` right after. What 10 is doing is sending a `RESIZED` event even for fullscreen changes, which is NOT how it works elsewhere. This causes GameWindow.ClientSizeChanged to fire, which GraphicsDeviceManager interprets as a user resize, causing the backbuffer to jump to the desktop res, hence our desync. I wonder if XNA has this problem too!

Here's a test SDL2.dll, can you give this a try with the same test?

http://www.flibitijibibo.com/win10blows.zip

**Comment by flibitijibibo** [comment]
It's a bit strange because AFAIK this works everywhere else, and in trying a handful of things with SDL I'm finding that 10 is being EXTREMELY aggressive with its resize events, bordering on psychotic. No matter how aggressively I enforce our width/height values, Windows just sends 5+ resize events all at once, and every attempt to interact with the window in any way whatsoever just fires more and more events until it finally tricks the application into accepting a resize and tripping this problem. Even on Linux with X11 this is not something we fight as much... I have no idea what Windows wants.

I brought back an old behavior that was originally just for stuff like alt-tabbing, but I guess it's needed for window managers being grossly irresponsible with events as well:

https://github.com/FNA-XNA/FNA/commit/5c5da6df91da15c7b434c61a7c4dd4c830add6db

Resizes for non-resizables are _supposed_ to be rare and with legitimate reasons, but I guess not in reality!

This should resolve this issue, but I'll have to go document this for certain targets that depended on it...

**Comment by flibitijibibo** [comment]
SDL bug filed with a patch:

https://bugzilla.libsdl.org/show_bug.cgi?id=4227

After this is resolved I should be able to fix this in FNA for realsies.

**Comment by flibitijibibo** [comment]
The patch went into SDL revision control just now:

https://hg.libsdl.org/SDL/rev/754cd2042e21

This should fix the most obvious resize issues, though I'll need to hammer this out for every backend, because who knows what each OS is doing with the window... wouldn't surprise me if X11 misbehaved somehow. But, if you want to play dangerous, the resizable check can be removed and you can give it a try wherever you're testing now.
