### ISSUE TITLE
Using SDL event loop w/ FNA

### ISSUE THREAD

**Issue by danielcrenna** [FNA-XNA/FNA#193]
I've added drag and drop support in my Update loop using SDL2. 

Something like this:

```csharp
while (SDL.SDL_PollEvent(out var evt) == 1)
{
	if (evt.type == SDL.SDL_EventType.SDL_DROPFILE)
	{
		var filename = SDL.UTF8_ToManaged(evt.drop.file, true);
		// Do stuff with filename
	}
}
```

However, I get frequent "misses" on the event. 

I'm guessing that could be because `SDL2_FNAPlatform` is also polling the event loop. There are a couple of things I don't like about what I'm doing.

1. Possibly colliding with FNA's use of the events (consumed before I get to them?)
2. Having to link my own instance of SDL2 into code (because `SDL.UTF8_ToManaged` is `internal`)

It would be ideal if FNA would let me register my own delegates in `SDL_FNAPlatform`, but I didn't see an obvious way to do that that wouldn't break the XNA design or add an ugly interface check.

Is there a "blessed" path to implementing things like this w/ FNA?

**Comment by flibitijibibo** [comment]
I think I answered this... you can keep using this thread if there’s anything I missed.
