### ISSUE TITLE
cmake mojoshader parse error

### ISSUE THREAD

**Issue by DanielsWrath** [FNA-XNA/FNA#195]
When I try to build mojoshader as described for the XBOX UWP, it gives an error:
```
Parse error in command line argument: -DMOJOSHADER_NO_VERSION_INCLUDE
Should be: VAR:type=value
CMake Error: No cmake script provided.
CMake Error: Problem processing arguments. Aborting.
```
Without `-DMOJOSHADER_NO_VERSION_INCLUDE`, it works fine. So I guess that either that command has to be dropped or changed in order for it to work. 

edit: Also, when it does run without said command arg, it returns the warning 
```
CMake Warning:
  Manually-specified variables were not used by the project:

    XNA4_VERTEXTEXURE
```

**Comment by flibitijibibo** [comment]
We’re trying to make that first part optional, just waiting for Ryan to review the CMake patch.

Also it’ll be TEXTURE not TEXURE. Will update the docs accordingly.
