### ISSUE TITLE
System.BadImageFormatException running UWP FNA

### ISSUE THREAD

**Issue by DanielsWrath** [FNA-XNA/FNA#196]
I am using [a very simple FNA template](https://github.com/DanielsWrath/FNATemplate/tree/UWP) to test the new UWP feature. I have created all the DLL's as shown in the tutorial on the docs. However, when I run the game, it gives an System.BadImageFormatException in SDL2:
```
System.BadImageFormatException
  HResult=0x8007000B
  Message=An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
  Source=FNA
  StackTrace:
   at SDL2.SDL.INTERNAL_SDL_SetHint(Byte[] name, Byte[] value)
   at SDL2.SDL.SDL_SetHint(String name, String value) in C:\Users\danie\Documents\Staxel\FNAGame\FNA\lib\SDL2-CS\src\SDL2.cs:line 374
   at App.Program.Main(String[] args) in C:\Users\danie\Documents\Staxel\FNAGame\FNAGame\Program.cs:line 18

```

This happens at:
```
public static SDL_bool SDL_SetHint(string name, string value)
		{
			return INTERNAL_SDL_SetHint(
				UTF8_ToNative(name),
				UTF8_ToNative(value)
			);
		}
```

It seems like the generated SDL2.dll is not working somehow? I have tried to remove the `SetDllDirectory` code, but this was to no avail.

**Comment by flibitijibibo** [comment]
20 bucks says you mismatched 32/64-bit. Be sure you don’t have Prefer 32-bit enabled in your project settings.

**Comment by flibitijibibo** [comment]
Closing due to old age but I think I answered this - that HRESULT should mark an arch mismatch. You can verify this with corflags if needed:

https://docs.microsoft.com/en-us/dotnet/framework/tools/corflags-exe-corflags-conversion-tool
