### ISSUE TITLE
GetData error on Texture2D

### ISSUE THREAD

**Issue by Pack4Duck** [FNA-XNA/FNA#197]
Hi i'm trying to get 1 pixels from a texture to check with mouse position.

What i'm doing is:

A declared 
`ushort[] _data = new ushort[1];`

Then into my inherited Texture2D class:
```
int pos = (mouseY * Width) + mouseY;
GetData(_data, pos, 1); //ERROR
```

The error screen:
![image](https://user-images.githubusercontent.com/20810422/45561604-70894300-b848-11e8-8a4c-b99856f4ebe4.png)

**Comment by flibitijibibo** [comment]
Your GetData call is invalid; `startIndex`/`elementCount` refer to the array, not the texture subregion. For that you need to use `rect`:

```
// Declare this somewhere else, don't allocate every time
Rectangle rect;
rect.Width = 1;
rect.Height = 1;

// Proper GetData
rect.X = mouseX;
rect.Y = mouseY;
GetData(0, rect, _data, 0, 1);
```

**Comment by Pack4Duck** [comment]
Thanks :)

**Comment by Pack4Duck** [comment]
With your method app crashes with this error: 0xc0000374

**Comment by flibitijibibo** [comment]
It's valid on my system but I don't know what your image format is - should you be using byte instead of ushort?

**Comment by flibitijibibo** [comment]
I tried this on my machine and it was valid:

```
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

class Program : Game
{
	static void Main(string[] args)
	{
		using (Program p = new Program())
		{
			p.Run();
		}
	}

	Program() : base()
	{
		new GraphicsDeviceManager(this);
	}

	protected override void LoadContent()
	{
		Texture2D tex = new Texture2D(GraphicsDevice, 640, 480, false, SurfaceFormat.Bgra5551);
		ushort[] cunt = new ushort[1];
		tex.GetData(0, new Rectangle(240, 240, 1, 1), cunt, 0, 1);
		tex.Dispose();
	}
}
```

My best guess is your driver is converting BGR5_A1 into RGBA8 behind your back and doesn't like glGetTexImage requesting your original format. using Color[] may fix this.

**Comment by Pack4Duck** [comment]
yep with Color[1] doesn't crash, but works bad.
I think because color uses uint

**Comment by flibitijibibo** [comment]
Color is a byte4, so maybe they have problems with values smaller than that. If you use a uint and then dump the value unchecked to ushort that might do it. At the same time though, if you're only querying a single pixel at a time, it may be easier to keep the texture data in a ushort[] and query the array instead of querying the driver. That way your performance will be better (no driver serialization) and if the driver does in fact modify your image format, it only matter during presentation and not during queries.

**Comment by Pack4Duck** [comment]
Exactly. 
Atm i'm storing texture pixels in an ushort[width * height] and check it runtime.
Thanks for you help i appreciate it !
