### ISSUE TITLE
Playing sound effect crashes game when run with .NET Core

### ISSUE THREAD

**Issue by TheSpydog** [FNA-XNA/FNA#198]
I made a simple program (referencing the FNA.Core project) that plays a single sound effect:
```using System;
using System.IO;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Audio;

namespace core_fna_audio_test
{
    public class Game1 : Game
    {
        static void Main(string[] args)
        {
            using (Game1 game = new Game1())
            {
                game.Run();
            }
        }

        GraphicsDeviceManager graphics;
        public Game1()
        {
            graphics = new GraphicsDeviceManager(this);
        }

        override protected void LoadContent()
        {
            SoundEffect effect;
            using (Stream stream = TitleContainer.OpenStream("wahhh.wav"))
                effect = SoundEffect.FromStream(stream);
            effect.Play();
        }
    }
}
```
When I use `dotnet run` to build+run the app on macOS, it outputs the usual OpenGL and MojoShader information before crashing with the error:
```
Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'msvcrt' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libmsvcrt, 1): image not found
   at Microsoft.Xna.Framework.Audio.SoundEffectInstance.memset(IntPtr ptr, Int32 value, IntPtr num)
   at Microsoft.Xna.Framework.Audio.SoundEffectInstance.InitDSPSettings(UInt32 srcChannels) in /Users/calebcornett/Downloads/FNA/src/Audio/SoundEffectInstance.cs:line 442
   at Microsoft.Xna.Framework.Audio.SoundEffectInstance..ctor(SoundEffect parent) in /Users/calebcornett/Downloads/FNA/src/Audio/SoundEffectInstance.cs:line 185
   at Microsoft.Xna.Framework.Audio.SoundEffect.Play(Single volume, Single pitch, Single pan) in /Users/calebcornett/Downloads/FNA/src/Audio/SoundEffect.cs:line 296
   at Microsoft.Xna.Framework.Audio.SoundEffect.Play() in /Users/calebcornett/Downloads/FNA/src/Audio/SoundEffect.cs:line 291
   at core_fna_audio_test.Game1.LoadContent() in /Users/calebcornett/Projects/core_fna_audio_test/Game1.cs:line 29
```

However, if I run the output assembly with `mono` instead of `dotnet`, the game runs as expected. The sound plays with no crash.

I'm using the latest FNA from git and the latest fnalibs archive (Sep 11). Is this crash just a limitation with .NET Core or is something else going on?

**Comment by flibitijibibo** [comment]
This is a limitation with .NET Core, you need to file a report with them to fix compatibility with common CRT entry points. The tradition with .NET has always been to reference msvcrt and the runtime will map to the system's libc, which Core does not appear to do.

If you have the option, use Mono instead of CoreCLR. They're version 2.0+ but honestly it's not even close to finished yet, features like this are still missing to this day and minimum OS compatibility is pathetic.

**Comment by TheSpydog** [comment]
Ah, gotcha. If Core is that immature, what's the rationale behind having the FNA.Core project included at all? Is .NET Core required by some platform?

**Comment by flibitijibibo** [comment]
It's needed for Xbone. I believe Tizen uses it as well but they seem to have this fixed, as I haven't gotten any reports about this from those users.
