### ISSUE TITLE
Overloads for some methods?

### ISSUE THREAD

**Issue by bsimser** [FNA-XNA/FNA#200]
Just wondering if you would be okay with adding overloads to some of the core classes. Trying to port some old XNA code over and under MonoGame it works fine but under FNA calls to things like Rectangle.Contains that pass in a Vector2 or floats don't work. They're implemented in MonoGame and the original code used them so I assume they were there in XNA, just not in FNA. I can create a PR for the missing overloads but wanted to ask if that was a path you wanted to go down or if you didn't want to clutter up some of the core classes.

**Comment by flibitijibibo** [comment]
AFAIK we have the whole XNA ABI in place, so more than likely the application has an undocumented MonoGame dependency. If you want to overload in that way, this can work inside the program:

```
public static bool Contains(this Rectangle, Vector2 something)
{
   // ...
}
```

**Comment by flibitijibibo** [comment]
I think I answered this... MSDN for reference: https://docs.microsoft.com/en-us/previous-versions/windows/xna/bb447715(v%3dxnagamestudio.41)

**Comment by bsimser** [comment]
Agreed and thanks for the link (I was trying to find the original documentation).

**Comment by flibitijibibo** [comment]
For some bizarre reason Microsoft killed a huge percentage of the existing MSDN links, so XNA documentation is now really hard to find unless you know exactly where to look... not sure how/why that happened.

**Comment by bsimser** [comment]
Well we're talking about the guys that killed off XNA to begin with, so no surprise there.
