### ISSUE TITLE
Ubuntu 18.04 SDL2 not found error

### ISSUE THREAD

**Issue by Pack4Duck** [FNA-XNA/FNA#201]
Hi, i'm trying to run my game on ubuntu.
My game is compiled with netcore 2.1.

When i do: 'dotnet start' my game crashes with this error:
`SDL2 was not found! Do you have fnalibs?

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.Xna.Framework.FNAPlatform' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'SDL2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSDL2: cannot open shared object file: No such file or directory
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.ProgramInit()
   at Microsoft.Xna.Framework.FNAPlatform..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Xna.Framework.Game..ctor()
   at ClassicUO.CoreGame..ctor() in /home/andrea/ClassicUO-dev/CoreGame.cs:line 38
   at ClassicUO.GameLoop..ctor() in /home/andrea/ClassicUO-dev/GameLoop.cs:line 52
   at ClassicUO.MainClass.Main(String[] args) in /home/andrea/ClassicUO-dev/MainClass.cs:line 58
`

Into the output folder i've all libs (FNA.dll, FNA.config and libs downloaded from your wiki page).
Game is x64, so i'm using libs into "libs64" folder.

UPDATE 1:
If i change the linux libs name from:

"libSDL2-2.0.so.0" to "SDL2.so" ( and for each libs like that).

It works. :|
I think it's very strange. 
I followed this post: https://github.com/FNA-XNA/FNA/issues/145
Maybe im missing some setup?

**Comment by flibitijibibo** [comment]
.NET Core is really bad and does not implement dllmap, so your workaround is the correct answer for now. Try to use Mono instead if you can help it.
