### ISSUE TITLE
How to make FNA windows not respect windows element scaling settings

### ISSUE THREAD

**Issue by Blecki** [FNA-XNA/FNA#202]
Simple issue. Windows element scaling is set at 200%. Set a resolution of 800x600 and the actual window is 1600x1200 with all pixels double-sized. XNA does not exhibit this behavior but FNA does.

**Comment by flibitijibibo** [comment]
Windows programs have to specify DPI awareness on 8+:

https://msdn.microsoft.com/en-us/C9488338-D863-45DF-B5CB-7ED9B869A5E2

**Comment by flibitijibibo** [comment]
I think I answered this... if you want to be more thorough this is actually an SDL issue anyhow:

https://bugzilla.libsdl.org/show_bug.cgi?id=3433
https://bugzilla.libsdl.org/show_bug.cgi?id=3281
