### ISSUE TITLE
FNA not working with .Net CoreRT

### ISSUE THREAD

**Issue by BurgerBob** [FNA-XNA/FNA#203]
Hello,

I managed to build my FNA game with the AOT compiler CoreRT, but there is a problem with Marshal.GetDelegateForFunctionPointer. I modified FNA a bit to get this error message :

>Unhandled Exception: Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException: GRAPHICS DRIVER IS EXTREMELY BROKEN!
Microsoft.Xna.Framework.Graphics.OpenGLDevice+GetString is missing delegate marshalling data. To enable delegate marshalling data, add a MarshalDelegate directive to the application rd.xml file. For more information, please visit http://go.microsoft.com/fwlink/?LinkID=393965
   at Microsoft.Xna.Framework.Graphics.OpenGLDevice.LoadGLGetString() + 0xd1
   at Microsoft.Xna.Framework.Graphics.OpenGLDevice..ctor(PresentationParameters, GraphicsAdapter) + 0x2f3
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.CreateGLDevice(PresentationParameters, GraphicsAdapter) + 0x62
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter, GraphicsProfile, PresentationParameters) + 0x15c
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Microsoft.Xna.Framework.IGraphicsDeviceManager.CreateDevice() + 0xda
   at Microsoft.Xna.Framework.GraphicsDeviceManager.get_GraphicsDevice() + 0x16
   at Microsoft.Xna.Framework.Game.InitializeGraphicsService() + 0x68
   at Microsoft.Xna.Framework.Game.DoInitialize() + 0x19
   at Microsoft.Xna.Framework.Game.Run() + 0x1e
   at FNA CoreRT Test!<BaseAddress>+0x1bd266

So I added this rd.xml to the project :

`<Directives>  
   <Application>  
        <Assembly Name="FNA" MarshalDelegate="Required All">
          <Type Name="Microsoft.Xna.Framework.Graphics.OpenGLDevice+GetString" MarshalDelegate="Required All">
          </Type>
        </Assembly>
   </Application>  
</Directives> 
`

But the problem still persists.

I attached a sample project with this issue.
[FNA CoreRT Test.zip](https://github.com/FNA-XNA/FNA/files/2502477/FNA.CoreRT.Test.zip)
It can be built in AOT with build_native.bat.
The executable is generated in FNA CoreRT Test\bin\Release\netcoreapp2.1\win-x64\publish

**Comment by flibitijibibo** [comment]
What in the world...? Can you explain what this is? I've never heard of any of this.

The only thing I can see that may be a CoreRT problem rather than FNA is this message here:

```
Microsoft.Xna.Framework.Graphics.OpenGLDevice+GetString is missing delegate marshalling data. To enable delegate marshalling data, add a MarshalDelegate directive to the application rd.xml file. For more information, please visit http://go.microsoft.com/fwlink/?LinkID=393965
```

**Comment by BurgerBob** [comment]
That is because Marshal.GetDelegateForFunctionPointer emits IL at runtime, and CoreRT does not know by default that it has to generate this code in advance.

So you are supposed to tell him in a rd.xml. I did, but it does not work.

I know it is a CoreRT problem, but I thought you would find it cool to have FNA be able to compile AOT. And if so, provide a default rd.xml.

.Net native uses the same kind of AOT compilation, is there a UWP version of FNA ?

**Comment by flibitijibibo** [comment]
FNA UWP uses FNA.Core. I currently have an Xbox One project using this and it seems okay, so this caught me by surprise.

Definitely complain to CoreRT. If they want to interop with native libraries, being able to work with function pointers is pretty important...

**Comment by BurgerBob** [comment]
Ok, thanks, I created an Issue on their side :
[https://github.com/dotnet/corert/issues/6479](url)

**Comment by BurgerBob** [comment]
jkotas answered, and the workaround is pretty simple :
replacing all (MyDelegate)Marshal.GetFunctionPointerForDelegate(MyMethod, typeof(MyDelegate)) by
Marshal.GetFunctionPointerForDelegate<MyDelegate>(MyMethod)

Do you see any drawbacks of doing that ?

**Comment by flibitijibibo** [comment]
Well for one, that API is marked obsolete and has been since at least 4.0...

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getfunctionpointerfordelegate?redirectedfrom=MSDN&view=netframework-4.7.2#System_Runtime_InteropServices_Marshal_GetFunctionPointerForDelegate_System_Delegate_

I do like their other idea though, I thought `UnmanagedFunctionPointer(CallingConvention.StdCall)` was the default but perhaps that is not the case everywhere. Add this to all the delegates in OpenGLDevice_GL.cs and ModernGLDevice_GL.cs:

`[UnmanagedFunctionPointer(CallingConvention = CallingConvention.StdCall)]`

If that fixes it, send the PR and I'll merge it right away. Pretty much the only thing that could go wrong is spaces instead of tabs, so should be a quick review :P

**Comment by BurgerBob** [comment]
GetFunctionPointerForDelegate(Delegate) is marked obsolete, because it was replace by the generic one.

[System.Obsolete("GetFunctionPointerForDelegate(Delegate) may be unavailable in future releases. Instead, use GetFunctionPointerForDelegate<T>(T). For more info, go to http://go.microsoft.com/fwlink/?LinkID=296522")]
[System.Security.SecurityCritical]
public static IntPtr GetFunctionPointerForDelegate (Delegate d);

So it would be more logical to replace all GetFunctionPointerForDelegate(Delegate) by GetFunctionPointerForDelegate<T>(T), no ?

That is what I am in the process of doing ...

**Comment by BurgerBob** [comment]
ok

**Comment by BurgerBob** [comment]
Done. That's my first pull request ever so I hope I did it right.
I also added a sample rd.xml (copied from the MonoGame one).

**Comment by flibitijibibo** [comment]
Thanks! The patch needs a couple quick changes but in any case, thanks for looking into it. I probably wouldn't have run into it for a really long time...

**Comment by flibitijibibo** [comment]
https://github.com/FNA-XNA/FNA/commit/8e4a826af519532a593212d23f928ebd487e0958
