### ISSUE TITLE
Latest FNA (head) breaks rendering in Shipwreck

### ISSUE THREAD

**Issue by nickgravelyn** [FNA-XNA/FNA#21]
Was just trying to do a simple update to Shipwreck including bumping to the latest FNA, but it seems rendering is totally busted for our game:

![fna bug](https://cloud.githubusercontent.com/assets/361789/14627318/058b3392-05a8-11e6-8394-a40f3b4aef9f.png)

Got any immediate ideas? I just saw this and haven't yet done any real research; we generally only build against release so I don't have debugger output. I'm going to do some looking into it but wanted to put this on your radar.

If you want to look into it, you should be able to grab the build from Steam and replace the DLL and see this (I would assume). I can also grant you permissions to our Git repo if that helps.

**Comment by flibitijibibo** [comment]
Probably the MojoShader update:

https://plus.google.com/+flibitijibibo/posts/X3M9NrHVejm

**Comment by nickgravelyn** [comment]
Ah, I didn't catch that part. I think I'm going to stick to 16.04 for now since that is working fine with the latest native libs and it's probably best for us to just stick to the monthly releases since our game doesn't really need any perf improvements. :)
