### ISSUE TITLE
TrueType

### ISSUE THREAD

**Issue by nanodesu88** [FNA-XNA/FNA#223]
Hello. How can i load ttf fonts without using XNA Content Pipeline?

**Comment by flibitijibibo** [comment]
With SharpFont! https://github.com/Robmaister/SharpFont/

Load the file, render the glyphs, push the bitmaps to a Texture2D and render with source rectangles based on the location of the glyph in the spritesheet.

**Comment by nanodesu88** [comment]
Thanks you, will try
