### ISSUE TITLE
GetHashcode()

### ISSUE THREAD

**Issue by codiemorgan** [FNA-XNA/FNA#224]
https://github.com/FNA-XNA/FNA/blob/74c428fdda2234f6ab0cb4bef9ebffbdddc99a19/src/Vector3.cs#L279

 GetHashCode() literally just (int)(X + Y + Z), which I'm pretty sure is a super frustrating bug.

In Vector2.GetHashcode() the hashes are simply added together , but in Vector3 the vector components are added, rounded, and returned, without any hashing...

Coords   (1,0, 0.0 ,0.0),   (0.0, 1.0, 0.0)    and  (0.0, 0.0, 1.0)    will all have exactly the same hashcode.
Coords  (0, 0, 0.75f) and (0.0, 0.0, 1.0) will also have the same hash code because we are rounding to int.

I think it would be safer, and **less frustrating**, to actually have unique hashes for every coordinate in all dimensions (so they actually work in hash tables): 

 - vec4=  X.GetHashCode() ^ (Y.GetHashCode() << 2) ^ (Z.GetHashCode() >> 2) ^ (W.GetHashCode() >> 1);
 - vec3=  X.GetHashCode() ^ (Y.GetHashCode() << 2) ^ (Z.GetHashCode() >> 2);
 - vec2=  X.GetHashCode() ^ (Y.GetHashCode() << 2);

**Comment by flibitijibibo** [comment]
What does XNA do here? I don't totally remember where this came from but if XNA does something this bad, we have to live with it...

**Comment by codiemorgan** [comment]
I don't know. But monogame has exactly the same mistake. None of their vectors are collision safe either.

**Comment by flibitijibibo** [comment]
Very well - you're going to want to look at this more closely, but I agree that the hashing method sucks, so I've at least made them consistent with one another:

https://github.com/FNA-XNA/FNA/commit/d103dce05d9f48dd0c1dba5ff5e4df4d333c5349

I hope this is more right, but if it turns out the crappy hash is the right hash, we'll have to revert this.

**Comment by codiemorgan** [comment]
I have just dug out the XNA assemblies from my GAC and decompiled 'Microsoft.Xna.Framework.dll '

They way you have updated it to now is the same way MS has done it.   

Probably still not collision safe (would need to test this), but it now matches microsoft's GetHashCode in an XNA4 assembly.

**Comment by flibitijibibo** [comment]
Just as an FYI, decompilation isn't something we're legally allowed to do. I had to delete that... we need to compare output from each version and make sure it actually aligns properly. You may just have to try every float value for each struct entry and compare the hashcode for every combination.

**Comment by codiemorgan** [comment]
That's fine. I was able to verify the Vector2 and _now_ Vector3 implementation is the correct impl. (which means MonoGame's implementation has been wrong all this time).
