### ISSUE TITLE
0xc000041d error at game startup

### ISSUE THREAD

**Issue by andreakarasho** [FNA-XNA/FNA#225]
Hi, after windows 10 update my game has some difficulty to run.
I've to try 3/4 times before run the game.

The game exits without any popup error. I take the 0xc000041d code from the VS output tab.
I added the FNA project to my game to debug and the problem seems to be here:
https://github.com/FNA-XNA/FNA/blob/d103dce05d9f48dd0c1dba5ff5e4df4d333c5349/src/FNAPlatform/SDL2_FNAPlatform.cs#L191

Basically after the Window creation the game stops to run.

No idea why :D

**Comment by flibitijibibo** [comment]
Going to need a bit more than this... what exact line fails? Is it SDL_SetMainReady, or something before/after? Does this happen on any other OS? What's the CPU target? I need real information first.

**Comment by andreakarasho** [comment]
There is not a real line, that's the problem. Seems like it crashes after a while.

If i debug and put a breakpoint here: https://github.com/FNA-XNA/FNA/blob/d103dce05d9f48dd0c1dba5ff5e4df4d333c5349/src/Game.cs#L246

It works. After using the CreateWindow method after a custom amount of time it crashes, also if i set a breakpoint at first line of the CreateWindow method and i stop the execution.


CPU target: x64
OS: windows 10 latest build (didnt try on other OS atm)

**Comment by andreakarasho** [comment]
Seems it's a problem between rivatuner and windows.
Sorry for the false alarm.
