### ISSUE TITLE
ABI Compatibility via Type Forwarding

### ISSUE THREAD

**Issue by flibitijibibo** [FNA-XNA/FNA#226]
Here's a really interesting one! This one's for me, @madewokherd, and @0x0ade.

For Proton's .NET support we'd like to have FNA as the built-in XNA reimplementation, but one of the main hurdles is that FNA doesn't follow the XNA ABI at all. Historically Maik and I have just hacked the games directly via [XnaToFna](https://github.com/0x0ade/XnaToFna), which has a couple benefits:

- Can use stock FNA
- Lets us do some extra glitter for Linux native support
- Lets us automatically work around some ugly Windows gunk (Forms comes to mind...)

For a broad solution, however, ABI compatibility is our best bet. This would introduce some problems though:

- Possibly need to refactor huge portions of FNA
- Can't fix up anything for Linux native support
- Can't hack around Windows stuff

The second/third parts I'm willing to ignore since A: The worst actors are games I've already ported, and B: This would primarily be for Wine and wine-mono, which of course won't care about the Win32-y stuff as much. D3D9 would still be a problem but literally the only XNA software I've seen that goes remotely near it is Katelyn's Squared.Render stuff (which, again, we have FNA native ports for).

The first part we may very well have a fix for! From MSDN...

https://docs.microsoft.com/en-us/dotnet/framework/app-domains/type-forwarding-in-the-common-language-runtime

>Type forwarding allows you to move a type to another assembly without having to recompile applications that use the original assembly.

This is pretty much exactly what we need! The XNA4 API is 100% safe C#, so the C++/CLI side should hopefully not be a problem. The _real_ problem is, uh, how do we generate all this stuff... I'm thinking it'd be smart to autogenerate everything, but that's coming from a guy who's literally never autogenerated any of his code ever, even for nothing-but-PInvoke libraries. Someone who has actually done this before would need to hold my hand on how to make the process easy.

If we do actually pull this off, it will be a good time to consider getting some of the XnaToFna workarounds into FNA as special paths (for example, returning the Win32 HWND for GameWindow.Handle). In a perfect world we could replace XnaToFna with a few environment variables and the type-forwarding assemblies, but we'll see how close we can get to that.

**Comment by madewokherd** [comment]
ABI compatibility also won't work with .NET because it requires pkt remapping.

You could use Mono.Cecil to get a list of public types from each library and generate C# source code. Here's something I hacked together to read exported types once: https://github.com/madewokherd/getclrinterface/blob/master/getclrinterface/Main.cs

**Comment by flibitijibibo** [comment]
I just made a bunch of ABI DLLs and... it actually works just fine?!

![screenshot from 2019-01-18 16-48-04](https://user-images.githubusercontent.com/1396814/51414693-4cfd3e80-1b41-11e9-923d-dcd8950a703a.png)

I don't know if this works with .NET (maybe it's picky about the PublicKeyToken) but for Mono it's running my XnaToFna test cases without touching _any_ of the game executables. Here are the files...

[fnaabi.zip](https://github.com/FNA-XNA/FNA/files/2774641/fnaabi.zip)

I just loaded up each assembly, GetExportedTypes()'d them, and generated some source files. I def'd out some Media stuff nobody uses and the Net stuff is def'd out until we make a clean FNA.NetStub.dll (I think FNA.Steamworks has an early revision that's basically this).

**Comment by flibitijibibo** [comment]
Committed the files to the repository:

https://github.com/FNA-XNA/FNA/commit/78d2e1831077246450208a15a1789343839a59c6

There's still the question of how we'd handle things like `Game.Window.Handle` use in Windows games, but we'll assess that as we explore this in stuff like XnaToFna and Proton.

**Comment by flibitijibibo** [comment]
19.03 pretty much covers this as far as FNA on its own is concerned, the rest is stuff that wine-mono cares about and will be covered there: https://github.com/madewokherd/wine-mono/issues/45
