### ISSUE TITLE
Why are 'MonoGame' and 'FNA' include same games in their showcases?

### ISSUE THREAD

**Issue by kovirolik** [FNA-XNA/FNA#229]
![image](https://user-images.githubusercontent.com/45714643/50738944-d297fa80-11e1-11e9-8764-5390e3eebfc6.png)

**Comment by flibitijibibo** [comment]
There are three reasons I'm aware of:

1. The information is out of date on the MG site. Examples include FEZ for Linux/macOS/Windows and Bastion for Mac.
2. The two frameworks share games. Examples include Celeste and TowerFall, which use FNA on PC and MonoGame on consoles.
3. Square Heroes is the one game I'm aware of where the developer only used FNA but for some reason advertised it as using MonoGame. I'm still not entirely sure why.

A more accurate (but still not 100% reliable) way to figure out which games use what is PCGamingWiki:

https://pcgamingwiki.com/wiki/Engine:FNA
https://pcgamingwiki.com/wiki/Engine:MonoGame
