### ISSUE TITLE
SpriteBatch is significantly slower than stock XNA for sort modes

### ISSUE THREAD

**Issue by kiates** [FNA-XNA/FNA#233]
FNA's SpriteBatch implementation is slower than stock XNA.  It is significantly slower when using the Texture/BackToFront/FrontToBack sorting modes because the .NET framework sort algorithm is forced to copy large value types during the sort.

**Comment by kiates** [comment]
Here are my benchmarks XNA vs FNA running each type of drawing mode for 12 seconds each with measuring only the last 10 seconds. Numbers are in "ticks" using Stopwatch.

```
Technique: Xna
           Type Average     Min     Max  Median
       Deferred    1522    1352    3546    2449
      Immediate   14045   12797   24639   18718
        Texture    4660    4266    6841    5554
    BackToFront    5378    4977   12616    8797
    FrontToBack    5659    4908   13882    9395
```

```
Technique: Fna
           Type Average     Min     Max  Median
       Deferred    4039    2300    6643    4472
      Immediate   32314   29476   52610   41043
        Texture   15854   11469   28702   20086
    BackToFront   16420   11487   24060   17774
    FrontToBack   17040   11760   29844   20802
```

**Comment by flibitijibibo** [comment]
This is now largely covered by #235. We’re still permanently screwed by being all-managed unlike XNA, but at least the sorted modes scale a little better. I imagine ANGLE improves the situation for low-end hardware, or AMD on Windows.

Note that the best possible optimization will always be a combination of pre-sorted draws and allocating enough buffers to where contention will not occur within a single frame.
