### ISSUE TITLE
Wiki improvements for iOS simulator builds

### ISSUE THREAD

**Issue by TheSpydog** [FNA-XNA/FNA#260]
After some confusion in the Discord about how to prep an app for simulator builds, could we change the [Simulator section](https://github.com/FNA-XNA/FNA/wiki/Appendix-A:-FNA-on-iOS#simulator) of the iOS Appendix to read as follows?

-----

If you want to run your app in the iOS simulator on your Mac, you'll need to do a couple extra things in addition to the above steps:

1. Make sure you've included x86_64 builds of your native libraries. This is the only architecture that the simulator allows. (These are generated by the build scripts when run with "ios-sim" or "ios-fat".)

2. Copy-paste the following into the bottom of `FNA.dll.config`, just before `</configuration>`:
```
	<!-- Remove these when not targeting simulator!!! -->
	<dllmap dll="SDL2"          os="osx" target="__Internal"/>
	<dllmap dll="SDL2_image"    os="osx" target="__Internal"/>
	<dllmap dll="mojoshader"    os="osx" target="__Internal"/>
	<dllmap dll="FAudio"        os="osx" target="__Internal"/>
	<dllmap dll="libtheorafile" os="osx" target="__Internal"/>
```
As the comment says, make darn sure to put this file back the way you found it when you're done. Otherwise, you might be in for a nasty surprise when you try to build for macOS or a physical iOS device.

**Comment by flibitijibibo** [comment]
Done!
