### ISSUE TITLE
[Wiki] Add resolution-handling info to iOS page

### ISSUE THREAD

**Issue by TheSpydog** [FNA-XNA/FNA#261]
In the first section of "Code Changes", we need to change the contents of Main:

```
// Enable high dpi "retina" support. Trust us, you'll want this.
Environment.SetEnvironmentVariable("FNA_GRAPHICS_ENABLE_HIGHDPI", "1");

realArgs = args;
SDL2.SDL.SDL_UIKitRunApp(0, IntPtr.Zero, FakeMain);
```

And let's also add a section directly under that, which reads:

### Retina Displays

For your app to take full advantage of iPhone and iPad retina displays, you need to set your preferred backbuffer size to the full extent of the display. This should happen at the start of your game and in the `Window.OrientationChanged` event callback (if your app supports both portrait and landscape orientations).

```
graphics.PreferredBackBufferWidth = GraphicsAdapter.DefaultAdapter.CurrentDisplayMode.Width;
graphics.PreferredBackBufferHeight = GraphicsAdapter.DefaultAdapter.CurrentDisplayMode.Height;
```

**Comment by flibitijibibo** [comment]
Done!
