### ISSUE TITLE
Can't load png through Texture2D.FromStream

### ISSUE THREAD

**Issue by rds1983** [FNA-XNA/FNA#267]
I can't load following png through Texture2D.FromStream
![image](https://user-images.githubusercontent.com/1057289/63637401-e8d9c480-c6a5-11e9-9a41-eb2572dfc142.png)

It throws NullReferenceException.
Following code is used:
```C#
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using System.IO;

namespace ImageTest
{
	public class MyGame : Game
	{
		private readonly GraphicsDeviceManager graphics;
		private Texture2D _texture;
		private SpriteBatch _spriteBatch;

		public MyGame()
		{
			graphics = new GraphicsDeviceManager(this);
			IsMouseVisible = true;
		}

		protected override void LoadContent()
		{
			_spriteBatch = new SpriteBatch(GraphicsDevice);

			var assembly = typeof(MyGame).Assembly;
			using (var stream = File.OpenRead(@"D:\Projects\ImageTest\Resources\image.png"))
			{
				_texture = Texture2D.FromStream(GraphicsDevice, stream);
			}

			base.LoadContent();
		}

		protected override void Draw(GameTime gameTime)
		{
			base.Draw(gameTime);

			GraphicsDevice.Clear(Color.Black);

			_spriteBatch.Begin();
			_spriteBatch.Draw(_texture, Vector2.Zero, Color.White);
			_spriteBatch.End();
		}
	}
}
```

It falls on Texture2D.FromStream line with NullReferenceException.
I am using latest FNA as well as latest SDL_image.dll downloaded from here: https://github.com/FNA-XNA/FNA/wiki/1:-Download-and-Update-FNA

I've tried with other pngs and they seem to load fine.
Environment: Windows 7x64

**Comment by flibitijibibo** [comment]
Do you have a precise line in FNA where it’s null? If I were to take a guess it’d be the color format but I can’t look at this directly right now.

**Comment by rds1983** [comment]
seems like SDL2_image call returns null:
![image](https://user-images.githubusercontent.com/1057289/63637541-6d791280-c6a7-11e9-8418-f08099bd8b0b.png)

**Comment by rds1983** [comment]
SDL.SDL_GetError() is "Unknown pixel format"

**Comment by flibitijibibo** [comment]
Yep, so that was it... you can either fix it in SDL_image or change the PNG format. FWIW, it always gets converted to RGBA per the spec, so this is really only about disk space.

**Comment by rds1983** [comment]
I see, so it's known issue. Closing then.
