### ISSUE TITLE
Update Environment Variable wiki docs

### ISSUE THREAD

**Issue by TheSpydog** [FNA-XNA/FNA#268]
I was looking over the environment variable documentation and noticed a few entries are outdated:

1. [FNA_OPENGL_FORCE_ES3](https://github.com/FNA-XNA/FNA/wiki/7:-FNA-Environment-Variables#fna_opengl_force_es3): We now officially support iOS and tvOS (both ES3 platforms).
2. [FNA_OPENGL_FORCE_CORE_PROFILE](https://github.com/FNA-XNA/FNA/wiki/7:-FNA-Environment-Variables#fna_opengl_force_core_profile): For the core profile we now use OpenGL 4.6 instead of 3.2.
3. [FNA_GRAPHICS_ENABLE_HIGHDPI](https://github.com/FNA-XNA/FNA/wiki/7:-FNA-Environment-Variables#fna_graphics_enable_highdpi): Might be worth mentioning iOS alongside macOS in the "Retina" screen section.

**Comment by flibitijibibo** [comment]
Good catches, fixed all three in the latest revision!
