### ISSUE TITLE
[Q] use with old XNA games without recompiling

### ISSUE THREAD

**Issue by eadmaster** [FNA-XNA/FNA#271]
is it possible to use the library with old XNA games without recompiling them?

(I am trying to run an old version of [ARES Extinction Agenda EX](https://store.steampowered.com/app/315340/ARES_Extinction_Agenda_EX/))

**Comment by flibitijibibo** [comment]
Only if they do not use xWMA, WMA, or WMV. The game also needs to avoid using explicit half-pixel offset fixes in their vertex data and shaders.

Other than that, this is what you care about: https://github.com/FNA-XNA/FNA/tree/master/abi

**Comment by eadmaster** [comment]
ok, can you provide some instructions on how to use FNA in this use case?

I've downloaded the [fnalibs.tar.bz2 here](http://fna.flibitijibibo.com/archive/fnalibs.tar.bz2).

**Comment by rfht** [comment]
What you are asking is pretty much what fnaify does on *BSD in the 2.0-beta version. It's just a Korn shell script. You can look at what the `xnasetup` function does (https://github.com/rfht/fnaify/blob/master/fnaify#L407).

**Comment by rfht** [comment]
PS: here are the XNA games known so far to work with this approach: https://github.com/rfht/fnaify/blob/master/README.md#xna

**Comment by eadmaster** [comment]
I was hoping for a more straightforward solution, btw i am going to install windows 7 into another partition to play old XNA games...

**Comment by rfht** [comment]
the only more straightforward solution I can think of is contacting the game devs and asking them to build an FNA version
