### ISSUE TITLE
Embedded FNA namespace conflict in iOS

### ISSUE THREAD

**Issue by danielcrenna** [FNA-XNA/FNA#272]
@TheSpydog 

Have you seen this before? I'm referencing FNA within my own game .csproj, and it looks like the `Microsoft.Xna.Framework.Media.MediaPlayer` class is conflicting with a non-namespaced class in Xamarin.iOS (latest version) with the same name.

![image](https://user-images.githubusercontent.com/129610/65806757-2922db80-e159-11e9-9d90-c649c11a8ff9.png)

**Comment by TheSpydog** [comment]
I can't reproduce this on VS 2019 or VS for Mac. I know Xamarin.iOS has a namespace called `MediaPlayer` so that's the source of the conflict, but there's a `using` alias at the top of this file that's supposed to prevent this issue.

I suspect something wonky is going on with your project/solution structure. Is FNA.Core added to your solution, with a reference in your game's project? (Mostly asking since I'm not totally sure what you mean by "embedded FNA".)

**Comment by danielcrenna** [comment]
@TheSpydog I mean I have the FNA sources in a sub-folder in my project, not referencing it separately as a .csproj. I can fix it just by changing the alias to `using MP = Microsoft.Xna.Framework.Media.MediaPlayer;`, rather than `using MediaPlayer = Microsoft.Xna.Framework.Media.MediaPlayer;`, presumably because MP doesn't conflict with the global.

**Comment by flibitijibibo** [comment]
Yeah this is pretty common, though I'm surprised to see it in a Xamarin library. Oftentimes I'll see different Vector2s from both XNA and a physics library, so you just have to alias them as you see them. Annoying, but thankfully easy to fix in the application.

**Comment by danielcrenna** [comment]
@flibitijibibo considering it's relegated to `FrameworkDispatcher.cs`, would you a consider a PR with an alternate alias name? The reason I ask is that I've been working on a proper NuGet package that sets up all dependencies like `fnalibs`, with the goal of having a single package to set up everything as well as a `dotnet new game` one line template setup. I'll close this issue, but it would help the "plug and play" distribution where the developer doesn't necessarily know how to modify source to get things to work.

**Comment by flibitijibibo** [comment]
If we can fix it linking to the Xamarin stuff that’d be a better solution, since the real bug is that it’s complaining about a conflict that doesn’t exist. If it can’t be fixed in the project file, sure, we can add it with a line explaining why it’s there.
