### ISSUE TITLE
Escape Goat 2 missing lighting with /glprofile:core

### ISSUE THREAD

**Issue by TheSpydog** [FNA-XNA/FNA#283]
I was testing EG2 with RenderDoc when I noticed something strange. If I specify `/glprofile:core` then all the lighting effects are missing.

Without `/glprofile:core`:
![correct](https://user-images.githubusercontent.com/8942401/71758568-5d501b80-2e6f-11ea-8543-a99b6bdf396b.PNG)

With `/glprofile:core`:
![wrong](https://user-images.githubusercontent.com/8942401/71758572-64772980-2e6f-11ea-868e-243991a1ccd8.PNG)

I thought it might be a spirv issue, but then I tested the game without `/glprofile:core` and with `/mojoshaderprofile:glspirv` and it worked correctly. To be extra sure, I tested with `/glprofile:core /mojoshaderprofile:glsl120` and it still exhibited the incorrect behavior.

Strangely enough, RenderDoc was still able to capture the non-core version just fine. (It displayed a message about how a core profile wasn't explicitly requested, but that's it.) Windows 10, NVIDIA GTX 1060.

**Comment by flibitijibibo** [comment]
I forget if this game uses user primitives or not... for OpenGLDevice the only difference between core and compat is a dummy vertex array binding.

**Comment by flibitijibibo** [comment]
Ended up confirming this in the Discord, so this is the expected behavior...
