### ISSUE TITLE
Vertex attribute overlap prioritization breaks TEXCOORD10 and above

### ISSUE THREAD

**Issue by jeffphilp** [FNA-XNA/FNA#291]
Hi,

I just updated to the latest version of FNA and it seems the Vertex attribute overlap prioritization commit (https://github.com/FNA-XNA/FNA/commit/9e6319d8d2b417d844dc11c90e27b2a33bf99354) introduced a hard limit of 10 attributes in the attrUse array.  We have a common effects file which makes use of TEXCOORD10, and TEXCOORD11 which unfortunately causes an index out of bounds exception in this code.

Changing the effects file from using TEXCOORD10/11 isn't possible, so I was wondering if a code patch to make this array size configurable through either a define word or environment variable would be acceptable?

**Comment by flibitijibibo** [comment]
I’m surprised that shader ever worked at all! How high can that attrib index go? I thought it only went from 0 to 9.

**Comment by flibitijibibo** [comment]
Nevermind, found a more definitive answer:

https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx9-graphics-reference-asm-vs-registers-input

Will update FNA and fnalibs today.

**Comment by flibitijibibo** [comment]
https://github.com/FNA-XNA/FNA/commit/77d29320193aadcda303bfb44add2ce125bf302f

fnalibs is updated as well.
