### ISSUE TITLE
Problem with windows scaling

### ISSUE THREAD

**Issue by BurgerBob** [FNA-XNA/FNA#292]
On windows, the rendering becomes blurry when the scale display settings is not 100%.
You can reproduce by using the attached project with this steps :
. Build and launch.
[FNA Full Screen Bug Sample.zip](https://github.com/FNA-XNA/FNA/files/4141251/FNA.Full.Screen.Bug.Sample.zip)
. See that the image is not blurry:
![image](https://user-images.githubusercontent.com/4925468/73571144-ed1bc200-443b-11ea-9773-06e57a36a4c7.png)
. Change the windows display settings :
![image](https://user-images.githubusercontent.com/4925468/73571334-4f74c280-443c-11ea-8e86-6b2d1d08e57a.png)
(This does not help : )
![image](https://user-images.githubusercontent.com/4925468/73571378-62879280-443c-11ea-9c21-cb961214c284.png)
See that the image is blurry:
![image](https://user-images.githubusercontent.com/4925468/73571289-3d931f80-443c-11ea-92fe-800170c02ae7.png)

**Comment by flibitijibibo** [comment]
This is a Windows bug, you need an app manifest to fix this:

https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/mt846517(v%3Dvs.85)

**Comment by BurgerBob** [comment]
Thanks for pointing me in the right direction.
Aaaaah Windows ...
Even if it is the recommended approach, the manifest did not work for me (maybe because of .Net Core ?).
So I used this method:
[System.Runtime.InteropServices.DllImport("user32.dll")]
static extern bool SetProcessDPIAware();

SetProcessDPIAware();

Maybe you should consider adding it to FNA (and/or SDL2) ?
It is a problem every FNA application will encounter by default.
But I do not know if it fits with the FNA design goals ...

**Comment by flibitijibibo** [comment]
DPI awareness on Windows is very inconsistent, and as the name suggests the application may genuinely not be aware of the difference, so it’s up to the application to do this locally, just as it’s expected for apps to enable high-DPI modes on platforms that make more sense.
