### ISSUE TITLE
GetGamepadState creates garbage

### ISSUE THREAD

**Issue by BurgerBob** [FNA-XNA/FNA#296]
It can be a problem because it is a method that is typically called each frame.

if (gc_builtState != INTERNAL_states[index])
does boxing and calls Equals

new GamePadState(
				new GamePadThumbSticks(stickLeft, stickRight, deadZoneMode),
				new GamePadTriggers(triggerLeft, triggerRight, deadZoneMode),
				new GamePadButtons(gc_buttonState),
				new GamePadDPad(gc_buttonState)
calls constructors with "params" that create temporary arrays

**Comment by flibitijibibo** [comment]
The disconnected state should be okay, but yeah this part is very `new` heavy. If you can fix this to not allocate so much I’ll merge whatever you come up with, we probably just need to not use the public constructors for this.

**Comment by flibitijibibo** [comment]
This gets rid of the most obvious generators:

https://github.com/FNA-XNA/FNA/commit/be889a528db93e0f776cc6b34ceca8b531d2c52e

If there are any others it'll require more in-depth analysis.

**Comment by BurgerBob** [comment]
I think that is all for the generators due to constructors.
There is still the if (gc_builtState != INTERNAL_states[index]) though.

**Comment by flibitijibibo** [comment]
This at least gets rid of the obvious boxing there... we had explicit comparisons for all the structs except GamePadState itself:

https://github.com/FNA-XNA/FNA/commit/25e6e4c91ced96cd7eeb55d3bcf2e5eab2fbd6df

**Comment by flibitijibibo** [comment]
Closing this as I believe I have fixed the problem - if this is not the case and you want the fix in 20.04 you have about 18 hours to fix it.
