### ISSUE TITLE
Support RasterizerState.MultiSampleAntiAlias = false

### ISSUE THREAD

**Issue by flibitijibibo** [FNA-XNA/FNA#3]
This is an issue continued from the old FNA repository: https://github.com/flibitijibibo/FNA/issues/333

@renaudbedard and I really want this for FEZ 1.12, but sadly GL_MULTISAMPLE is ignored on the majority of drivers used today. We still glEnable/glDisable that enum just in case, so in a way it's implemented for those lonely few cards, but a way around this for everyone would be very much appreciated.

**Comment by flibitijibibo** [comment]
If #11 is even completed then this issue will be resolved, but only for Vulkan. OpenGL will unfortunately be out of luck due to the lack of proper support for disabling GL_MULTISAMPLE.

**Comment by flibitijibibo** [comment]
This could also be solved by #30, in theory.

**Comment by nhydock** [comment]
Just a suggested work around, do you think FNA could just get away with using a FXAA shader instead of GL_MULTISAMPLE?  Using a simple shader for post processing and having it be built into FNA should be a feasible cross-platform solution.

**Comment by flibitijibibo** [comment]
FXAA isn't really the same, and it adds extra rendering passes behind the developer's back... it'd probably be easier to just get multisampling working with a different GLDevice!

**Comment by nhydock** [comment]
While it adds extra rendering passes, it's still typically less work than MSAA on the hardware and notably performs really well, even though the results aren't as great at lower resolutions.

I noticed you even have a [https://gist.github.com/flibitijibibo/85fc0112ec3a1cff08da](gist) for it with SpriteBatch.

**Comment by flibitijibibo** [comment]
That was part our original tests for enabling antialiasing in FEZ. Our conclusion was that it looked like total crap:

https://plus.google.com/+flibitijibibo/posts/48R4vB5MVPN

It didn't help that Tim Lottes even told us not to use it if we could avoid it...

Point is, I'm not writing it in and I don't suspect anyone else will either. Focus on Vulkan or Metal instead.

**Comment by flibitijibibo** [comment]
So while researching MultiSampleMask and glSampleMaski I ended up playing with the idea of setting GL_MULTISAMPLE to false and hoping that would work in combination with `glSampleMaski(0, 1)` or something to get "roughly" the same thing as if GL_MULTISAMPLE was actually respected.

I got to setting `RasterizerState.MultiSampleMask = false` and... uh, apparently it just works now??? WTF? Are there others that could possibly play with this? I swear when @renaudbedard and I were working on FEZ 1.12 it didn't work and there are discussions elsewhere talking about how drivers ignore it, and now I have it working with NVIDIA/Intel Linux and NVIDIA/Intel macOS. If any Windows users or AMD Linux users want to try this I made a super quick test binary:

http://www.flibitijibibo.com/msaaWTF.tar.bz2

Just run Program.exe (or Program.bin.x86_64 on Linux) and toggle the multisample mode with the space bar. The demo is based on this example:

https://msdn.microsoft.com/en-us/library/bb975403.aspx

**Comment by flibitijibibo** [comment]
I now also have it verified as working on NVIDIA/Intel Windows. If this works on AMD I'm marking this as done and the drivers that don't support this will have to deal with it themselves...

I just updated msaaWTF with a corflags fix and Mac binaries; if you run AMD graphics on any platform please give that test project a try. Windows runs `Program.exe` and Linux/macOS runs `./Program`.

**Comment by 0x0ade** [comment]
Ran your test program on my machine. Windows 10, NVIDIA GTX 750 TI, dunno what driver version.

![image](https://user-images.githubusercontent.com/1200380/32954539-acd4eca6-cbb3-11e7-8374-4b490049c69f.png)

Looks like it's still broken with Windows drivers. Kinda surprising, but not shocking ¯\\\_(ツ)\_/¯

**Comment by flibitijibibo** [comment]
Possibly; my Windows machine tends to lag behind so there could be a newer release than what I tried. That said, looking at your output it appears to be working, the edges are aliased :P

**Comment by hoserama99** [comment]
Works as expected on AMD Radeon 460, 10.13.1.

I'm not terribly surprised though - our ports have relied on this for years now. Hitman Absolution needed this to work, and it did as of when we shipped it back in 2014.

**Comment by flibitijibibo** [comment]
Thanks Brad! My guess is macOS has always respected it, though interestingly it's their docs specifically that informed this issue:

https://developer.apple.com/library/content/documentation/GraphicsImaging/Conceptual/OpenGL-MacProgGuide/opengl_fsaa/opengl_fsaa.html

> The commands glEnable(GL_MULTISAMPLE) and glDisable(GL_MULTISAMPLE) are ignored on some hardware because some graphics cards have the feature enabled all the time. That doesn't mean that you should not call these commands because you'll certainly need them on hardware that doesn't ignore them.

I also got confirmation from a Windows AMD user via Twitter (thanks Joaquins Void!), so Linux is all that's left... I'm fine with just Mesa, don't care about fglrx or PRO.

**Comment by renaudbedard** [comment]
+1, works on Windows 10 & nVidia with latest drivers. I'm confused, but I'm glad!

**Comment by flibitijibibo** [comment]
Got a radeonsi result from @kisak-valve so I'm calling this as done as can be. I updated the GL_MULTISAMPLE note accordingly:

https://github.com/FNA-XNA/FNA/commit/c53a5e1677229524d7da23eaa20a6c8a349a521d
