### ISSUE TITLE
Implement MetalDevice

### ISSUE THREAD

**Issue by flibitijibibo** [FNA-XNA/FNA#30]
With Vulkan being MUCH harder to implement than Metal, MoltenVK being proprietary, and MojoShader getting Metal shader support, I've started to warm up to this idea a little bit.

That said, this will still be implemented in a very strict manner.

The Metal documentation can be found here:

https://developer.apple.com/metal/

Unlike OpenGL/Vulkan where we can have managed code with dynamically loaded entry points, Metal will have to be a native C (or rather, Objective-C, barf) library that a C# file (the MetalDevice) will reference with various opaque pointers, and testing for support will be as simple as attempting to load the dylib and falling back to OpenGL if it fails. I will NOT be using anything like Xamarin.Mac due to the absurd dependency tree and sheer size of those projects; just using a single native dylib that only links to Metal and hooking that up to an SDL_Window\* will be far more pleasant.

The overall process and difficulty of this task will be similar to #11, except it should (in theory) be ever so slightly less difficult to test due to both the simpler API and the smaller range of hardware that supports it. On the note of hardware, one side effect of this IGLDevice is that it would allow for easier support of iOS and tvOS, which would certainly need any performance improvements that Metal can provide.

- [ ] Create libFNAMetal.dylib
    - [ ] Create C API for MetalDevice.cs to access
    - [ ] Integrate MojoShader MSL output into Metal renderer
- [ ] Create MetalDevice.cs, DllImport FNAMetal
    - [ ] If FNAMetal fails to load, fall back to OpenGLDevice

**Comment by tgjones** [comment]
FYI, Veldrid now has Metal support, using a custom C# wrapper compatible with .NET Core, no Xamarin.Mac in sight:

https://github.com/mellinoe/veldrid/tree/master/src/Veldrid.MetalBindings

**Comment by flibitijibibo** [comment]
Good to know we can sidestep both Objective-C and Xamarin if needed.

Since this is on my mind, I'll point out that the [Vulkan Portability Initiative](https://www.khronos.org/blog/khronos-announces-the-vulkan-portability-initiative) may render this backend unnecessary if it ever actually ships. Our D3D11 support via ANGLE and existing Vulkan-to-Metal layers have made me MUCH less concerned about writing entire vendor-locked backends when the layers seem to do a pretty good job and are probably healthier for the ecosystem anyway. And hey, it'd give us D3D12 as well.

But again, it'd need to ship. Still waiting for that GitHub repo, Khronos...

**Comment by flibitijibibo** [comment]
This will no longer be pursued as MoltenVK has been open sourced and has already been made compatible with SDL 2.0.8:

https://www.khronos.org/news/press/vulkan-applications-enabled-on-apple-platforms

https://hg.libsdl.org/SDL/rev/d97ab6d12404

Please refer to the VulkanDevice issue if you were looking to replace OpenGL on macOS.
