### ISSUE TITLE
FNA crashes at launch on some PCs

### ISSUE THREAD

**Issue by BurgerBob** [FNA-XNA/FNA#307]
People reviewing our game at Valve had the game crashing at this place:
> Unrecognized window depth/stencil format!
> at Microsoft.Xna.Framework.Graphics.OpenGLDevice..ctor(PresentationParameters, GraphicsAdapter) + 0xf68
> at Microsoft.Xna.Framework.SDL2_FNAPlatform.CreateGLDevice(PresentationParameters, GraphicsAdapter) + 0x6b
> at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter, GraphicsProfile, PresentationParameters) + 0x1a9
> at Microsoft.Xna.Framework.GraphicsDeviceManager.Microsoft.Xna.Framework.IGraphicsDeviceManager.CreateDevice() + 0xe8
> at Microsoft.Xna.Framework.GraphicsDeviceManager.get_GraphicsDevice() + 0x1f
> at Microsoft.Xna.Framework.Game.InitializeGraphicsService() + 0x64
> at Microsoft.Xna.Framework.Game.DoInitialize() + 0x1a
> at Microsoft.Xna.Framework.Game.RunOneFrame() + 0x29

I changed the code to:
`throw new NotSupportedException($"Unrecognized window depth/stencil format! depth: {depthSize}, stencil: {stencilSize}");`
and I asked them to launch the game again, here was the result:
> Unrecognized window depth/stencil format! depth: 32, stencil: 8

If openGL says that SDL_GL_DEPTH_SIZE (the minimum number of bits in the depth buffer) is superior to 24, FNA won't launch.
I did this blind fix:
```
else if (depthSize >= 24 && stencilSize >= 8)
{
	windowDepthFormat = DepthFormat.Depth24Stencil8;
}

```
but I do not know for sure if it is the right way to solve it.

The machine where the bug occurred had a 
NVIDIA GeForce GTX 1660Ti with OpenGL 1.1

**Comment by flibitijibibo** [comment]
> NVIDIA GeForce GTX 1660Ti with OpenGL 1.1

That sounds like an extremely broken system that FNA just caught for you, are you absolutely positive that's the GL version being reported by the system?

**Comment by BurgerBob** [comment]
Yes it is weird, I just asked them for confirmation ...

**Comment by flibitijibibo** [comment]
Looked at this one more time to be sure, since I haven’t seen this happen in years, but I’m pretty convinced that test box is actually using GDI?!

https://stackoverflow.com/questions/22435518/sdl2-and-glew-unable-to-get-proper-opengl-version-if-using-sdl-gl-setattribute

If the hack doesn’t fix it there, you may want to cheat with ANGLE: https://github.com/FNA-XNA/FNA/wiki/4:-FNA-and-Windows-API#direct3d-support

(Also, sent you a separate e-mail about the builds, let me know if you got it!)

**Comment by flibitijibibo** [comment]
This has been integrated into master so we can provide better logging of the issue:

https://github.com/FNA-XNA/FNA/commit/35cb1f54e717edff571757205f0d8ebebc61650a

Whenever this happens, it should now log a warning and then produce the more legible NoSuitableGraphicsDevice messagebox. I'm still super confident that this is GDI taking over, this code path should help confirm these cases more clearly.
