### ISSUE TITLE
Cannot load .png in new FNA game

### ISSUE THREAD

**Issue by ahrnbom** [FNA-XNA/FNA#309]
Hi! I'm not really sure if this is a problem in FNA or the "new" tutorial for making FNA games from scratch (this one: https://gist.github.com/flibitijibibo/1ce4b7899b3cf1805a420330f0d2faf3)

I'm following the tutorial and everything works fine up until the "The First Sprite" part. I created an image called FNATexture.png and put it in a folder called Content. I then run the exact code from the tutorial, and then I get the following error:

```Exception has occurred: CLR/Microsoft.Xna.Framework.Content.ContentLoadException
An unhandled exception of type 'Microsoft.Xna.Framework.Content.ContentLoadException' occurred in FNA.dll: 'Could not load asset FNATexture! Error: The directory was not found.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\Users\mahrn\Documents\TestGame\bin\Debug\netcoreapp3.1\Content\FNATexture.xnb'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at Microsoft.Xna.Framework.TitleContainer.OpenStream(String name) in C:\Users\mahrn\Documents\FNA\src\TitleContainer.cs:line 52
   at Microsoft.Xna.Framework.Content.ContentManager.OpenStream(String assetName) in C:\Users\mahrn\Documents\FNA\src\Content\ContentManager.cs:line 241
```

I find this error quite confusing. Most importantly, the error implies that the code is looking for a .xnb-file, and not a .png. This makes me believe that the FNA code is actually expecting that the user should run a MonoGame-style Content Pipeline to convert the image before, but this isn't mentioned anywhere in the tutorial, and as far as I know, FNA doesn't have such a pipeline and should be able to load the .png directly. 

I tried changing the image loading line to `texture = Content.Load<Texture2D>("FNATexture.png");` but that doesn't work either; then I get the same error except for this line
`Innermost exception 	 System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\Users\mahrn\Documents\TestGame\bin\Debug\netcoreapp3.1\Content\FNATexture.png.xnb'.`

So this function seems very adamant that it's looking for a .xnb file and not a .png file.

After googling a bit, I came across this old issue: https://github.com/FNA-XNA/FNA/issues/267
Here, there's some code of directly loading a .png which seems to work for me.

Therefore, unless I've misunderstood something important, I'd suggest one of the following:
1. Update the tutorial to change the line `texture = Content.Load<Texture2D>("FNATexture");` to something like 
```
var assembly = typeof(FNAGame).Assembly;
			using (var stream = File.OpenRead(@"Content\FNATexture.png"))
			{
				texture = Texture2D.FromStream(GraphicsDevice, stream);
			}
```
, or some other code that works directly with .png images
2. Change ContentManager.ReadAsset to natively support reading .png images (unless of course this already works somehow, in which case it might be a good idea to clarify how it works)

In case it makes a difference, I'm using .Net Core 3.1 on Windows, with Visual Studio Code. I'm using commit 03cbf9a49ab626a29047894afa66ad095d2bbf54 of FNA.   

Thanks for making this awesome framework!

**Comment by flibitijibibo** [comment]
The error message is accurate to the spec, so that won’t be changing.

The FromStream call is also technically invalid in that example, it needs to be using TitleContainer.OpenStream. This is what the content loader does internally.

Step through the Load call to see where it’s going wrong, as the current sample works for me.

**Comment by ahrnbom** [comment]
After debugging carefully, I've finally figured it out: It does look for a file in /bin/Debug/Content/FNATexture.png, it's just that I didn't set up the csproj file to copy the Content folder to /bin/Debug when building. 

Adding
```
Content Include="Content\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>  
```

into the `<ItemGroup>`  tag in the .csproj file fixes the issue.

I'm closing this because I figured it out. I guess you could consider mentioning this in the tutorial in case others get confused by it just like I did, but you could also argue that it's beyond the scope of the tutorial to explain how .csproj files work. 

Thanks for your help and fast response!


Just in case someone comes here by googling and need help constructing their .csproj files for FNA, here's what I used:

```
<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FNA\FNA.Core.csproj" />
    <Content Include="Content\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>  
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

</Project>
```
