### ISSUE TITLE
Embed FNA in Winforms

### ISSUE THREAD

**Issue by Torshid** [FNA-XNA/FNA#31]
Hi,

I have some kind of game editor working with XNA/Winforms, and I wanted to give a try to FNA after some problems with Monogame.
However, I was not able to find any code using a winform, beside the _SDL2WindowExample.cs_ in which I see no link to FNA.
Basically, I would like to embed a Game class to a winform control (picturebox or whatever), with all the loops, loading, drawing, ..., working. Is that possible? If not with Winforms, is it possible with Gtk, Xwt, or even Eto.Forms?

Thank you

**Comment by flibitijibibo** [comment]
It works, but you need to use Game.Window.Handle with SDL_SysWMinfo, as the example points out.

**Comment by flibitijibibo** [comment]
New FNA example has been pushed to the Gist link, use that and you'll be fine.

**Comment by Torshid** [comment]
Great, I will give it a try, thank you. :)

**Comment by Torshid** [comment]
It worked well, but is there a cross platform solution? The only problem seems to be the user32.dll import.

**Comment by flibitijibibo** [comment]
There is not. I would focus on putting your editor in the engine itself, possibly using something like ImGui to render:

https://github.com/ocornut/imgui

The last thing you want as a dependency is a UI lib like wx/GTK/Qt/Forms/etc... I make good money getting rid of stuff like that.
