### ISSUE TITLE
Feature Request - Add a Vector Limit Method

### ISSUE THREAD

**Issue by v-kainth** [FNA-XNA/FNA#310]
Hey I have a Feature Proposal for the Vector structs. A limit function as described by the code below, will help in limiting a vector's magnitude to the supplied value. Just a nice to have, not necessary. I can issue a PR if you'd like this implemented for all Vectors too
```c#
// Limits the velocity based on the max value
public static Vector2 LimitVector(Vector2 vector, float max)
{
	if (vector.LengthSquared() > max * max)
	{
		vector.Normalize();
		vector *= max;
	}
	return vector;
}

// Limits the velocity based on the max value
public static void LimitVector(ref Vector2 vector, float max, out Vector2 outVector)
{
	if (vector.LengthSquared() > max * max)
	{
		vector.Normalize();
		vector *= max;
	}
	outVector = vector;
}
```

**Comment by flibitijibibo** [comment]
This can be implemented either as a standalone function or as an extension method:

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods

Functionally the method seems fine, we just make it a policy to avoid extensions unless they're absolutely impossible to implement from the outside.
