### ISSUE TITLE
SpriteBatch.Draw and DrawString don't throw an exception when Begin isn't called

### ISSUE THREAD

**Issue by PoroCYon** [FNA-XNA/FNA#312]
This is an accuracy note, and maybe shouldn't be fixed for performance reasons.

However, in some obscure edge cases in games, this behavior is expected, but dragging down performance everywhere while the game in question already uses an outdated FNA build feels like a bad idea.

**Comment by flibitijibibo** [comment]
I think we can strip that DEBUG conditional out now - it was an artifact from when we were struggling to compete with the original XNA SpriteBatch, while we’re probably still not 1:1 here I don’t think one bool check will make it any worse. If removing that line fixes the issue we can get this into master!

**Comment by PoroCYon** [comment]
As I already mentioned elsewhere, actually trying this out won't be very practical in this case, as everything depends on legacy versions, and updating everything will be annoying.

However, adding this back in (using runtime bytecode injection...) seems to make things work properly, so removing the conditional would most likely fix it as well.

**Comment by flibitijibibo** [comment]
Very well, I’ll run some tests just to be sure and we’ll get this into 20.06.

**Comment by flibitijibibo** [comment]
As expected, it's pretty much immeasurable, so:

https://github.com/FNA-XNA/FNA/commit/80fed01bcb0027f7e307be66570b2a752c647af6
