### ISSUE TITLE
DynamicSoundEffect references in FrameworkDispatcher.Update() are sometimes null.

### ISSUE THREAD

**Issue by ZaneDubya** [FNA-XNA/FNA#316]
Running 20.06.

My bug reporter has collected a small number of null reference exceptions from players. The null reference exception is thrown from [FrameworkDispatcher.cs at line 40](https://github.com/FNA-XNA/FNA/blob/3d470062728d4879fbbb47ab45f853bf870f1a5c/src/FrameworkDispatcher.cs#L40).

I instance and dispose of DynamicSoundEffect instances on a second thread, but I do not directly modify the FrameworkDispatcher.Streams collection from my code.

I edited the linked Update() routine as follows, and have not seen any crashes since. My changes are:
- Lock Streams because the Streams object can be updated while this method is running,
- Make sure the instance is not null before updating.

I am happy to submit this (in your coding style) as a PR.

        public static void Update() {
            /* Updates the status of various framework components
            * (such as power state and media), and raises related events.
            */
            for (int i = 0; i < Streams.Count; i += 1) {
                DynamicSoundEffectInstance dsfi = null;
                lock (Streams) {
                    if (Streams.Count > i) {
                        dsfi = Streams[i];
                    }
                    if (dsfi == null) {
                        continue;
                    }
                }
                dsfi.Update();
                if (dsfi.IsDisposed) {
                    i -= 1;
                }
            }
            . . .

**Comment by flibitijibibo** [comment]
It seems like the lock should be for the whole loop, not for each access. That should prevent the entries from ever being null.

**Comment by ZaneDubya** [comment]
Yes, that would simplify it:

            lock (Streams) {
                for (int i = 0; i < Streams.Count; i += 1) {
                    DynamicSoundEffectInstance dsfi = Streams[i];
                    dsfi.Update();
                    if (dsfi.IsDisposed) {
                        i -= 1;
                    }
                }
            }

**Comment by flibitijibibo** [comment]
Makes sense to me! If this works for you, send the patch with tabs + left braces and I'll merge it in today.

One of the peculiar behaviors of the DSFI list is that when an effect is Disposed, it is removed from the list, so if we're in this block and it ends with the instance being disposed, we know it's been removed from the list and we need to decrement to avoid skipping over a buffer.

**Comment by ZaneDubya** [comment]
I've opened a PR with tabs and left braces at #317 - let me know if any changes are needed.

Thanks for all your work on this project!

**Comment by flibitijibibo** [comment]
Fixed by #317!
