### ISSUE TITLE
Loading the specific png image through Texture2D.FromStream results in ArgumentNullException

### ISSUE THREAD

**Issue by rds1983** [FNA-XNA/FNA#321]
The project to reproduce the issue is attached(the image is part of it).
It was compiled against latest version of FNA from this repo.
The native binaries(winx64) were taken from here: http://fna.flibitijibibo.com/archive/fnalibs.tar.bz2

It's important to notice that other png images seems to load fine.
Moreover the managed stb_image seems to load this specific png fine too.

[FNATextureFromStreamPerformanceTest.zip](https://github.com/FNA-XNA/FNA/files/5009804/FNATextureFromStreamPerformanceTest.zip)

**Comment by flibitijibibo** [comment]
Unfortunately this report came at just about the worst time - the new graphics library is totally replacing the image loader and that replacement is getting merged after tomorrow's tag. So if it's actually a bug in the image library it will have to stay in pre-20.09 fnalibs permanently unless you (yes, you) diagnose and fix the issue in the next 10 hours.

**Comment by rds1983** [comment]
Well, if the bug will go away in the upcoming version, it's totally fine by me.

**Comment by flibitijibibo** [comment]
Luckily for you, someone ran this through `file` for you:

>AgedPavement_height.png: PNG image data, 512 x 512, **8-bit gray+alpha**, non-interlaced

So no, neither version will work because the image format is unsupported per the specification. You will have to load/palette-ify this yourself in the application.

**Comment by rds1983** [comment]
Thanks for the response.
I would like to sorry beforehand, if my advice isnt welcome.
Still, if it was me, I'd throw more informative Exception than vague ArgumentNullException.
At least it should be something like "Image isnt supported.".

**Comment by flibitijibibo** [comment]
It already does this: https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/SDL2_FNAPlatform.cs#L1699

**Comment by rds1983** [comment]
Thanks for clarification.
Also, it's important to notice that the image loaded fine when I changed references to the original xna 4.

**Comment by flibitijibibo** [comment]
If you're 100% sure you need this pixel format, this is where you'll want to start stepping in the new graphics library:

https://github.com/FNA-XNA/FNA3D/blob/master/src/FNA3D_Image.c#L217

Instructions for the new setup are here: https://github.com/FNA-XNA/FNA/wiki/BETA:-FNA3D
