### ISSUE TITLE
XACT Distance->Volume RPCs require min/max values set

### ISSUE THREAD

**Issue by teamtwentythree** [FNA-XNA/FNA#33]
Minor bug related to using XACT RPCs to give volume drop off.  In XNA not setting a min/max value causes the adjacent values to be used (As the graphic below shows).  In FNA if not within this range the volume is set to zero (Or at least I assume, sound effects are no longer audible).  

![image](https://cloud.githubusercontent.com/assets/10147585/16315417/0b054fd4-3937-11e6-9095-ca55eacf2660.png)

Adding a point at the min/max (Distance 0 and 1000 on this example) seems to resolve this issue.

**Comment by flibitijibibo** [comment]
I think it depends on the curve type, but at the moment we only do linear anyway so this is definitely a problem. If you want to dig through the curve data calclulation yourself:

Data parsing: https://github.com/FNA-XNA/FNA/blob/master/src/Audio/AudioEngine.cs#L300

Actual Math: https://github.com/FNA-XNA/FNA/blob/master/src/Audio/XACTInternal.cs#L233

My guess is it's line 250 that just needs to be capped, but mess around with the curves a bit in the tool and see what the outer bounds should do.

**Comment by teamtwentythree** [comment]
Maybe I'm not thinking of something, but I think 236->254 becomes the following.  No need to special case 0 since it'll fall somewhere in the range anyway (Which seems bound from 0-X, but even if not it should be fine).  For before the first point and after the last it would just be the value of the nearest point.  

```C#
			// TODO: Non-linear curves
			if (varInput <= Points[0].X)
			{
				// Zero to first defined point
                return Points[0].Y;
			}
			else if (varInput >= Points[Points.Length - 1].X)
			{
				// Last defined point to infinity
                return Points[Points.Length - 1].Y;
			}
			else
			{
```

**Comment by flibitijibibo** [comment]
Give it a try locally, if it works I'll go ahead and write that in.

**Comment by teamtwentythree** [comment]
Yea, this fix is working for us.

**Comment by flibitijibibo** [comment]
https://github.com/FNA-XNA/FNA/commit/414fb160b5f46dfb843aed70fac8f6646c0c9272
