### ISSUE TITLE
[UWP] Mouse events not processed correctly

### ISSUE THREAD

**Issue by PumpkinPaul** [FNA-XNA/FNA#338]
I've noticed an issue with the mouse on FNA Core / SDL WinRT.

If a mouse button is held, other mouse button events do not get fired / handled.
e.g. 

Hold MOUSE1 - SDL_MOUSEBUTTONDOWN (1) fired correctly
Hold MOUSE2 - no event fired

The following situation IS handled correctly...
Hold MOUSE1 - SDL_MOUSEBUTTONDOWN (1) fired correctly
Release MOUSE1 - SDL_MOUSEBUTTONUP (1) fired correctly

Hold MOUSE2 - SDL_MOUSEBUTTONDOWN (3) fired correctly
Release MOUSE1 - SDL_MOUSEBUTTONUP (3) fired correctly

```c#
private static SDL.SDL_EventFilter _winRTEvents = WinRTEvents;
private static unsafe int WinRTEvents(IntPtr userdata, IntPtr evtPtr)
{
	SDL.SDL_Event* evt = (SDL.SDL_Event*)evtPtr;
	switch (evt->type)
	{
		case SDL.SDL_EventType.SDL_MOUSEBUTTONDOWN:
			Debug.WriteLine($"WinRT event handler SDL_MOUSEBUTTONDOWN {evt->button.button}");
			break;

		case SDL.SDL_EventType.SDL_MOUSEBUTTONUP:
			Debug.WriteLine($"WinRT event handler SDL_MOUSEBUTTONUP {evt->button.button}");
			break;

		case SDL.SDL_EventType.SDL_APP_TERMINATING:
			Debug.WriteLine("WinRT event handler SDL_APP_TERMINATING -> Exiting()");
			break;

		case SDL.SDL_EventType.SDL_APP_WILLENTERBACKGROUND:
			Debug.WriteLine("WinRT event handler SDL_APP_WILLENTERBACKGROUND -> Suspending()");
			break;

		case SDL.SDL_EventType.SDL_APP_WILLENTERFOREGROUND:
			Debug.WriteLine("WinRT event handler SDL_APP_WILLENTERFOREGROUND -> Resuming()");
			break;
	}

	return 1;
}

public void Run(LaunchOptions launchOptions)
{
	_launchOptions = launchOptions;

	SDL.SDL_SetHint("SDL_WINRT_HANDLE_BACK_BUTTON", "1");
	SDL.SDL_AddEventWatch(_winRTEvents, IntPtr.Zero);
	SDL.SDL_main_func mainFunction = FakeMain;
	SDL.SDL_WinRTRunApp(mainFunction, IntPtr.Zero);
}
```

_Issue happens with / without the custom event filter_

Followed the guide here...
https://github.com/FNA-XNA/FNA/wiki/Appendix-B:-FNA-on-Consoles

This is a WinRT / UWP project running on Windows 10 Home 10.0.19041 Build 19041

VS project template from here...
https://gist.github.com/clarvalon/3dc6b70cd7ccf3edb9847b7283e82a7c

I'm guessing this is an issue with SDL WinRT? and FNA merely inherits the problem.

FNA source up to date as at Nov 14, 2020
FNA dependences (FNA3D, etc) built from source on this date also
SDL version 2.0.12 (stable)

**Comment by flibitijibibo** [comment]
That's definitely an SDL-WinRT issue, possibly even a WinRT issue. File it here and CC me:

https://bugzilla.libsdl.org/

**Comment by PumpkinPaul** [comment]
Nice one, thanks.

SDL issue raised: https://bugzilla.libsdl.org/show_bug.cgi?id=5381

**Comment by flibitijibibo** [comment]
Issue was moved to GitHub: https://github.com/libsdl-org/SDL/issues/3908

**Comment by flibitijibibo** [comment]
Latest SDL fixes this issue.
