### ISSUE TITLE
Q: SDL2 was not found! Do you have fnalibs?

### ISSUE THREAD

**Issue by SaltedReed** [FNA-XNA/FNA#339]
I was following FNA From Scratch and started a project with reference to FNA. The compiling of the project was ok, but when I tried to run it, an error of "SDL2 was not found! Do you have fnalibs?" occurred. My guess is that it's because I didn't follow the step of "Next to your executable, you will put the native libraries you downloaded earlier into this folder" in FNA From Scratch, but I cannot find any library in the folder of "FNA/lib" and "FNA/bin". What should I do now?

**Comment by flibitijibibo** [comment]
https://gist.github.com/flibitijibibo/1ce4b7899b3cf1805a420330f0d2faf3#the-first-download

>Next, download the [native libraries](http://fna.flibitijibibo.com/archive/fnalibs.tar.bz2) and extract the archive.

Per the FAQ: That'll be [five dollars](https://github.com/sponsors/flibitijibibo)!
