### ISSUE TITLE
Newest release on FNA website has issues building 

### ISSUE THREAD

**Issue by Shadowblitz16** [FNA-XNA/FNA#341]
![image](https://user-images.githubusercontent.com/2453707/104112297-f2b39600-52a1-11eb-9d68-e8b14c2fa3ec.png)
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning		The file 'app.config' could not be added to the project.  Cannot add a link to the file C:\Users\Shadowblitz16\Downloads\FNA-2101\FNA\app.config. This file is within the project directory tree.	FNA			
```

this a newly unzipped fna download opened in visual studio 2019

**Comment by flibitijibibo** [comment]
The project hasn't changed in a really long time:

https://github.com/FNA-XNA/FNA/commits/master/FNA.csproj

msbuild comes out clean so you're looking at a Visual Studio issue.
