### ISSUE TITLE
Cannot convert from 'string' to 'System.IntPtr'

### ISSUE THREAD

**Issue by broxen** [FNA-XNA/FNA#347]
This line is giving me two build errors on VSCode with C# Plugin v1.23.9 powered by OmniSharp. It's not clear to me if this is the compiler being picky, but an explicit conversion does not seem to resolve the issue.

https://github.com/FNA-XNA/FNA/blob/7a64a33b8b36ddddae46d02fd182714eab14aed9/src/FNAPlatform/SDL2_FNAPlatform.cs#L1472

## Output
```
/~/src/external/FNA/src/FNAPlatform/SDL2_FNAPlatform.cs(1472,28): error CS1503: Argument 1: cannot convert from 'string' to 'System.IntPtr' [/~/src/external/FNA/FNA.Core.csproj]
/~/src/external/FNA/src/FNAPlatform/SDL2_FNAPlatform.cs(1472,38): error CS1615: Argument 2 may not be passed with the 'out' keyword [/~/src/external/FNA/FNA.Core.csproj]
```

## Tool-chain Info
```
VSCode About
Version: 1.53.1
Commit: 5d424b828ada08e1eb9f95d6cb41120234ef57c7
Date: 2021-02-08T23:30:54.166Z
OS: Linux x64 5.10.7-100.fc32.x86_64
```

**Comment by flibitijibibo** [comment]
git submodule update

**Comment by broxen** [comment]
Thank you @flibitijibibo! That worked, but I had to add the recursive and init flags `git submodule update --init --recursive`
