### ISSUE TITLE
Steam Overlay turning into flickering triangles with some FNA titles

### ISSUE THREAD

**Issue by psy-q** [FNA-XNA/FNA#356]
I've observed this on Mesa 21.1.4 on an AMD RX580 as well as an ancient Intel HD2000-era iGPU:

![Screenshot_20210717_184945](https://user-images.githubusercontent.com/87557/126045395-b40309e2-b461-4657-a6a2-854bd5b147bb.png)

The overlay becomes a bizarre flickering mass of triangles and squares. It looks pretty wild, maybe I can get a video. It seems Terraria players have [seen this as well](https://forums.terraria.org/index.php?threads/steam-overlay-rendering-issues.104834/). I've tested the following titles:

  * Rogue Legacy
  * Streets of Rage 4
  * Full Metal Furies
  * Terraria
  * Escape Goat 2

They share FNA so I thought of reporting this here. Or is it maybe a Mesa issue?

**Comment by flibitijibibo** [comment]
I've been seeing this on Xwayland recently - I would say it's a Mesa issue but for all I know X is involved as well. I would file a report with them, we're compliant with both the OpenGL and Vulkan specifications so there's not a lot we can do about a proprietary overlay.

**Comment by psy-q** [comment]
Ah, thanks! I hadn't searched their issues when I reported, but seemingly the problem is in Steam Overlay?

https://gitlab.freedesktop.org/mesa/mesa/-/issues/4191

Curious that it only triggers for some titles. Closing here, in this case.

**Comment by flibitijibibo** [comment]
Yup, that would explain it - the overlay appears to violate spec regarding point sprites, we enable them all the time by default to replicate GL Core and Vulkan behavior. Using ES3 or updating FNA3D and using Vulkan would be a workaround until Valve fixes the overlay.
