### ISSUE TITLE
Is sample accurate looping for Ogg files with MediaPlayer/Song possible?

### ISSUE THREAD

**Issue by nickgravelyn** [FNA-XNA/FNA#360]
I'm upgrading Shipwreck to the latest FNA from a quite old version. From Git history the last time I updated FNA for Shipwreck was late August 2016 so... yeah. Thankfully pretty much everything works perfectly which is fantastic but our music system required a little work. Previously I was relying on the Vorbisfile C# bindings FNA used to have to get sample-accurate looping for my music. This Gist is the core of the code we used that interacted with Vorbisfile previously: https://gist.github.com/nickgravelyn/386b834fcc2a16e763d71f2bb9e36fb6

After upgrading Vorbisfile is gone so I moved over to using MediaPlayer and Song which can load up the Ogg files and play them, however there are noticeable gaps when the songs loop. Is there any way to get sample-accurate looping in FNA? From what I can tell the MediaPlayer class is actually handling the repeating and does so using time instead of samples. There's a comment that seems to indicate the time was used to avoid stair stepping when using samples to derive the time.

Curious for thoughts on whether it's possible to modify MediaPlayer and/or FAudio to support this. Otherwise I'll probably just go build Vorbisfile myself to include the game to keep using our old music code.

**Comment by flibitijibibo** [comment]
XNA Song doesn't guarantee smooth loops as far as I know, so I would definitely take the old Vorbisfile.cs (and dllmap bindings!) and include it in the main project.

**Comment by nickgravelyn** [comment]
Yeah that's what I thought. Old XNA Song was not great for looping (in this way) so that makes sense. I'll bring over the old code myself. Thanks!
