### ISSUE TITLE
Where I can learn FNA ?

### ISSUE THREAD

**Issue by Watynecc** [FNA-XNA/FNA#364]
Hi I'm actually a beginner how started programming with C# I wonder if I can use this Framwork for making my Frist game 🎯

**Comment by flibitijibibo** [comment]
In general, no - we actually recommend learning C# before using FNA: https://gist.github.com/flibitijibibo/1ce4b7899b3cf1805a420330f0d2faf3#before-you-start

**Comment by flibitijibibo** [comment]
Pretty sure this has been answered...
