### ISSUE TITLE
GitHub's new authentication policy is preventing submodules from being fetched

### ISSUE THREAD

**Issue by TheSpydog** [FNA-XNA/FNA#373]
Attempting to run `git submodule update` or a fresh `git clone --recursive` now results in a slew of these types of error messages:
```
fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
Unable to fetch in submodule path 'lib/FAudio'; trying to directly fetch 1677bfdc0cccf0682b0c2997001f0ab6eee9f020:
```
Which is weird since the submodules were explicitly updated back in November to use https:// instead of git://, so I'm not sure what's happening here.

**Comment by flibitijibibo** [comment]
I guess we need to file a report somewhere? As long as .gitmodules is accurate I'm not sure what's happening here. I wasn't able to reproduce this on any of the lab boxes.

**Comment by thatcosmonaut** [comment]
I can't reproduce this either.

**Comment by TheSpydog** [comment]
Nevermind, it looks like I just screwed something up locally. Apologies for the false alarm.
