### ISSUE TITLE
Outdated Metal reference in wiki

### ISSUE THREAD

**Issue by thatcosmonaut** [FNA-XNA/FNA#374]
This page still mentions Metal as a force driver option: https://github.com/FNA-XNA/FNA/wiki/7:-FNA-Environment-Variables#fna3d_force_driver

**Comment by TheSpydog** [comment]
On a similar note, the [FNA3D_MOJOSHADER_PROFILE](https://github.com/FNA-XNA/FNA/wiki/7:-FNA-Environment-Variables#fna3d_mojoshader_profile) section also mentions metal, and doesn't mention spirv or hlsl.

**Comment by flibitijibibo** [comment]
Fixed both. HLSL probably won't be mentioned unless we add a DXBC emitter.
