### ISSUE TITLE
Please put binary file on nuget.

### ISSUE THREAD

**Issue by Qiu233** [FNA-XNA/FNA#380]
When I installed FNA from nuget(in visual studio), it actually downloaded and referenced the source instead binary files(.dll).
Then every time I try to build the project, vs(csc) keeps showing a lot warnings and messages about code quality, making debugging harder.
So is it possible to put compiled binarys on nuget?

**Comment by flibitijibibo** [comment]
[No.](https://github.com/FNA-XNA/FNA/wiki/0:-FAQ#where-is-the-nuget-package)

**Comment by ryancheung** [comment]
Try [this](https://github.com/FNA-NET/FNA)
