### ISSUE TITLE
There seems to be artefacts when SpriteBatch.DrawText is called with non-integer y

### ISSUE THREAD

**Issue by rds1983** [FNA-XNA/FNA#391]
See attached sample.
It draws "Search" twice: first time with y=97.5f(left on the image), second with y=97(right).
There seems to be an artefact in the first call - letters 'r' and 'h' are somewhat elevated:
![image](https://user-images.githubusercontent.com/1057289/174469576-cae975da-3ddd-4c6e-81f9-8d3afb057fd6.png)
[FNATest.zip](https://github.com/FNA-XNA/FNA/files/8934893/FNATest.zip)

**Comment by flibitijibibo** [comment]
That doesn't sound far off for SpriteFont. Here's the routine:

https://github.com/FNA-XNA/FNA/blob/master/src/Graphics/SpriteBatch.cs#L933

Depending on the sampler state it probably does not handle fractions all that well, it might not be consistent across hardware either!

**Comment by rds1983** [comment]
After more research I found that it's not related to the SpriteFont, but managed to reproduce the problem using only SpriteBatch(new sample is attached).
And, yes, the problem is somehow relates to using `SamplerState.PointClamp`.
![image](https://user-images.githubusercontent.com/1057289/184584486-3acd0d75-cc67-42ce-9dc9-d42b98efa182.png)

[FNATest2.zip](https://github.com/FNA-XNA/FNA/files/9335353/FNATest2.zip)

**Comment by flibitijibibo** [comment]
That about confirms it then - this is what I would expect a quad to do when rendered with non-integer coordinates and nearest-neighbor filtering; the system has to interpolate between texels and nearest-neighbor's results are going to be pretty nasty. The vertex data won't be rounded anywhere, but ultimately the fragment stage has to make a choice and it usually isn't pretty no matter which pixel it chooses for that fragment. This can be verified with apitrace and RenderDoc, across all three supported APIs.
