### ISSUE TITLE
DriverID & VendorID props

### ISSUE THREAD

**Issue by andreakarasho** [FNA-XNA/FNA#404]
Hi, what's missing to get these 2 properties available?

https://github.com/FNA-XNA/FNA/blob/master/src/Graphics/GraphicsAdapter.cs#L47
https://github.com/FNA-XNA/FNA/blob/master/src/Graphics/GraphicsAdapter.cs#L125

**Comment by TheSpydog** [comment]
The only way to get this information would be to add functions to FNA3D for fetching the various Driver/Vendor/Revision/SubSys properties via GL/DXGI/VK queries, but even then I'm not sure their results will be consistent, or match the values from XNA.

What's your intended use case for these values?

Should also mention that the XNA docs explicitly warn that [these members should be used with caution](https://learn.microsoft.com/en-us/previous-versions/windows/xna/bb199687(v=xnagamestudio.40)), so it's probably best to avoid these anyway.
