### ISSUE TITLE
Please expand on advice in Appendix D - Content Pipeline

### ISSUE THREAD

**Issue by dsaf** [FNA-XNA/FNA#405]
[Appendix D: MonoGame Compatibility - Content Compatibility - Content Pipeline
](https://github.com/FNA-XNA/FNA/wiki/Appendix-D:-MonoGame-Compatibility) says:

> You are STRONGLY encouraged to **develop your own content tools**, as they will be simpler, easier to use, more specialized and optimized, and **will probably take a few days to make**, unlike an XNA-like pipeline which would probably take years to complete.

Would it be possible please to help noobs like me with a few pieces of advice and/or links and/or samples on how to go about that? I understand that "a few days" is probably a bit hyperbolic, but I like the idea of something custom and simple that would enable loading basic sprite sheets and sounds.

**Comment by TheSpydog** [comment]
Loading basic sprite sheets is as simple as plopping the images into a `Content/` directory, then using `Content.Load<Texture2D>("MySpriteSheet")` to load it in. Audio is similarly straightforward -- `Content.Load<SoundEffect>("MySoundEffect")`.

The [FNA From Scratch tutorial](https://gist.github.com/flibitijibibo/1ce4b7899b3cf1805a420330f0d2faf3) goes through some examples of this stuff.

**Comment by dsaf** [comment]
Thank you! I did not manage to find that tutorial myself - much appreciated.

What do content pipelines from real well-known shipped projects tend to do on top of that? Bridge the gap between artists' output and usable game assets? For example, I see that Celeste guys are combining multiple source sprites into an atlas: https://github.com/chevyray/crunch

What about loading performance? Is there some target well-known format that is both compressed and fast to load?

**Comment by thatcosmonaut** [comment]
"Content pipeline" can mean a few things but usually it's a process of transforming artist-friendly assets into code-friendly assets. Discussing all the nuances of this process is very intentionally outside the scope of this project but would be an appropriate topic for our Discord channel: https://discord.gg/fna-xna

**Comment by dsaf** [comment]
Sounds good.
