### ISSUE TITLE
Problem with 3d graphics rendering 

### ISSUE THREAD

**Issue by theranix** [FNA-XNA/FNA#409]
Hi, I was trying to port my big game project from xna to fna according to instruction. As a test I copied all the content xnb's and didn't do any code changes. Everything is ok - game is loading, ui and input is working etc. but 3d graphics is not displayed excepting the sky.

It seems like everything was discarded. All parameteres coming to effect are correct. Most of shaders are ps_3_0 and vs_3_0.

Are there any ideas what could go wrong and what to do with it?

**Comment by flibitijibibo** [comment]
A common thing I run into is struct packing - be sure any IVertexType values have a Pack attribute in addition to StructLayout.Sequential. (It usually wants Pack = 1)

Aside from that, RenderDoc is good for capturing D3D11/Vulkan/GL frames, it should be possible to step through each draw to see what isn't working.

**Comment by theranix** [comment]
Thanks for answer! I checked RenderDoc - It's turned out that behavior of cleaning rendertraget is a bit different.
I used to clean most of targets by ClearOptions.DepthBuffer. But it leads to have no data after rendering in my case

**Comment by flibitijibibo** [comment]
If you have a test case we can look at we can try to fix it - I would expect OpenGL to be correct (pass /GLDevice:OpenGL as an arg) but maybe D3D11/Vulkan need adjustments.

**Comment by theranix** [comment]
It's D3D11, I will collect more information and return back

**Comment by flibitijibibo** [comment]
Just in case, here's the FNA3D function: https://github.com/FNA-XNA/FNA3D/blob/master/src/FNA3D_Driver_D3D11.c#L1623

**Comment by theranix** [comment]
Solution was easy - depth value coming to Clear should not be more than Viewport.MaxDepth. Xna allowed to do this so I haven't changed anything. But It leads to problem only when multiplie render target is used.

Other problems I faced with: 
- VFACE need to inverted
- Sampler_state parameter AddressU / AddressW setted to wrap in some cases can behave like "clamp" when I use different Effect's and apply pixel shader pass earlier then vertex shader pass. It's seems to be not right to apply passes in such order but it's strange why sometimes it works and sometimes it doesn't
- Window can change size without any reason and behavior of border mode is not stable. I will collect more information of what's going on
