### ISSUE TITLE
Can initial data improve performance of textures loading 

### ISSUE THREAD

**Issue by theranix** [FNA-XNA/FNA#413]
There is "pInitialData" parameter in ID3D11Device::CreateTexture2D. Can it significantly improve performance if data passed here instead of calling D3D11_SetTextureData2D?

**Comment by flibitijibibo** [comment]
For the type of device we create I don't think so - it was something I looked at when we were OpenGL only and the extra call to TexSubImage2D didn't seem to make a real difference. Plus, for Vulkan and SDL_gpu we pretty much have to do it like this anyhow.
