### ISSUE TITLE
Setting RenderTarget makes the screen violet

### ISSUE THREAD

**Issue by rds1983** [FNA-XNA/FNA#419]
See attached sample.
It has very simple code:
```c#
		protected override void LoadContent()
		{
			base.LoadContent();

			_renderTarget2D = new RenderTarget2D(GraphicsDevice, 1024, 1024);
		}

		protected override void Draw(GameTime gameTime)
		{
			GraphicsDevice.Clear(Color.Black);

			// TODO: Add your drawing code here
			GraphicsDevice.SetRenderTarget(_renderTarget2D);
			GraphicsDevice.SetRenderTarget(null);

			base.Draw(gameTime);
		}
```

It makes the screen violet.
![image](https://user-images.githubusercontent.com/1057289/231284636-561ea9c2-4b73-4f5b-abeb-759fa0508198.png)

Reproducible on the latest FNA with the latest native binaries.

[FNATest3.zip](https://github.com/FNA-XNA/FNA/files/11204828/FNATest3.zip)

**Comment by flibitijibibo** [comment]
RenderTargetUsage applies to the backbuffer as well; PreparingDeviceSettings will allow you to configure the target usage via the PresentationParameters:

https://github.com/FNA-XNA/FNA/blob/49031b77c41c742350f9c0950e7a638b2295a4e8/src/Graphics/PresentationParameters.cs#L137
