### ISSUE TITLE
AL lib: (EE) alc_cleanup: 1 device not closed

### ISSUE THREAD

**Issue by oldteen** [FNA-XNA/FNA#42]
Hello,

When I start (key F5) my project from VisualStudio more than 6 or 7 times this error appears in the output window :
- AL lib: (EE) alc_cleanup: 1 device not closed
And my project take 2 ou 3 seconds to close

Before these 6 or 7 times, no message, no delay to exit.
If I quit VisualStudio and restart it, no message and no delay for 6 or 7 times again.

I searched on google, many info about libgdx or minecraft :)
I certainly forgot something.
My project and FNA are compiled in 32 bits.
If I switch to monogame, I don't have this problem (others but not this one). But I don't want to switch to monogame for win/linux/osx.

To exit my project, I call the function Exit() from the FNA class Game

Any idea ? Need more information ? I will try to help.

Thank you in advance,
Have a good day,
-Thierry

**Comment by flibitijibibo** [comment]
Be sure to Dispose the game as well. That said, that message is actually something that should be done on program exit anyway:

https://github.com/FNA-XNA/FNA/blob/master/src/Audio/AudioDevice.cs#L86
https://github.com/FNA-XNA/FNA/blob/master/src/Audio/AudioDevice.cs#L99

I would try to break on program exit and see if you can get traces of what's happening after you've Disposed the game. There's a good chance that the hang is something else, as AL tends to catch device leaks pretty well.

**Comment by oldteen** [comment]
argggggg :) Three months that I hesitate to ask this question. :)

You are right. I dispose all my resources (textures, sounds, ...) but not the game.
Seems to work.

Thanks a lot!
