### ISSUE TITLE
[Streets of Rage 4] No sound.

### ISSUE THREAD

**Issue by trinukso** [FNA-XNA/FNA#425]
Heroic Launcher (flatpak version) GOG version of the game. No sound in the game. Thanks.

[log.txt](https://github.com/FNA-XNA/FNA/files/12207441/log.txt)

**Comment by flibitijibibo** [comment]
Looks like this is Wwise:

> INFO: CAkSinkSDL2::Init(): Unknown channel configuration: 3

I can deploy a fix for this at some point (check the game's Linux README for contact info) but the easiest fix is to set SDL_AUDIO_CHANNELS=2 as an environment variable when launching this game.

**Comment by trinukso** [comment]
> Looks like this is Wwise:
> 
> > INFO: CAkSinkSDL2::Init(): Unknown channel configuration: 3
> 
> I can deploy a fix for this at some point (check the game's Linux README for contact info) but the easiest fix is to set SDL_AUDIO_CHANNELS=2 as an environment variable when launching this game.

Now works. Thanks!
