### ISSUE TITLE
Status on console support?

### ISSUE THREAD

**Issue by markusstephanides** [FNA-XNA/FNA#428]
Hi! Just wanted to know how PS5 support is coming along? I have seen that it will use NativeAOT so I'm really curious on how it will work.

**Comment by TheSpydog** [comment]
Hey, PS5 support is still a work in progress, but I can’t say much more than that due to NDAs. If you’re a registered Sony developer, feel free to ping any of the mods in the FNA Discord and we’ll keep you in the loop.
