### ISSUE TITLE
2. Download Native Libraries

### ISSUE THREAD

**Issue by ct14it** [FNA-XNA/FNA#43]
- Visual Studio 2015 Community Edition
- Windows 10 64 Bit

Hi, I'm sorry if this is really obvious but I am struggling with this step.

I've downloaded the native libraries, but what do I actually do with them?

Instinctively I thought I would need to add a reference to them, but I get the `a reference to DLL could not be added` error message.

Any hints?

Thanks

**Comment by flibitijibibo** [comment]
Native libraries are not the same as managed libraries. When making C# projects you're creating and referencing managed libraries, whereas the native libraries are accessed by `[DllImport]` functions at runtime. These libs are accessed internally by FNA, so you won't need to explicitly link to them, but you will need to copy them to the output directory and to the final packages for Windows/Mac/Linux.

**Comment by ct14it** [comment]
Ahh OK, so they don't get bundled up, but they will need to reside with the exe file (or in system32) like any other DLL?

**Comment by flibitijibibo** [comment]
Yup! For Linux/Mac they go in slightly different locations, but I'm sure you get the idea:

https://github.com/FNA-XNA/FNA/wiki/3:-Distributing-FNA-Games

**Comment by ct14it** [comment]
Brilliant, thank you for your stupidly quick response!

**Comment by flibitijibibo** [comment]
No problem, let me know if you run into any trouble packaging all this at the end.
