### ISSUE TITLE
Can i use FNA on GNU/Linux with .NET Core?

### ISSUE THREAD

**Issue by Ambijubi** [FNA-XNA/FNA#431]

**Comment by flibitijibibo** [comment]
These are the supported environments:

https://github.com/FNA-XNA/FNA/wiki/0:-FAQ#what-development-environments-are-supported

Work is underway to support Visual Studio Code on Fedora to target Mono/.NET Framework.

We do not recommend Core at this time for desktop development:

https://github.com/FNA-XNA/FNA/wiki/0:-FAQ#i-have-a-bug-when-running-on-net-core-and-

Be sure to read the wiki for details, especially this block here:

https://github.com/FNA-XNA/FNA/wiki/0:-FAQ#what-happens-if-i-ask-a-question-thats-answered-in-this-wiki

**Comment by Ambijubi** [comment]
well, fna is not for me, im kali linux(debian) user ;(

**Comment by Ambijubi** [comment]
_Be sure to read the wiki for details, especially this block here:

https://github.com/FNA-XNA/FNA/wiki/0:-FAQ#what-happens-if-i-ask-a-question-thats-answered-in-this-wiki

That'll be [five dollars](https://github.com/sponsors/flibitijibibo/). No, this isn't a joke. Expect a link to the sponsors page for each of your requests._
oh crap, i dont have money, im 13 years old.💀💀 💀💀💀💀

**Comment by flibitijibibo** [comment]
Fair enough! But yeah, there may be a way to get MonoDevelop up and running over there but I don't think anyone on our team has experience with Kali. If vscode ever gets a flatpak that might make things more consistent everywhere, I hope... Definitely subscribe to the vscode issue in the FAQ for updates on support for that environment.
