### ISSUE TITLE
Can't load video

### ISSUE THREAD

**Issue by mthaier** [FNA-XNA/FNA#433]
![iss1](https://github.com/FNA-XNA/FNA/assets/70210166/e5f45f42-41b8-465c-b90a-160e4856f35d)

Script(Btw, it's from your 2b tutorial):
```

using System;
using System.Runtime.InteropServices;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Media;

class FNAGame : Game {
    [STAThread]
    public static void Main(string[] args) {
        using (FNAGame g = new FNAGame ()) {
            g.Run();
        }
    }

    private GraphicsDeviceManager gdm;
    private Video vid;

    private FNAGame() {
        gdm = new GraphicsDeviceManager(this);
        //Content
        Content.RootDirectory = "Content";
    }

    protected override void LoadContent() {
        vid = Content.Load<Video>("Frac");
    }
    protected override void UnloadContent() {
        vid = null;
    }

    
    protected override void Update(GameTime gameTime) {
        base.Update(gameTime);
    }

    Vector3 c = new Vector3(0,0,0);
    protected override void Draw(GameTime gameTime) {
        GraphicsDevice.Clear(new Color(c));

        base.Draw(gameTime);
    }
}
```

**Comment by TheSpydog** [comment]
What's the video file you're trying to play? Is it in Ogg Theora format?

**Comment by itsMohammedThaier** [comment]
@TheSpydog  yes
![image](https://github.com/FNA-XNA/FNA/assets/70210166/c0a17662-d652-4dd2-a6fb-88e0212ada41)

**Comment by TheSpydog** [comment]
Can you share the video file you’re using so we can take a look at it? Alternatively, you’re welcome to debug the [Theorafile library]( https://github.com/FNA-XNA/Theorafile ) yourself using mixed mode debugging (use the visualc/ solution to build it from source).

**Comment by TheSpydog** [comment]
Since this works with our test cases, there's not much we can do about this issue without a sample video to look at. Feel free to reopen this if you can throw a bogus ogv file our way.
