### ISSUE TITLE
SetEnvironmentVariable has no effect on Linux with .NET Core

### ISSUE THREAD

**Issue by Chicken-Bones** [FNA-XNA/FNA#435]
Apparently a well known compatibility issue with .NET and `getenv`. SDL can only see the environment of the process when it was loaded, and not any managed changes.

This makes all the calls to `Environment.SetEnvironmentVariable` which set variables for `FNA3D_` or `SDL_` ineffective on Linux with .NET Core.

Remedy is to use `SDL_SetHintWithPriority(..., SDL_HINT_OVERRIDE)`

Note that this issue does *not* affect Mono.

Test code:
```cs
SDL2.SDL.SDL_GetVersion(out var ver);
Console.WriteLine($"SDL Version {ver.major}.{ver.minor}.{ver.patch}");

Console.WriteLine("GetHint(SDL_VIDEODRIVER): " + SDL2.SDL.SDL_GetHint("SDL_VIDEODRIVER"));

Console.WriteLine("SetEnvironmentVariable(SDL_VIDEODRIVER, proc)");
Environment.SetEnvironmentVariable("SDL_VIDEODRIVER", "proc");

Console.WriteLine("GetHint(SDL_VIDEODRIVER): " + SDL2.SDL.SDL_GetHint("SDL_VIDEODRIVER"));

Console.WriteLine("SDL_SetHintWithPriority(SDL_VIDEODRIVER, ovr, SDL_HINT_OVERRIDE)");
SDL2.SDL.SDL_SetHintWithPriority("SDL_VIDEODRIVER", "ovr", SDL2.SDL.SDL_HintPriority.SDL_HINT_OVERRIDE);

Console.WriteLine("GetHint(SDL_VIDEODRIVER): " + SDL2.SDL.SDL_GetHint("SDL_VIDEODRIVER"));
```

Expected output, running with `SDL_VIDEODRIVER=env ...`
```
SDL Version 2.28.2
GetHint(SDL_VIDEODRIVER): env
SetEnvironmentVariable(SDL_VIDEODRIVER, proc)
GetHint(SDL_VIDEODRIVER): proc
SDL_SetHintWithPriority(SDL_VIDEODRIVER, ovr, SDL_HINT_OVERRIDE)
GetHint(SDL_VIDEODRIVER): ovr
```

.NET Core output
```
SDL Version 2.28.2
GetHint(SDL_VIDEODRIVER): env
SetEnvironmentVariable(SDL_VIDEODRIVER, proc)
GetHint(SDL_VIDEODRIVER): env
SDL_SetHintWithPriority(SDL_VIDEODRIVER, ovr, SDL_HINT_OVERRIDE)
GetHint(SDL_VIDEODRIVER): ovr
```

**Comment by flibitijibibo** [comment]
Is there any plan to fix this on .NET's end? If not, I guess we'll just add this to the FAQ...

**Comment by Chicken-Bones** [comment]
Won't fix https://github.com/dotnet/runtime/issues/9529

**Comment by flibitijibibo** [comment]
I've added this to the FAQ for the .NET Core question. Once #437 is in that'll be about all we can do until we can find a way to streamline patching the runtime like we do for MonoKickstart.

**Comment by flibitijibibo** [comment]
Updated the wiki's environment variable page as well.
