### ISSUE TITLE
Port working FNA game to XBOX/UWP

### ISSUE THREAD

**Issue by Jacques4v7W** [FNA-XNA/FNA#436]
Dear FNA developers

Firstly, I want to say you guys seem to be doing great work thus far with this reimplementation of XNA 4.0, and I would really appreciate help in porting my game to the XBOX store, since it is already on the Microsoft Store.

In addition, I have read through this brief guide here: https://github.com/FNA-XNA/FNA/wiki/Appendix-B:-FNA-on-Consoles , and it seems to have changed from UWP to GDM in the last view hours or I have visited another version of the page somehow, but things I have done so far:

- Added XInput controller mappings,
- Created a Blank UWP Project,
- Deleted the XAML files,
- Designated my game as the entry point,
- Made the changes to the Main method by adding the Pre-Processor definitions for UWP,
- Enabled developer mode for our XBOX One,
- Added our XBOX to my Partner Centre and added my account as an allowed tester,

Furthermore, things I am still struggling with:

- The SDL2.SDL.SDL_WinRTRunApp(mainFunction, IntPtr.Zero) was giving some sort of type error, so
- I started trying to read into how to build UWP versions of the DLLs from the master branch, but
- Not all of the projects contain a "visual-winrt" or "visual-gdk" folder (not sure if I should use winrt or gdk) and the requirement versions of the SDK or other times of .NET differ somewhat drastically between the different projects, even though I open them separately.
- Moreover, I am using Visual Studio 2019 but I do not have an option to install .NET 7 (except if it refers to .NET 4.7?), also it seems as if UWP uses an older .NET framework. This is problematic, because the Appendix B article states that .NET 7 should be used.
- The SDL2 project is called SDL2-CS when downloading from the Masterbranch and also compiles to four SDL2-CS.dll's and libtheorafile is called theorafile.

I know this probably seems like "noob-y" questions, but I couldn't derive enough information from the articles to come to a solution and I really want to try and develop more games with FNA and also if you want to list my first FNA Game on your website, it is called "Waste Escape" on the Microsoft PC Store and I did mention your Licences in my Privacy Policy.

If I make enough profit from the game(s) at some point I would like to try and make a partial donation. I hope you can give me some guidance as I am not as advanced as you guys.

Kind regards,
Jacques

**Comment by flibitijibibo** [comment]
Can confirm we've been on GDK since ~January 2023, and we deprecated UWP support at around the same time. If you have a GDK agreement with Microsoft we can get you access to the NativeAOT-GDKX repo which has everything needed to set up GDK projects.

Happy to hear about more FNA games, the only requirement we have for adding games to the site is that a native Linux version must be available to customers.

**Comment by Jacques4v7W** [comment]
> Can confirm we've been on GDK since ~January 2023, and we deprecated UWP support at around the same time. If you have a GDK agreement with Microsoft we can get you access to the NativeAOT-GDKX repo which has everything needed to set up GDK projects.
> 
> Happy to hear about more FNA games, the only requirement we have for adding games to the site is that a native Linux version must be available to customers.

Thank you for your response Ethan, I am not sure if I have a GDK agreement with Microsoft, but I did register as a Developer with them in July; in addition, it seems that I was able to enable the XBOX Live Creators Program for my game yesterday.

Does the NativeAOT-GDKX repo contain a private branch for easier access to GDK versions of the DLL's? If so should I email them at ID@XBOX to request permission? I am not currently concerned about adding leaderboards or cloud syncing, I just want to get it working on XBOX and allow people to save their High Score locally (currently it saves to Environment APPDATA on PC).

Furthermore, I will consider a native Linux port at a later stage if it is showing some success, I will want to experiment with Steam and GOG, maybe Epic after getting the XBOX Port to work.

**Comment by flibitijibibo** [comment]
Definitely get in touch with the ID@Xbox team to get a GDK agreement (and definitely do it soon, getting the agreement takes _forever_). NativeAOT-GDKX is essentially the base solution that builds dotnet, the FNA native libraries, and the bootstrapping system that runs the AOT-ified game.

Since the agreement takes a while to come in, once you filed the request with Microsoft definitely take a look at the other available platforms - you will have a _lot_ of time between now and then the agreement is finally drafted and ready to sign.

**Comment by Jacques4v7W** [comment]
Thank you for your input Ethan, I will take note to contact ID@Xbox tomorrow ZA-time for the GDK Agreement, but I would like to ask if it is possible to port the game to XBOX in the meantime without NativeAOT by building the libraries? Or do you only support it now through NativeAOT?

The reason I am asking, is because I want to try an XBOX Port first, since I suspect I will have to pay sign-up fees for platforms like Steam, GOG, etc. as well, and since I am already a registered Microsoft Developer, I thought the XBOX Store would be more popular than the PC Counterpart.

**Comment by flibitijibibo** [comment]
Building the Xbox binaries requires the GDK to be installed, so at the moment there's not much that can be done - you can inspect the visualc-gdk folders at SDL, FNA3D, FAudio, and Theorafile if you'd like, but they won't build without GDK. Likewise, the NativeAOT bootstrapper also requires GDK. Currently you can only get the Xbox GDK via private downloads from Microsoft themselves, but once that's installed the Xbox port is as simple as cloning our NativeAOT repo and following the README to hook the game up to the bootstrapper.

Aside from that, what's on the public documentation is about all I can say due to the usual console NDAs. For testing a console-like experience, we've found that the Steam Deck Verified process at least gets the basics right, so that may be a good starting point for doing a "console port", which can then be compiled against GDK later.

**Comment by Jacques4v7W** [comment]
Hi Ethan, so I have no emailed the Partner Centre Representative for help, because the application for ID@Xbox requires a business account, and I only have a personal account for indie development.

In contradiction, I do seem to currently be on the Creators Program, but I suppose this will not give me access to NativeAOT-GDKX.. The creators program states that one can release games to the XBOX- and PC- store through UWP, but I understand you have ended support for UWP.

I do not know what to try now, as I have already registered my banking details, tax, etc. to my personal development account. Furthermore, I guess I will start reading up about how to get access to Steam for Development as I have been a valuable customer on Steam, but I do not own a Steam Deck unfortunately. Do you know if the appxupload files one packages for the Microsoft Store will work for uploading to Steam as well?

**Comment by Jacques4v7W** [comment]
Sorry I did not intend to close the thread.

**Comment by Jacques4v7W** [comment]
The funny thing is my game worked for the most part when I used your native FNA libraries in my new UWP Project, I just got some strange errors after closing the game and the splash screen was in the way on start-up.

In addition, the game didn't seem to write my High Scores anymore, but I do have exception handling to prevent crashes due to file writing; furthermore, I simply made my game the "Entry Point" and I think, I already deleted the XAML files at that stage.

**Comment by Jacques4v7W** [comment]
Hi again Ethan,

So I seem to have gotten the game running in UWP by figuring out how to build all the native libraries correctly, because on of the readme's described where I should download the actual SDL2 project from, which is currently here: https://github.com/libsdl-org/SDL/releases/tag/release-2.28.3 , so figuring this out seemed to help a lot.

In contradiction, I have a new issue which is that I was leveraging on the scenario that FNA seems to support SuperSampling by default for PC x64, and therefore I could render my game in 4K and it would SuperSample back to my Desktop resolution 1920x1080p, but now with the working UWP DLL's it is forcibly rendering 4K and therefore I only see quarter of the screen.

In addition, I am already using two different "Scalar constant floats" to calculate texture detail for resolutions below 1080p and above 1080p to allow me to render my Textures in appropriate details down to 720p and up to 2160p; therefore, I would please like to ask if there is a way to re-enable this "SuperSampling down to Desktop resolution" by a FLAG or something without making drastic coding changes.

Furthermore, I have to try and apply your recommended "Mouse Fix for UWP" in the mean-time.

Kind regards
Jacques

**Comment by flibitijibibo** [comment]
The viewport sounds more like a bug than a feature - the D3D11 renderer hasn't really changed so it wouldn't surprise me if the swapchain was broken again on UWP (see lib/FNA3D/src/FNA3D_Driver_D3D11.c and grep "regression"). My guess is, there's something wrong with the DXGI swapchain.

UWP's habit of regressing, especially now that it's effectively EOL, is a big reason why we're not supporting it and getting all of our developers on GDK instead.

**Comment by Jacques4v7W** [comment]
Please forgive me for being a bit slow to catch on, I have only done slight graphics programming in the past and I vaguely remember about the frame-buffer, back-buffer for VSync, etc. I believe what you are saying, but I think it can still be valuable to leave a "backdoor" to UWP for FNA as it currently seems to be, because from articles I read the whole day Microsoft is confirming that UWP backwards compatibility is present on XBOX Series S|X systems (we only have a base XBOX One); in addition, Microsoft is referring to UWP continuously on the Creators Program pages from the Partner Centre.

So if I understand correctly, you think the bug is related within the DirectX11 renderer for UWP and not in the Desktop Fullscreen mode? Furthermore, is there now way for me to recreate the SuperSampling effect through a borderless fullscreen mode, etc.? Because adjusting my variable scalars will not completely resolve the issue, resolutions such as 1366x768 & 1360x768 and 4:3 resolutions will now become problematic for me to adjust to because (1366 / 1600 * 900 = 768.375; my internal resolution is 1600x900).

**Comment by flibitijibibo** [comment]
Microsoft definitely likes saying things, but the reality is very different: While UWP apps will _technically_ run, that's largely coincidental - we had an incident where an Xbox OS update broke UWP's DXGI implementation, and rather than fix the regression, they _delisted all the affected games without notifying the partners_, and the FNA community had to scramble to find a workaround and get the games up on the store. These were ID@Xbox titles as well, which you would _think_ would get more attention, but this was not the case.

Creator's Club is treated pretty much like XBLIG where it gets absolutely buried in the UI, giving it no discoverability whatsoever, so we encourage ID@Xbox to make it so people can actually find the game on the store, in addition to having our development toolchain not cause titles to get silently delisted.

There might be a way to fix this, but I definitely won't be looking for it, since UWP support is scheduled for removal in FNA 24.01.

**Comment by Jacques4v7W** [comment]
Thank you for your response Ethan, yes I definitely understand the frustration of big companies not caring at all about what they break; for example, I have experienced this with AMD removing DirectX9 Unreal Engine 3 optimizations with the release of 17.7.2 due to negligence.

I do not expect you to fix it in the FNA source code, I am just trying to understand how the Desktop version achieves the resizing of the backbuffer resolution back down to the Window/Desktop resolution, and which functions/properties I should try to set to achieve the same result. I have tried reading up about the RenderTargets a few weeks ago, but it was problematic due to messing up my Mouse Coordinates, but by using Fullscreen mode without render targets the Coordinates works perfectly for all resolutions.

Is DXGI not resizing the Backbuffer properly? Because, you seem to be calling resizing functions in the C file you mentioned with Pointers.

**Comment by flibitijibibo** [comment]
The best place to look at the swapchain behavior is via FNA3D: https://github.com/FNA-XNA/FNA3D/blob/master/src/FNA3D_Driver_D3D11.c

For the most part we just keep the swapchain size matching the window size, and if the "backbuffer" size in the presentation parameters is different we make an intermediate render target that gets blit at the very end. WinRT is a little different in that we had to actively cache the window dimensions to keep the swapchain size sane, but if the viewport is broken again then it would indicate a problem with the swapchain detection. You will want to see what ResizeBuffers is doing and see if there's a way to adjust based on that; aside from that I don't really know how this would be addressed.

**Comment by Jacques4v7W** [comment]
I really appreciate your input thus far Ethan, I will try do understand some of the C source, but my assumption from what you are describing is that you guys are doing the "Super-Sampling" in your D3D11.c file and I do not see myself being able to recreate it in C#.

What I mean by this, is there was literally nice anti-aliasing applied due to Super-Sampling with your handling of the Resizing and I can see that by temporarily adjusting my Scalar variable for this new issue, 1080p now fits but is more pixelated than my non-UWP version.

May I ask if the Viewport is disconnected from the Backbuffer in that the Viewport represents the Desktop size? Maybe if I try adjusting the Viewport size to my Backbuffer size it will recreate the resizing, I will have to read-up again.

**Comment by Jacques4v7W** [comment]
A few things I have noticed thus far:

- Starting the game in Windowed mode allows proper resizing, but in a very small Window,
- User can stretch Window even when "this.Window.AllowUserResizing = false" and immediately causes the Swapchain to stop scaling,
- I cannot edit the sizes for Windowed mode, even though I thought I did it the other day and PreferredBackbuffer does not seem to affect the UWP Window.

**Comment by Jacques4v7W** [comment]
Hi, hope you guys are doing well. I would just like to add that:
- I tried a RenderTarget again and it seems to cause serious performance issues with SuperSampling/DownSampling, so
- I am currently adusting my Scalar which results in rendering, in proper native resolution in fullscreen-mode for now, therefore everything fits except for 1024x768 and 1366x768 causing slight miscalculations, probably due to the float being truncated to an int which I will test,
- The mouse causes a strange artefact midway through a level which it never did before, this is after applying the "resource mouse fix" on the old UWP page,
- Strangely, even though IsBorderlessEXT doesn't seem to support being a set property in your Desktop- or UWP- code, it worked in my Desktop version of my game, but here the mouse always causes the border to display when moving the mouse-only (not gamepad) to the upper border of the screen which I do not know how to fix.

**Comment by Jacques4v7W** [comment]
I was now able to install my Game on our XBOX One and it works, but it is clipping the borders..

**Comment by flibitijibibo** [comment]
There are only so many different ways to say this and I'm going to be out of the office today, so I'm going to be as clear as possible without getting out the bullhorn:

UWP is bitrotted and will not work _at all_ starting December 2, 2023. You need to _stop what you are doing_ and re-think your plan for how and where you ship your game. Do the starting paperwork for GDK, and while that is pending you are going to make a Win32, non-UWP build that is deployable on Windows and Linux _at minimum_, and can be deployed to Steam and itch.io, all of which can and will possible to do given how long the paperwork takes. The wiki provides the details necessary to do this.

If you use UWP, _your project is doomed_ and no expertise from anyone in the FNA community can save you. UWP is _done_ and you are burning money by working on it.

**Comment by Jacques4v7W** [comment]
I did not mean to be a nuance Ethan, and I appreciate your input. I understood when you initially mentioned UWP should be avoided, and I did contact Microsoft but I am still waiting for them to respond.

Please understand, I am not able to currently sign-up for ID@Xbox as I am not a business owner; moreover, I was initially attracted by your Home-page advertisement of FNA with XBOX Support without mentioning getting access to GDK first. In addition, I did contact GOG Galaxy for the possibility of porting my game there as well, because Steam and Epic is currently too expensive with the 100USD launch-price.

If it works out, I was thinking about doing the other ports you mentioned as well.

Have a good day Ethan, and thank you for some of the hints.

**Comment by nkrapivin** [comment]
Hi all, thought I'd drop by,

Just wanted to mention that the ID@Xbox program gives two free complimentary development kits to their first-time partners (this is public info). You can absolutely join ID after you've joined their UWP dev activation thing.
And depending on your country you might be able to register as a Sole Trader which is much less paperwork and hassle than owning an LLC/LLP.
There's also a Discord server that you can join if you want to discuss the public side of ID https://discord.gg/idatxbox it has Microsoft employees which can help you get in touch with the right people.

**Comment by Jacques4v7W** [comment]
> Hi all, thought I'd drop by,
> 
> Just wanted to mention that the ID@Xbox program gives two free complimentary development kits to their first-time partners (this is public info). You can absolutely join ID after you've joined their UWP dev activation thing. And depending on your country you might be able to register as a Sole Trader which is much less paperwork and hassle than owning an LLC/LLP. There's also a Discord server that you can join if you want to discuss the public side of ID https://discord.gg/idatxbox it has Microsoft employees which can help you get in touch with the right people.

Hi @nkrapivin , thanks a lot for sharing this information, I did not see anything of the complimentary kits, but this is good to hear. When I started registering it immediately asked my business name.

Furthermore, when I registered as a Microsoft Developer I had to fill in a lot of forms and a tax treaty, but they still take a cut (which I do not mind too much as the affordable sign-up fee justifies it).

I will try it again later, as I do hope not too much adjustments have to be made for GDK, at the moment I assume the same guidance steps will be followed as UWP, but with less issues.

Kind regards
Jacques

**Comment by flibitijibibo** [comment]
> Hi all, thought I'd drop by,
> 
> Just wanted to mention that the ID@Xbox program gives two free complimentary development kits to their first-time partners (this is public info). You can absolutely join ID after you've joined their UWP dev activation thing. And depending on your country you might be able to register as a Sole Trader which is much less paperwork and hassle than owning an LLC/LLP. There's also a Discord server that you can join if you want to discuss the public side of ID https://discord.gg/idatxbox it has Microsoft employees which can help you get in touch with the right people.

Thanks, will add this to the wiki - expect this to be added within the next 12 hours or so! This should help reduce the gap between Creator's Program and ID, which so far seems to be the biggest blocker that's keeping devs on UWP.

(I can maybe also figure out a way to connect these Discord communities together to streamline getting access to our GDKX channel, but that'll come later...)

Thanks again for all the details, and sorry for all the red tape involved!
