### ISSUE TITLE
Terraria - Memory leaks with Vulkan renderer

### ISSUE THREAD

**Issue by HunterCZ122** [FNA-XNA/FNA#443]
Sorry for an amateurish issue.
Playing for about an hour with Vulkan renderer results in high CPU usage and memory leaks, resulting in lock up until OOM killer kicks in and kills Terraria. It doesn't happen with OpenGL renderer at all.
![Screenshot_20231007_225513](https://github.com/FNA-XNA/FNA/assets/23011428/4bab4ba9-f262-4e84-88c6-9a6abdae58f6)
I haven't tried replacing FNA with a newer version.
Driver is proprietary Nvidia 535.43.10
Also, is there a way to enable logs and detect FNA version used in Terraria? Just to make report more useful.

**Comment by flibitijibibo** [comment]
I would update FNA3D first, then update FNA.dll with a debug version if FNA3D doesn't fix it. It could be video memory fragmention or it could be a leak, which newer versions are better at pointing out.

**Comment by HunterCZ122** [comment]
Played for about 2 hours with a friend and half an hour solo on updated FNA3D, no leaks or suspicious increase of memory usage (game stays at 1GB usage as it should). Reverting to Terraria's FNA3D version makes it obvious after few minutes it leaks memory slowly. So I guess Re-Logic will need to update FNA3D.

**Comment by flibitijibibo** [comment]
Next time I'm in a room with them I'll let them know, but definitely report on your findings as well to make sure they see it!
