### ISSUE TITLE
Fn

### ISSUE THREAD

**Issue by panorb** [FNA-XNA/FNA#447]

**Comment by flibitijibibo** [comment]
![image](https://github.com/FNA-XNA/FNA/assets/1396814/a59e0136-8a40-451a-8da9-d127821e7072)

**Comment by panorb** [comment]
Hey, sorry about that. I actually wanted to search If you suggest any particular TrueType Font Implementation here, but my fat fingers hit the create issue button instead. GitHub Mobile is... definetely not ideal. It is way to easy to create an issue on accident. Sorry again.
