### ISSUE TITLE
Incorrect Wiki instructions: Chapter 5 Creating New Projects

### ISSUE THREAD

**Issue by fabtjar** [FNA-XNA/FNA#468]
https://github.com/FNA-XNA/FNA/wiki/1:-Setting-Up-FNA#chapter-5-creating-new-projects

> `dotnet new console YourProjectName` to create an empty project

Should be `dotnet new console --name YourProjectName`.

**Comment by flibitijibibo** [comment]
Fixed, thanks for the report!
