### ISSUE TITLE
ReadBackbuffer GL_INVALID_OPERATION

### ISSUE THREAD

**Issue by jeffphilp** [FNA-XNA/FNA#47]
When calling `GraphicsDevice.GetBackBufferData(...)` a GL_INVALID_OPERATION error is generated in DebugCallback handler of OpenGLDevice_GL.cs.

The console output for reference is as follows:
```
GREMEDY_string_marker not supported!
IGLDevice: OpenGLDevice
OpenGL Device: GeForce GTX TITAN X/PCIe/SSE2
OpenGL Driver: 4.5.0 NVIDIA 368.81
OpenGL Vendor: NVIDIA Corporation
MojoShader Profile: glsl120
Using EXT_swap_control_tear VSync!
EXT_swap_control_tear unsupported. Fall back to standard VSync.
GL_INVALID_OPERATION error generated. FBO anti-alias method is not valid for read pixels.
	Source: GL_DEBUG_SOURCE_API_ARB
	Type: GL_DEBUG_TYPE_ERROR_ARB
	Severity: GL_DEBUG_SEVERITY_HIGH_ARB
```

The method call inside OpenGLDevice.cs which is causing the DebugCallback to be triggered is 
```
glReadPixels(
    x,
    y,
    w,
    h,
    GLenum.GL_RGBA,
    GLenum.GL_UNSIGNED_BYTE,
    data
);
```
on lines 3062 - 3070.

The cause of this invalid operation seems to occur when multi-sampling is enabled, as per this page https://www.opengl.org/wiki/GL_EXT_framebuffer_multisample you are unable to use glReadPixels to read a multisampled buffer.

I tested it with multisampling disabled and the error does not occur.  

I am happy to help out where I can with any fixes, or further investigation but I was after some feedback from those more knowledgeable than myself.

Thanks in advance for any assistance.

**Comment by flibitijibibo** [comment]
Should be fixed, but I only have confidence in this since it works similar to the backbuffer blit on SwapBuffers:

https://github.com/FNA-XNA/FNA/commit/9cb33dd35b2d758eb133e6d65e89cd3ca595bd31

(On a personal note, can reports like this come slightly sooner than hours before an FNA release...?)
