### ISSUE TITLE
VertexPositionColorNormalTexture

### ISSUE THREAD

**Issue by balt-dev** [FNA-XNA/FNA#473]
[As seen here, there's an extra IVertexType implementor in XNA not implemented here.](https://docs.monogame.net/api/Microsoft.Xna.Framework.Graphics.VertexPositionColorNormalTexture.html)
Maybe we could get this in FNA?

**Comment by balt-dev** [comment]
(note: i very well may be stupid here)

**Comment by flibitijibibo** [comment]
We would have to add an EXT suffix would would probably defeat the purpose - I would statically link to that type (it's one file, I bet) when using FNA.

**Comment by balt-dev** [comment]
ah, i see
