### ISSUE TITLE
Unable to load FBX 

### ISSUE THREAD

**Issue by ghost** [FNA-XNA/FNA#48]
Hello

I tried to load a simple FBX but it can't find the file? I get a ('System.IO.FileNotFoundException')

Is this a bug or i'm missing something?

```
            mModel = Content.Load<Model>("Ship");
```

Here is the FBX i used:  http://rbwhitaker.wikidot.com/local--files/model-library/SimpleShip.zip

**Comment by Scellow** [comment]
And if i add the extension .fbx i get the following error:

```
An unhandled exception of type 'Microsoft.Xna.Framework.Content.ContentLoadException' occurred in FNA.dll

Additional information: Could not load Ship.fbx asset!
```

Looks like it's not even supporte internally

```c#
				if (typeof(T) == typeof(Texture2D) || typeof(T) == typeof(Texture))
				{
					Texture2D texture = Texture2D.FromStream(
						graphicsDeviceService.GraphicsDevice,
						stream
					);
					texture.Name = assetName;
					result = texture;
				}
				else if ((typeof(T) == typeof(SoundEffect)))
				{
					result = SoundEffect.FromStream(stream);
				}
				else if ((typeof(T) == typeof(Effect)))
				{
					byte[] data = new byte[stream.Length];
					stream.Read(data, 0, (int) stream.Length);
					result = new Effect(graphicsDeviceService.GraphicsDevice, data);
				}
				else if ((typeof(T) == typeof(Song)))
				{
					// FIXME: Not using the stream! -flibit
					result = new Song(modifiedAssetName);
				}
				else if ((typeof(T) == typeof(Video)))
				{
					// FIXME: Not using the stream! -flibit
					result = new Video(modifiedAssetName, graphicsDeviceService.GraphicsDevice);
				}
				else
				{
					stream.Close();
					throw new ContentLoadException("Could not load " + assetName + " asset!");
				}
```

no mention of Model type :/

**Comment by flibitijibibo** [comment]
We can't read raw FBX files, they need to be compressed by the XNA content pipeline.

**Comment by Scellow** [comment]
Oh that sucks :/

**Comment by flibitijibibo** [comment]
Yeah. Feel free to write your own reader though, I think the MGCB has a parser for it.

**Comment by Alan-FGR** [comment]
FBX support is no easy problem to solve. Official SDK isn't permissive and assimp doesn't support it very well. There's OpenFBX these days, it's usable but relatively young. Not sure what MGCB use.

**Comment by flibitijibibo** [comment]
If someone wants to come up with `Model.FromStreamEXT` I'd be willing to merge it, but you have a few requirements:

- Must be permissive (so yeah, SDK is out)
- Must support the very old 2006.11 format, per the [XNA specification](https://msdn.microsoft.com/en-us/library/bb447762.aspx)
- Must not add any new DLLs, or must load the new DLL dynamically with Assembly.Load (so if we add assimp that's how we'll integrate it)

MGCB may have something we can use, but our goal needs to be to contribute to existing model loading code and simply push that through the equivalent of XNA's ModelProcessor. In doing this, we may be able to add other formats as well (obj and the like).

**Comment by carlos-ferreira** [comment]
I read [here](https://digitalrune.github.io/DigitalRune-Documentation/html/6cc96ddc-4127-4ec7-889a-19cb71af0d3d.htm) that MonoGame uses [assimp](https://github.com/assimp/assimp) to import FBX files. There's even a [3D model viewer](https://github.com/acgessler/open3mod) that uses assimp to load 3d models.

Is this something we could use or integrate on FNA ?

**Comment by thatcosmonaut** [comment]
At this point in time we have absolutely no interest in supporting an official path for model loading. You are more than welcome to pull a library into your project to handle this.
