### ISSUE TITLE
Add extension method for loading mipmap texture from stream

### ISSUE THREAD

**Issue by tomcashman** [FNA-XNA/FNA#481]
We're working on a project that relies heavily on mipmaps and would like to have access to a variation of FromStream that can load mipmaps.

`public static Texture2D FromStream(GraphicsDevice graphicsDevice, Stream stream)`

I propose adding an extension method

`public static Texture2D FromStreamEXT(GraphicsDevice graphicsDevice, Stream stream, bool mipMap)`

**Comment by flibitijibibo** [comment]
Does DDSFromStreamEXT handle this? AFAIK it's the only format that natively supports mip levels.

**Comment by tomcashman** [comment]
Looks like it would. We'd need to change our asset pipeline. Is there a recommended way to generate DDS files?

**Comment by flibitijibibo** [comment]
I'm aware of the [NVIDIA Texture Tools](https://developer.nvidia.com/nvidia-texture-tools-exporter), but most image editors have an exporter for DDS - for an automated solution it may be enough to throw together a quick DDS spewer, as the format is a small header followed by byte chunks with lengths prepended:

- https://github.com/FNA-XNA/FNA/blob/master/src/Graphics/Texture.cs#L263
- https://github.com/FNA-XNA/FNA/blob/master/src/Graphics/Texture2D.cs#L532

(This is also a good place to compress the texture data to DXT5/BC7, if VRAM usage becomes an issue)
