### ISSUE TITLE
[BUG] Can't download clone the Wiki

### ISSUE THREAD

**Issue by milen-prg** [FNA-XNA/FNA#484]
Windows 11 Pro 64bit

C:\Users\User\Downloads>git clone https://github.com/FNA-XNA/FNA.wiki.git

Cloning into 'FNA.wiki'...
remote: Enumerating objects: 1574, done.
remote: Total 1574 (delta 0), reused 0 (delta 0), pack-reused 1574Receiving objects:  94% (1480/1574

Resolving deltas: 100% (1026/1026), done.
error: invalid path '0:-FAQ.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

---
This:

git config core.protectNTFS false
git config hooks.enforcecompatiblefilenames false

do not help.

**Comment by flibitijibibo** [comment]
We ended up moving this to a new GitHub page: https://fna-xna.github.io/docs/

Repo is now here: https://github.com/FNA-XNA/docs
