### ISSUE TITLE
FLAC and WAV support for music?

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [FNA-XNA/FNA#492]
I know that Touhou uses WAV files as music.

**Comment by flibitijibibo** [comment]
For WAV it can either be loaded all at once in SoundEffect though that probably uses too much memory.

All other formats can use any standard decoder and pass the PCM to a DynamicSoundEffectInstance.

**Comment by H-A-M-G-E-R** [comment]
I think FLAC/WAV can be streamed from disk with less CPU cycles than Vorbis.
Proof: https://phoboslab.org/log/2023/02/qoa-time-domain-audio-compression

**Comment by flibitijibibo** [comment]
QOA is fine too - Vorbis is mostly for disk size, for FNA's purposes it was chosen to replace XNA MediaPlayer's format which is WMA. You can pick any format you want, we'll read PCM either way.

**Comment by flibitijibibo** [comment]
Think I answered this - short version: Use whatever you want and pass the decoded samples to DynamicSoundEffectInstance.
