### ISSUE TITLE
<TargetFrameworks> should be <TargetFramework> (no 's') when using FNA.Core

### ISSUE THREAD

**Issue by NecroseN** [FNA-XNA/FNA#493]
In the FNA.Core.csproj file, under \<PropertyGroup>

\<TargetFrameworks> should be changed to \<TargetFramework> (singular version without 's') since it is only targeting one framework (net8.0)

As well, the bookend should be \</TargetFramework>

In the current state, when running the publish command, the attached error will occur.
![PublishError](https://github.com/user-attachments/assets/a367fda1-86d1-4036-8759-cc66bf396855)

**Comment by flibitijibibo** [comment]
https://github.com/FNA-XNA/FNA/commit/db16bf91f86935f9f7ef8b667fb5399b26035843
