### ISSUE TITLE
errors where building project

### ISSUE THREAD

**Issue by Qwertcool54** [FNA-XNA/FNA#499]
![1](https://github.com/user-attachments/assets/ff58bb14-8951-43a8-9678-43eb60df2f2b)
when i trying building project, i got this errors:
The type or namespace name 'xna' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
The type or namespace name 'Game' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'Game' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'GraphicsDeviceManager' could not be found (are you missing a using directive or an assembly reference?)
} expected

**Comment by Keithcat1** [comment]
I think that instead of using Microsoft.Xna.Framework, you have to use Fna.Framework? Not sure but give it a try

**Comment by flibitijibibo** [comment]
Looks like this was a capitalization thing... and a missing brace, and probably some other stuff too. Check the error logs carefully!
