### ISSUE TITLE
Steam Overlay not working on OS X

### ISSUE THREAD

**Issue by connorshea** [FNA-XNA/FNA#5]
OS X 10.11.2

Tested with:
- Rogue Legacy
- FEZ (tested with Stable and 1.11 [MonoGame] branch)
- Terraria
- Dust: An Elysian Tail
- Apotheon

I'm pretty sure it's not a problem on my side, as the Overlay works in non-FNA games, e.g. Hotline Miami 2, Dustforce, Guacamelee, Team Fortress 2, and Counter-Strike: Global Offensive.

Also tested on the Steam Beta as well as the Steam stable client, occurs with both.

I'm not sure how I can best help you debug this, would you like my Console dumps?

**Comment by connorshea** [comment]
The issue also effects Transistor, it looks like. Could be an issue carried over from MonoGame, or one caused by SDL2?

**Comment by flibitijibibo** [comment]
Eversion has this problem too, so I think it's SDL2. I can't fix this, Valve has to fix it.

**Comment by connorshea** [comment]
Just found a file named `libsdl2-2.0.so.0` in CSGO, but the Overlay works for that. I'm guessing this is an Overlay problem, not an SDL one, but is that worth forwarding on to the SDL team?

**Comment by flibitijibibo** [comment]
I would forward it to Sam, as he has a view of both SDL and Valve's stuff internally.

**Comment by flibitijibibo** [comment]
I should also point out that the overlay worked at one point but has stopped working for games that are still on old FNA versions that were built before this problem started, so the regression is definitely in the overlay.

**Comment by connorshea** [comment]
How would you recommend I contact Sam?

**Comment by flibitijibibo** [comment]
Message slouken@libsdl.org

**Comment by connorshea** [comment]
Awesome, thank you :)

**Comment by flibitijibibo** [comment]
I think we figured it out... the overlay doesn't work when launching from a shell script. This affects Valve's games as well!

**Comment by connorshea** [comment]
Per Alfred at Valve:

This sounds like the apple issue with their shell now stripping the `DYLD_INSERT_LIBRARIES` environment variable, which we use to inject our overlay. We also set a `STEAM_DYLD_INSERT_LIBRARIES` environment variable to help work around this design choice, in any launch shell script your game(s) have you could add this line to fix it:
 
`DYLD_INSERT_LIBRARIES=$( STEAM_DYLD_INSERT_LIBRARIES)`

**Comment by flibitijibibo** [comment]
Ah okay, so this is more along the lines of MonoKickstart rather than FNA anyway, if you want to not call it an Apple bug...

Fuck me that's going to be a lot of updating for nothing.

**Comment by connorshea** [comment]
As an Apple user, sorry :(

**Comment by flibitijibibo** [comment]
This doesn't appear to work anymore! Has this been replaced with something? I still see it in the scripts for Valve games, but the variable is empty now...

**Comment by connorshea** [comment]
God damn it Apple....
