### ISSUE TITLE
Build option to separate out primitive objects into a separate assembly

### ISSUE THREAD

**Issue by eropple** [FNA-XNA/FNA#51]
Hey there! Thanks for all the hard work on FNA, I recently discovered it and after spending time studying the source I'm really appreciative that you've done this in an open-source manner.

So one of the persistent issues that I run into when using any of the XNA family of libraries is that I often have a core, logic-only library that doesn't have any dependency on any of the graphics, audio, etc. stuff in the game part of the gizmo. That core library could really use a lot of the primitives in FNA to avoid some gross marshaling back and forth between framework-independent types and the FNA ones. What I'm thinking (and this is something that I'd be willing to take on) is a build option that creates an `FNA.Primitives.dll` or something that contains those data structures and builds an FNA assembly that depends on it. That primitives library could be used in that kind of corelib (and thus, transitively, in a game server or even a web application that consumes that corelib), while plugging in straight away with a correctly built version of FNA proper.

Thoughts?

**Comment by LavenderMoon** [comment]
Something I've always wished for when working with XNA and MonoGame.

**Comment by flibitijibibo** [comment]
I'll be honest: I could _barely_ read the second half of the OP without getting lost. It sounds like an extremely overcomplicated design change to the build process for... Something? I'm actually still not 100% clear on what separating the sources  has to do with just not using things like Graphics in a server binary. As far as I know it's perfectly feasible to only use the math types with FNA.dll with nothinng else.

**Comment by eropple** [comment]
You're right in that the math types can be selectively used from the normal assembly. The problem with that approach is that FNA transitively includes its dependencies when it's used at any point, regardless of whether the underlying native libraries are actually called. This sort of dependency is both socially and technically problematic with a lot of projects I've worked on in the past and will in the future (the difficulty of wrestling MonoGame into a sane build process is a big part of why I'm digging into FNA right now while I have some time); pulling in MojoShader-CS et al. into a web server raises a lot of red flags for the development groups I've worked with. It also increases code fragility in that it exposes to the consuming developer a lot of code that might invoke spooky action at a distance--ever-helpful IntelliSense suggesting semantically inappropriate classes and that sort of thing. Not super desirable.

I don't think this is a particularly large change via MSBuild given the feature changes since VS2015 (mirrored into MD/XS). I'll see if I can proof it as an example, though it might not be a quick turnaround.

**Comment by flibitijibibo** [comment]
Your problem appears to be with your editor and not actual code. My editor, for example, does not exhibit these problems. Blaming FNA seems like a weird strategy when editors much nicer than VS2015 exist!

From a code perspective, you're writing in C#; a couple extra DllImport functions is the least of your dependency problems. The only actual problem I've seen with colliding types is somewhat dealt with already by `using` when you need to specify exact types for two libraries sharing class/struct names. It's not pretty having to do ifdefs for this sort of thing, but doubling the size of the build process for myself and my partners, for so many games, is, as you put it, problematic.

I must also point out that part of exposing what we use internally in FNA is a matter of respect to my partners, in addition to its convenience (particularly the exposure of SDL2#). I am willing to trust that someone using my software is intelligent enough to do what's right in the end, even if it takes a slip-up or two over the years to figure it out. That also includes what I may not have foreseen as the correct thing back when I wrote it! Lots of excellent extensions to FNA have come from this mutual respect between FNA developers. I wouldn't think of changing that even for a second.

**Comment by eropple** [comment]
OK. Never mind, then.

**Comment by LavenderMoon** [comment]
> editors much nicer than VS2015 exist!

Could you name them? The "VS2015 + Resharper" combo is one of the main reasons I'm sticking to Windows 7 over FreeBSD.

> doubling the size of the build process

Wait, why would having one additional .dll with a very light amount of structs and classes double the size of the build process? Am I misunderstanding what would be needed?

**Comment by flibitijibibo** [comment]
It doubles the number of DLLs, and despite being a small amount of code, doubles the build time unless you're using 'make' (i.e. me and nobody else). If the builds could be parallel you might be able to mitigate that, but we're talking about chaining one library into two libraries that are coupled together anyway.

And I'm saying this next sentence unironically: I use vim and an extra terminal and it somehow manages to be better than 2015's editing environment. 2010 is probably the only editor since 6 that I haven't completely hated. Resharper is very nice, but not worth using VS if you can avoid it.
