### ISSUE TITLE
Cannot clone an Effect once it's been used

### ISSUE THREAD

**Issue by kg** [FNA-XNA/FNA#510]
There's no way to de-apply a Pass or a Technique once you've applied it, which results in this SDL assert if you try to clone an effect after using it:

![image](https://github.com/user-attachments/assets/4017c12e-c9c5-46d1-84f3-6a48fea6801d)

We either should clear this state variable before cloning (dangerous, since they could be doing something crazy like cloning during draw? I checked and I'm definitely not doing that), or maybe add an EXT method to deapply a pass so people like me can not hit this assert while debugging.

**Comment by flibitijibibo** [comment]
I think I'm going to end the extension system soon - it's very clearly sending people in the wrong direction when it comes to debugging and fixing issues, which isn't healthy for a project that's supposed to be about accuracy and stability over feature-richness.

The assert is here: https://github.com/icculus/mojoshader/blob/main/mojoshader_effects.c#L1540

What this means is my assumption about the pass being copied is probably wrong - we should ignore Begin/End state when cloning and initialize it as if it's a new effect altogether (which it kind of is, in a way).

**Comment by kg** [comment]
Sounds good to me. Should I just change it to initialize these members to -1 since the assert says that's the expected value?

**Comment by flibitijibibo** [comment]
Yeah, pretty much anything that gets used in Begin/BeginPass should be initialized with fresh values rather than the parent effect's current state.

**Comment by flibitijibibo** [comment]
Fixed in latest FNA3D
