### ISSUE TITLE
is there any setup instruction for mac osx users & how to use it

### ISSUE THREAD

**Issue by lewislepton** [FNA-XNA/FNA#52]
just as the title says, is there any setup instructions and use in mac osx?

thanks

**Comment by flibitijibibo** [comment]
I have no idea what your development environment looks like.

My best answer at this point can only be "yes."

**Comment by lewislepton** [comment]
well it would be using sublime text more than likely. then maybe using terminal to build etc. depending if sublime text could.

if xcode could be used, then i would of used that. i guess monogame/xamarin IDE is a choice as well.

but i guess it the setup etc that is more confusing on how to get going for mac. if visual studio was on mac, id use that and i think things would be fine then ;)

**Comment by flibitijibibo** [comment]
For terminal setups you can use either `xbuild` or `make`. You can also use MonoDevelop for building and using its debugger if you want, that's what I have to do sometimes if `mono --debug` and `mono --verbose` aren't enough. The project files you care about are the Makefile and FNA.csproj, which you can wire up to your game's project setup. The FNA.sln is mostly for show, to be honest.

**Comment by lewislepton** [comment]
cool thanks. ill give monodevelop a go
