### ISSUE TITLE
Program silently crashes after first call to SDL_Init

### ISSUE THREAD

**Issue by adamgryu** [FNA-XNA/FNA#53]
I'm not sure if this is the best place to ask this, but I've been having some trouble...

So, I was looking into porting one of my old XNA games to FNA. I believe I followed the setup instructions correctly. I placed the downloaded DLLs into the same folder the executable is run from. When I clicked run in VS, the program seemed to run but quit immediately without any errors. I noticed that after I commented out all of my game specific code, the game will run ONLY when I click on the built EXE from the File Explorer (it will show a blank screen with CornFlowerBlue). When I try to run it from VS, I can debug it until it reaches SDL_Init, after which, the program exits with exit code 1080890248 (0x406d1388).

I'm using Visual Studio 2010 Pro on Windows 10. Not sure how to debug this one. Do you have any tips?

**Comment by flibitijibibo** [comment]
Did you download SDL2 from fnalibs or the SDL website?

**Comment by flibitijibibo** [comment]
Nevermind, turns out a fix I wrote locally on my old Windows builder never made it into repo:

https://github.com/FNA-XNA/SDL-mirror/commit/8b406a8141a98ce7e8a217f5576e768d354d0c60

Redownload fnalibs and it should work again.
