### ISSUE TITLE
Missing matching SDL_FreeRW call for SDL_RWFromMem

### ISSUE THREAD

**Issue by elisee** [FNA-XNA/FNA#59]
Hi!

It looks like the structs allocated by the calls to `SDL_RWFromMem` in [`SDL2_FNAPlatform.TextureDataFromStream`](https://github.com/FNA-XNA/FNA/blob/17bc067f1f2bd140761e9abc3516474f10c01a0a/src/FNAPlatform/SDL2_FNAPlatform.cs#L1029) and [`SDL2_FNAPlatform.SavePNG`](https://github.com/FNA-XNA/FNA/blob/17bc067f1f2bd140761e9abc3516474f10c01a0a/src/FNAPlatform/SDL2_FNAPlatform.cs#L1239) are never freed.

 There's a [`SDL_RWclose` macro in SDL2](https://github.com/FNA-XNA/SDL-mirror/blob/9328b68368628ddc3272c0c27280e12c7116186d/include/SDL_rwops.h#L189) but all it does in the case of `SDL_RWFromMem` is [call `mem_close`](https://github.com/FNA-XNA/SDL-mirror/blob/8b406a8141a98ce7e8a217f5576e768d354d0c60/src/file/SDL_rwops.c#L599) which [has a null check and then calls `SDL_FreeRW`](https://github.com/FNA-XNA/SDL-mirror/blob/8b406a8141a98ce7e8a217f5576e768d354d0c60/src/file/SDL_rwops.c#L457).

I believe SDL2-CS is missing the `SDL_FreeRW` function though?

**Comment by flibitijibibo** [comment]
The RWops structs get freed by the calls that use them; i.e. IMG_Load_RW's extra '1' parameter indicates that the RWops is to be freed when the call is completed.

**Comment by elisee** [comment]
Ah. I should have known better than to doubt you :P. Nevermind then ^_^
