### ISSUE TITLE
SDL2 GameWindow and other platform code

### ISSUE THREAD

**Issue by WardBenjamin** [FNA-XNA/FNA#6]
Hey Flibit,

I am currently working on my own game framework from scratch, called [Flare](https://github.com/WardBenjamin/Flare.Framework) that has the goal of not only letting developers use (for example) sprites and text rendering as part of the engine but also exposing the raw OpenGL API if they want it.

Right now, I'm in the process of investigating a move to SDL2 rather than OpenTK for input and window handling. May I use your window handling and input bindings from FNA, of course under the appropriate licensing?

~Benjamin Ward

**Comment by flibitijibibo** [comment]
Use whatever you like from FNA, from the SDL2 folder to the IGL/IAL devices!

**Comment by WardBenjamin** [comment]
@flibitijibibo Thanks!
