### ISSUE TITLE
Mojoshader: NOT only allowed on predicate register

### ISSUE THREAD

**Issue by jeffphilp** [FNA-XNA/FNA#61]
Hi,

When working with a newly written shader which is compiled using the XNA effect compiler, the following error is generated when running it through MojoShaders testparse program:

Object #1: SHADER, technique 0, pass 0
    PROFILE: (null)
    Universal.fxb:2440: ERROR: NOT only allowed on predicate register

Which is caused by a fail call in mojoshader.c (https://github.com/flibitijibibo/MojoShader/blob/master/mojoshader.c#L9037).

I can find the documentation which is the basis for the check ( https://msdn.microsoft.com/en-us/library/windows/hardware/ff569716(v=vs.85).aspx ) however it would seem that the compiler is generating a NOT source modifier against a TEMP register.

If I change the check to allow either Predicate, or Temp source registers then the shader seems to run fine inside Mojoshader.  

What is the way to proceed with this in terms of getting a fix into Mojoshader? i.e. just submit a pull request, or do you want some further investigation done?

Cheers,
Jeff

**Comment by flibitijibibo** [comment]
Do you think it'd be possible to isolate the HLSL into a reproducible case for this? I'm definitely willing to believe that MSDN is wrong, but I wonder how easy it is to get there. For all I know it might be limited to certain shader model versions...

Let's play with this a little bit and after we understand it some more I'll write the fix in. Considering we have an OpenAL Soft updating happening soon this was actually a great time to patch MojoShader, since I'm dusting off the buildbots anyway :)

**Comment by jeffphilp** [comment]
Hi, no worries I'll have a play around and get it down to the smallest possible shader file I can.

**Comment by jeffphilp** [comment]
So I've stripped down the shader code to the smallest I can get it whilst it still fails `testparse`, the shader below wouldn't actually do anything useful, and I have replaced variables with existing variables or constants where possible to reduce its complexity.  

```
bool LightingPerPixel;
float4 DiffuseColor;

void VertexShaderFunction(
	inout float4 position : POSITION0,
	inout float3 normal : NORMAL0,
	inout float4 color : COLOR0)
{
	color *= DiffuseColor;
	if (!LightingPerPixel)
	{
		float temp1 = dot(position.xyz, normal);
		if (temp1 < 0)
		{
			float temp2 = dot(normalize(position.xyz), float3(0.1f, 0.1f, 0.1f));
			if (color.a > 0.0f)
			{
				float temp3 = pow(abs(temp2), 16);
				color.rgb += temp3;
			}
		}
	}
}

void PixelShaderFunction(inout float4 color : COLOR0)
{
}

technique Technique1
{
	pass Pass1
	{
		VertexShader = compile vs_3_0 VertexShaderFunction();
		PixelShader = compile ps_3_0 PixelShaderFunction();
	}
}
```

**Comment by flibitijibibo** [comment]
Excellent, thanks. I've CC'd Ryan, as he might have an idea as to where the check came from...

**Comment by flibitijibibo** [comment]
Actually, you know what this might be - I think he got the source/predicate mixed up. This check makes sense in that we should only get here for CONSTBOOL values, as the predicate register is a BOOL. So I think if you change that check to check for REG_TYPE_CONSTBOOL it should work just fine and still make sense.

**Comment by jeffphilp** [comment]
So I have tried your suggestion replacing `if (info-> != REG_TYPE_PREDICATE)` to `if (info-> != REG_TYPE_CONSTBOOL)` and it does allow this file to past the test and the other shaders too :).  Just found another shader issue though (with another new shader) which is not failing in Mojoshader but not rendering properly - so Ill have a dig into that to see where it is going wrong.

**Comment by flibitijibibo** [comment]
Cool - I don't have a test to see if PREDICATE was ever right, so I'll probably just `||` that in. Feel free to keep this issue open for the other boog though, since it's probably in the same neighborhood anyway.

**Comment by jeffphilp** [comment]
Wouldn't it be a `&&` ?

**Comment by flibitijibibo** [comment]
Er, yes. My mistake... This is me attempting to write code outside vim :P

**Comment by jeffphilp** [comment]
:) So with this other shader case I have a more complex case than the code which triggered the above issue (basically an Obj shader with specular and textures).  Any advice/suggested tools to help get to the bottom of the rendering differences? 
I can't see any preshader vm code,  so it must be somewhere in the translated glsl.  In which case I am presuming it involves decoding that and seeing where it differs.

**Comment by flibitijibibo** [comment]
This is what I usually do:

- With fxc.exe, compile the shader without piping it to a file with /Fo. Compare the asm output to the GLSL output from testparse, and make sure that the MojoShader output is actually the same as the compiler output.

- With apitrace (or something like it), trace to the bad rendering call, then look at the bound shaders and the uniform values to make sure that the uniforms actually align to what you'd expect.

- Step through the shader with the given uniform values. Open up an empty text file for notes here, because you're in for a ride at this step!

**Comment by jeffphilp** [comment]
I think this issue can be closed, if the above code change can be made to MojoShader. 

The issue with the textures not being lit at a distance, seems to be related to the generation of MipMaps at runtime and not MojoShaders parsing of shaders.  XNA doesn't support Mipmap generation at run time for textures, but it can be done using by drawing a loaded texture to a `RenderTarget2D` using `SpriteBatch` then reading the generated levels back into a `Texture2D` by using `RenderTarget2D.GetData` and `Texture2D.SetData`.  I'll need to keep digging to find out why this doesn't work in FNA.

**Comment by flibitijibibo** [comment]
@jeffphilp Might be able to diagnose right away: Before calling GetData(), call SetRenderTarget(null) (or set another target).

**Comment by jeffphilp** [comment]
@flibitijibibo I double checked and I am already doing that (code extract below).  I wonder if its related to OpenGLDevice.cs#ReadTargetIfApplicable where if the texture is bound it ignores the level argument.  Thought I haven't studied the code thoroughly enough to say that is actually a problem.

```
using (var stream = File.OpenRead(reader.TempPath))
{
    var xnaTexture = Texture2D.FromStream(m_graphicsDevice, stream, size.X, size.Y, true);
    var data = new Color[xnaTexture.Width * xnaTexture.Height];
    xnaTexture.GetData(data);
    xnaTexture.SetData(data.Select(c => c != colorKey ? c.ToPremultiplied() : Color.RawColors.Transparent).ToArray());

    if (generateMipMaps)
    {
        var renderTarget = new RenderTarget2D(m_graphicsDevice, xnaTexture.Width, xnaTexture.Height, true, xnaTexture.Format, DepthFormat.None);
        m_graphicsDevice.SetRenderTarget(renderTarget);
        m_graphicsDevice.Clear(Microsoft.Xna.Framework.Color.Transparent);
        m_spriteBatch.Begin();
        m_spriteBatch.Draw(xnaTexture, Vector2.Zero, Microsoft.Xna.Framework.Color.White);
        m_spriteBatch.End();
        m_graphicsDevice.SetRenderTarget(null);
        xnaTexture.Dispose();
        xnaTexture = new Texture2D(m_graphicsDevice, xnaTexture.Width, xnaTexture.Height, true, xnaTexture.Format);
        var levelSize = new SizeXY(xnaTexture.Width, xnaTexture.Height);
        for (var i = 0; i < xnaTexture.LevelCount; ++i)
        {
            var dataSize = levelSize.X * levelSize.Y;
            renderTarget.GetData(i, null, data, 0, dataSize);
            xnaTexture.SetData(i, null, data, 0, dataSize);
            levelSize = SizeXY.Max(levelSize / 2, SizeXY.One);
        }
        renderTarget.Dispose();
    }
    return new XnaTexture2D(xnaTexture);
}
```

**Comment by flibitijibibo** [comment]
It almost certainly is - I imagine apitrace will show garbled texture data for all mip levels beside 0. If you fix that, it should work afterward.

**Comment by flibitijibibo** [comment]
https://github.com/FNA-XNA/FNA/commit/c6b94dcd067aa05967ba2ccb563d5da8cce643b2

**Comment by jeffphilp** [comment]
https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/OpenGLDevice.cs#L2824
https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/OpenGLDevice.cs#L2836

Have hard coded 0 level values, if I try these with "level" put in place of "0" the data reads.

**Comment by flibitijibibo** [comment]
I like how I not only hardcoded it this whole time, but actually fixed it in ModernGLDevice only to not take that fix back to the OpenGLDevice. Anyway, lots of mipmap fixes!

https://github.com/FNA-XNA/FNA/commit/ee49365032d35ed11d3ab0b62fbf6bab9746438d

**Comment by jeffphilp** [comment]
@flibitijibibo Thank you for the quick turn around that works now!  I had been staring at the ASM output from FXC for the shader and was thoroughly relieved to find out it was something in the C#.

**Comment by flibitijibibo** [comment]
The change is now in fnalibs:

https://github.com/flibitijibibo/MojoShader/commit/0cee89a4b6487ea8a649fea46320d013f994996d
