### ISSUE TITLE
Vector2 == should not use epsilon check

### ISSUE THREAD

**Issue by TrevorSundberg** [FNA-XNA/FNA#66]
I know from experience that the best way to get your bugs solved is to be positive, so right off the bat, I love FNA!

Now to the point, XNA does not use epsilon checks when comparing Vectors (Equals and operator==), it uses the built in floating point equality which has a well defined behavior.

I know the reasoning behind floating point epsilons, however generally they should only be applied on a case by case basis, rather than a blanket over all floating point comparisons.

The current implementation causes unexpected behaviors, such as comparing a Vector2 initialized with Single.PositiveInfinity to compare incorrectly with itself (infinity comparison is well defined). Another example is if you were to use the Vector2 as a key in a Dictionary, the GetHashCode becomes inconsistent with the equality tests.

**Comment by flibitijibibo** [comment]
If you can fix these scenarios in a pull request with a test program to verify the accuracy I'll merge it. If you want this in 16.11 you'll want to do this in the next 6 hours.

**Comment by TrevorSundberg** [comment]
Oh boy I've never used git before, mostly an hg person. Here goes nothing!

**Comment by flibitijibibo** [comment]
Feel free to post a 'git diff' if that's easier than doing the whole process (it is kind of a lot...). Removing the Epsilon calls from the math stuff probably isn't worth all that anyway :P

(Also a part of me is glad to not use this anymore, it was mostly a Gendarme conformance feature but is only useful in scary parts like XACT internals...)

**Comment by TrevorSundberg** [comment]
It seems git isn't too different from hg. I created branch, committed. I then went to create a pull request but it states I don't have permission. Do pull requests need branch pushing permissions?

**Comment by TrevorSundberg** [comment]
Oh shoot seems I need to fork to do that... woops do over!

**Comment by flibitijibibo** [comment]
What you'll do is create a fork on GitHub, then 'git push -u https://github.com/TrevorSundberg/FNA' and then your fork will have a "Create Pull Request" button.

**Comment by flibitijibibo** [comment]
Before tagging 16.11 I did some more WithinEpsilon removals:

https://github.com/FNA-XNA/FNA/commit/624bd5065cc171cdf7b684e3c5b1f83700f42d90

Man, I'm really glad some of these are gone... looking at Matrix == in particular made me cringe a little.

**Comment by TrevorSundberg** [comment]
Good to know. I ported my game recently from XNA to FNA, and other than the comparison it worked perfectly! I still need to test hosting FNA in WPF as an HWNDHost for my editor though.
