### ISSUE TITLE
Polling SDL_Events

### ISSUE THREAD

**Issue by jsmars** [FNA-XNA/FNA#68]
I needed to access the windowevents from SDL for adding scaling and such when rescaling my game window, but it turns out they are all being polled from within the FNAPlatform and I can't find any way to access them without creating a custom OnEvent within Game. Am I missing something or is this something FNA should consider adding?

**Comment by flibitijibibo** [comment]
We do handle such window events internally, but if you want to get them as well you can use SDL_AddEventWatch or SDL_AddEventFilter, as we do to specially handle some Win32 events.

**Comment by jsmars** [comment]
If I use any of those, it doesn't catch all the events, and I get a bunch of threading errors because of they are run on a seperate thread.

> Additional information: A callback was made on a garbage collected delegate of type 'FNA!SDL2.SDL+SDL_EventFilter::Invoke'. 

Usage:
```
SDL.SDL_AddEventWatch(onEvent, i);

private unsafe int onEvent(IntPtr func, IntPtr evtPtr)
{
    SDL.SDL_Event* evt = (SDL.SDL_Event*)evtPtr;
    if (evt->type == SDL.SDL_EventType.SDL_WINDOWEVENT)
    {
        onWindowEvent(evt->window);
        return 0;
    }
    return 0;
}
```

**Comment by flibitijibibo** [comment]
As the error states, you need to store the event in a delegate variable first. Take a look at how we use it in SDL2_FNAPlatform to see how it's used in C#.

**Comment by jsmars** [comment]
I tried the same approach as you use in SDL_FNAPlatform as such

```
func = onWindowEvent;
if (true) // to try both of these
    SDL.SDL_SetEventFilter(onEvent, Marshal.GetFunctionPointerForDelegate(func));
else
    SDL.SDL_AddEventWatch(onEvent, Marshal.GetFunctionPointerForDelegate(func));
```


```
unsafe delegate void WindowEvent(SDL.SDL_WindowEvent we);
unsafe WindowEvent func;

private static unsafe int onEvent(IntPtr func, IntPtr evtPtr)
{
    SDL.SDL_Event* evt = (SDL.SDL_Event*)evtPtr;
    if (evt->type == SDL.SDL_EventType.SDL_WINDOWEVENT)
    {
        Marshal.GetDelegateForFunctionPointer(
            func,
            typeof(WindowEvent)
        ).DynamicInvoke(evt->window);
        return 0;
    }
    return 1;
}

private void onWindowEvent(SDL.SDL_WindowEvent wEvent)
{
    Ward.Log(wEvent.windowEvent.ToString());
    switch (wEvent.windowEvent)
    {
        case SDL.SDL_WindowEventID.SDL_WINDOWEVENT_RESIZED:
            ResolutionChanged();
            break;
    }
}
```

Using the SDL_SetEventFilter method doesn't capture any of the events, and using the SDL_AddEventWatch catches the events a while, but eventually crashes on the same error as above, but on the SDL_PollEvent call from FNAPlatform.

Is there something wrong with my implementation? I'm a bit rusty at unsafe code to be honest, and would rather see a more straightforward approach in FNA without having to use unsafe code if possible. Since the events are being polled from FNAPlatform, maybe add an easier to use functionality to FNAPlatform similar to this?

new delegate type:
`public delegate void SDLEvent(SDL_Event e);`

in Game:
`public SDLEvent OnSDLEvent { get; set; }`

In RunLoop() / PollEvents
`game.OnSDLEvent?.Invoke(evt);`

**Comment by flibitijibibo** [comment]
Maybe we can just skip this altogether... can I ask what events you even want? If it's just window resizes you can get Game.Window.ClientSizeChanged...

**Comment by jsmars** [comment]
I didn't even think of going that route. I was using minimized/maximized as well but I can really do without them by just combining with Game.IsActive if I just have the resizing event. I'm really sorry to have wasted your time on this. I was using the WindowsForm events for my XNA games and got stuck in trying to get the SDL events working in a similar way, but this is a much easier solution for my current situation. 

I'm not sure if there are any other vital events that may be used in other scenarios though where accessing the SDL events would be useful, but for now this solves my problem. Thanks!

**Comment by flibitijibibo** [comment]
Cool, we can revisit this later if needed.
