### ISSUE TITLE
MojoShader: Shader causes System.AccessViolationException

### ISSUE THREAD

**Issue by jsmars** [FNA-XNA/FNA#69]
I apologize for raising another issue so soon. I've been in the process of moving to FNA for the past days, most things have gone very smoothly but I've got a few issues I'm struggling with. I also found [another thread](https://github.com/flibitijibibo/FNA-MGHistory/issues/302) dealing with a similar issue, but it seems that has already been patched so I don't know how it can be related.

All my XNA4 shaders moved over to FNA without trouble except one. I wrote it a long time ago so it's a bit messy, so I could just go ahead and rewrite it and maybe my problems would be gone, but since the shader worked fine in XNA4 I'd rather know what it is doing wrong so I know what to avoid in the future when dealing with FNA and MojoShader.

I get the following exception on line 2042 in OpenGLDevices.cs when drawing with this shader:

> An unhandled exception of type 'System.AccessViolationException' occurred in FNA.dll
> 
> Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

It's a very basic skybox shader with clipping, [entire source here.](http://pastebin.com/3p1RGzf7)

**Comment by flibitijibibo** [comment]
My guess is that it's the attrib locations - what happens when you remove ClipDist and ClipPlaneEnable entirely and change TEXCOORD5 to NORMAL0?

**Comment by jsmars** [comment]
Ah yes, removing the use of TEXCOORD5 & TEXCOORD9 seems to have fixed the problem. What are the available attributes when using MojoShader? And are there any limitations to any of them? I know I used these high numbers before on XNA because of some unexpected results since some of the attribs are clamped or limited in some way.

**Comment by jsmars** [comment]
Hmm.. While all of my other shaders seem to work out of the box when, I'm going through my other shaders and noticing some differences.
In this one shader I was also sending some data in my vertex shader output, which also need to be assigned an attrib, so they were using the TEXCOORD5 and up. The shader rendered fine except that a lot of the functinality was missing. Changing this to NORMAL0 and up fixed these issues as well. I'd say this is quite a difference from XNA4 and possibly there should atleast be a mention of it somewhere, and preferebly a more detailed list of what the differences are.

**Comment by flibitijibibo** [comment]
Technically all the attribs should be available, but TEXCOORD gets some weird treatment because there's a built-in gl_TexCoord[] array that has slightly undefined behavior depending on the max coords per program:

https://github.com/flibitijibibo/MojoShader/blob/master/mojoshader.c#L2637

Ironically it probably works better when you enable GLES mode and we work around that missing builtin.

The best advice I can give is to try and use the attributes that semantically make the most sense, rather than just stacking on a single attribute. Since behavior can be different for both D3D and OpenGL it'll save you headaches no matter where you export!

**Comment by jsmars** [comment]
Thanks for the reference! Yeah I wish there was a clear list of what treatment different attribs go through. As mentioned XNA4 also treats the first few TEXCOORDs differently, but I haven't found a resource that explains how and why.

I'll try to look over my shaders and try to make their connections more logical, but sometimes I pass nonstandard data. For example lifetime for instances, textureID variations or clipping planes.

Once again thanks for all the help and great job on building FNA!

**Comment by flibitijibibo** [comment]
Cool, glad it was a quick diagnosis. Will close for now, but will make a separate issue regarding documentation for vertex attributes and a possible need to research more obscure D3D attribs like TEXCOORD5+.
