### ISSUE TITLE
JoyStick Support

### ISSUE THREAD

**Issue by SlowLogicBoy** [FNA-XNA/FNA#7]
As I can see there is no joystick support yet, do I need to add this myself?
Cause I can use GamePad, but no Joystick. 
Also there are no usages of SDL_EventType.SDL_JOYDEVICEADDED.

**Comment by flibitijibibo** [comment]
Do you have a use case where you only need joystick and not gamecontroller?

**Comment by SlowLogicBoy** [comment]
I don't think so

**Comment by flibitijibibo** [comment]
GameController already does this, pltease read the documentatian in full:

https://github.com/FNA-XNA/FNA/wiki/4:-FNA-and-Windows-API#directinput-support

**Comment by SlowLogicBoy** [comment]
Sorry and thank you
