### ISSUE TITLE
Game.IsFixedTimeStep defaults to false

### ISSUE THREAD

**Issue by jsmars** [FNA-XNA/FNA#71]
I noticed that in FNA `Game.IsFixedTimeStep` defaults to `false`, while in vanilla this defaults to `true`, and this could cause issues with some games. 

I guess it should be defaulted to true for XNA4 accuracy?

**Comment by CloudyHeart** [comment]
This caused me problems for a few hours the other day, and I meant to post an issue about it.

**Comment by flibitijibibo** [comment]
Turns out every game I've been updating since August 24 has had this set manually on startup, so it never got caught...

https://github.com/FNA-XNA/FNA/commit/972f7a09a10b7f01e43be941decb6adbca58e779

**Comment by flibitijibibo** [comment]
For amusement's sake: I've updated 10 games and 18 packages since that regression and _exactly_ 1 game and 2 packages were affected, and it was TowerFall 8-Player... pretty sure I never would have found this.
