### ISSUE TITLE
Weird issue on modern PC's - Not redrawing frames

### ISSUE THREAD

**Issue by LennardF1989** [FNA-XNA/FNA#72]
I have a peculiar case where my game decides to not re-render itself on very modern systems. It will draw just one frame, while the update-loop continues like normal. Only upon switching between windowed and full-screen mode, will it redraw a frame only to "hang" again.

I have no idea what might be causing this, or how I would even begin to debug this, since neither of my machines have this issue. So far it looks nVidia-related, so it might be a driver-issue.

Does this issue seem familiar to anyone? If so, did you manage to fix it and if so, how?

For some additional information, my game renders everything to a RenderTarget2D with PreserveContents, which it eventually draws on-screen with the SpriteBatch.

**Comment by LennardF1989** [comment]
The users themselves did some investigation and found out the game wasn't actually using their nVidia, but rather their integrated Intel graphics. Still I wonder what might cause this issue on lesser hardware.

**Comment by flibitijibibo** [comment]
Hybrid graphics drivers for integrated graphics are generally very poor and very outdated, since they're typically bound to the manufacturer's "custom" version rather than, for example, Intel's latest release. The only real way you can avoid this is to have the user make sure that it's using the dedicated GPU for your game in the graphics control panel.

**Comment by LennardF1989** [comment]
Yea, turned out to be only two users out of a few thousand who had this issue, one of which noticed the game was using the wrong GPU, the other magically fixed it by rebooting.

I don't think we should waste any more time on this, so I'll close it :)

Thanks @flibitijibibo!
