### ISSUE TITLE
[XACT] Pausing/Resuming a Category should perform the same action on SubCategories

### ISSUE THREAD

**Issue by kiates** [FNA-XNA/FNA#73]
While porting I noticed that my music wasn't pausing/resuming the same as in XNA.  I pause/resume a Global category of which my sound effects and music are in two subcategories.  Per XACT implementation this action should apply to any sub category as well.

I can provide a patch to address this.

**Comment by flibitijibibo** [comment]
So it's similar to the recent SetVolume fix then! Send a patch doing all that and I'll merge it in.

**Comment by kiates** [comment]
Yes, exactly!

**Comment by flibitijibibo** [comment]
Whuh forgot to close this
