### ISSUE TITLE
DynamicSoundEffectInstance.Play

### ISSUE THREAD

**Issue by LennardF1989** [FNA-XNA/FNA#74]
I have found another odd issue in the crashlogs I receive from my game:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
    at Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.Play(Boolean isManaged)
    at Microsoft.Xna.Framework.Media.Song.Play()
    at Microsoft.Xna.Framework.Media.MediaPlayer.PlaySong(Song song)
    at Microsoft.Xna.Framework.Media.MediaPlayer.Play(Song song)
```

I have investigated this and noticed that `AudioDevice.ALDevice` in there is null. Even after calling Initialize again when this is noticed, it will still be null afterwards.

When I forcefully disable sound inside `Initialize`, the game proceeds as normal with the `NullALDevice` without crashing, just no sound obviously. This leads me to believe the `CreateALDevice` fails.

I have already tested with the user by manually installing OpenAL on their system, that doesn't work. So I'll have to further investigate why instancing an `OpenALDevice` fails.

Is the device using anything in particular not all systems might support?

**Comment by flibitijibibo** [comment]
I can't think of any reason why OpenAL Soft would fail... see if kcat's version works for them:

http://kcat.strangesoft.net/openal-binaries/openal-soft-1.17.2-bin.zip

Is this user on WinXP maybe...?

**Comment by flibitijibibo** [comment]
To at least make the issue clearer I've added NAHE to the function:

https://github.com/FNA-XNA/FNA/commit/9919f72840dc7a10243171d4c07430888357fd82

Why there's no device found I don't know, but now it should present a real error and not just a crash.

**Comment by LennardF1989** [comment]
Perfect! I'm trying to plan a remote desktop session with this user to test out a few things, will report back my findings :)

**Comment by flibitijibibo** [comment]
Since this has more to do with no audio hardware being found rather than DSFI itself, I'm going to close this... feel free to use this thread to log what you find with their hardware setup though.
