### ISSUE TITLE
Various pitch related features are not working

### ISSUE THREAD

**Issue by kiates** [FNA-XNA/FNA#76]
It appears that the conversion from encoded pitch values (individual and ranges) is off by 10.  Encoded 12 semitones is 1200, however on reading these pitch values are divided by 1000, thus 1200 results in 1.2 instead of 12.

Additionally the OpenAL audio framework seems to need a scaled -1 to 1 range for +/- one octave, while XACT works with -12 to 12. Applying this conversion within the OpenAL wrapper corrects the mismatch.

One final observation is when calculating pitch variations at the Play wave level, the sound level should always be added regardless of whether add/replace was occurring at the play wave level.

**Comment by kiates** [comment]
I have a branch with the above corrections and will submit a pull request for your consideration.

**Comment by flibitijibibo** [comment]
https://github.com/FNA-XNA/FNA/commit/c6e964e4e2aa5d6197fafc7daa34d2debcb70ce8
