### ISSUE TITLE
What are the differences between FNA and MonoGame ?

### ISSUE THREAD

**Issue by beppe9000** [FNA-XNA/FNA#8]
How does this compare to MG? I am asking this because having two separate project to do the same thing is redundant - in my opinion - unless there are some substantial divergences between the two.

I am going to make a 2D game from scratch and I don't like Unity as my only IDE is Visual Studio and it does not support Visual Basic (unless i do some dark ritual).

**Comment by flibitijibibo** [comment]
FNA is XNA4, MonoGame is XNA5.

**Comment by beppe9000** [comment]
I do not understand, can you elaborate a bit more please?

**Comment by flibitijibibo** [comment]
If you don't understand the difference between the two then the only good explanation you're going to get is the one you make for yourself by using the two libraries in a real project and comparing accordingly.

**Comment by beppe9000** [comment]
Thanks. What about performance?

**Comment by flibitijibibo** [comment]
Depends on what your program does. Does it do anything yet?

**Comment by beppe9000** [comment]
Nope, as I am still deciding on what framework I will base it on, and then get things done... My question is if the performance in terms of fillrate/fps/input latency/garbage are equal when using FNA vs MonoGame.

**Comment by flibitijibibo** [comment]
They're not equal, but without data it's hard to say what matters and what doesn't. Target the XNA4 spec and compare as you develop, then when you make a decision you can start using extensions as needed. You won't get a real answer without data, nor will you get a completed product regardless of what's supposed to be running it.
