### ISSUE TITLE
XACT clamps Pitch to +/- 12 semitones, FNA does not.

### ISSUE THREAD

**Issue by kiates** [FNA-XNA/FNA#82]
While working on fixing pitch issues, I wrote a test.  In that test 1 semitone is added to the PItch with each loop.  In XACT this is clamped internally to +12 semitones, however the FNA implementation happily allowed it to continue "forever".

**Comment by flibitijibibo** [comment]
I believe this is a SoundEffectInstance bug too, so we can clamp it there assuming it does so in XNA too.

**Comment by flibitijibibo** [comment]
https://github.com/FNA-XNA/FNA/commit/9197bec29f4fcbb3bbcdb90367ed0bb1fabd6cd1
