### ISSUE TITLE
XACT cue state inaccuracies

### ISSUE THREAD

**Issue by kiates** [FNA-XNA/FNA#84]
Various issues related to cue states for example:

  - IsPrepared should go to false once playback begins.
  - In XACT all states are mutually exclusive with the exception of IsPaused which can also be true while IsPlaying is true.
  - A paused cue that is stopped always stops immediately.  The as authored mode is ignored.
  - A cue cannot be paused when in the IsStopping state.  Control is not allowed.

**Comment by flibitijibibo** [comment]
Partially addressed by #85, on Monday I'll be doing a small test to check all the bools at various points in a Cue's lifetime. Something tells me this is going to make less sense than it does now!

**Comment by flibitijibibo** [comment]
Fixed by changes discussed in #85.
