### ISSUE TITLE
Acual XACT pitch clamping range is +/- 2 octaves, not +/- 1 octaves

### ISSUE THREAD

**Issue by kiates** [FNA-XNA/FNA#87]
It actually looks like XACT clamps to +/- 2 octaves. So -2.0 to 2.0 would be the correct clamping range inside SoundEffectInstance instead of the current -1.0 to 1.0 range.  Not sure if XNA only sounds have the same range.

**Comment by flibitijibibo** [comment]
https://github.com/FNA-XNA/FNA/commit/2b69bad54579be459b18c1fe8381800bb053528c
