### ISSUE TITLE
Documentation: deploying signed FNA apps for mac OSX

### ISSUE THREAD

**Issue by mklingen** [FNA-XNA/FNA#89]
This isn't technically an issue with FNA, but I think it should be somewhere in the wiki. 

Apparently, Mac OS sierra now defaults to only running apps that were distributed through the app store, or which were signed using an Apple certified developer certificate (which costs $99 a year, wow thanks Apple!).  In the FNA wiki, there is no mention of this fact. How do we sign apps that were created using monokickstart and FNA? 

The only documentation I can find about signing is for apps [developed using xcode](https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/DistributingApplicationsOutside/DistributingApplicationsOutside.html). Does that mean we have to generate an xcode project to sign games crated with FNA?

**Comment by flibitijibibo** [comment]
Here's a guide to disable Gatekeeper:

https://answers.uchicago.edu/25481

I have never shipped with signed binaries and never will, and I suggest you do the same. If a user refuses to do this, tell them to give you the $99 and they can figure out how to do the CLI codesign for you as well.

Luckily you will never find a user that won't disable it, assuming they haven't already disabled it by the time they get to your game.

**Comment by flibitijibibo** [comment]
Updated guide for Sierra:

https://www.tekrevue.com/tip/gatekeeper-macos-sierra/
